### ISSUE TITLE
WebSession event not getting triggered

### ISSUE THREAD

**Issue by codeMatt** [DoctorMcKay/node-steam-user#10]
Hello all, and thank you in advance :)

I am attempting to create a trading bot, I set up a trade offer manager just like the example yet the 'webSession' event doesn't get fired.

The logged on event fires and returns an eresult of 1 which is a normal log on. I am new to steam trading bots so it could be something retarded but I feel like its all correct and the webSession event is not being fired.

Just so you know I need this event so that I can load the inventory and make offers, if there is a work around to getting the cookies I could use that but this seems like some issue.

Code:

    var SteamUser = require('steam-user');
    var TradeOfferManager = require('steam-tradeoffer-manager');
    var fs = require('fs');

    var SteamClient = new SteamUser();

    var offers = new TradeOfferManager({
	    steam: SteamClient,
	    language: "en",
	    pollInterval: 10000,
	    cancelTime: 300000
    });

    if(fs.existsSync('polldata.json')){
    	fs.readFile('polldata.json', function (err, data) {
    	    if (err) {
	        console.log('Error reading polldata.json. If this is the first run, this is expected behavior: '+err);
    	    } else {
    	        console.log("Found previous trade offer poll data.  Importing it to keep things running smoothly.");
    	        offers.pollData = JSON.parse(data);
    	    }
    	});	
    }

    SteamClient.logOn({
    	account_name: 'xxxxxxxxxxxxxxxx',
    	password: 'xxxxxxxxxxxxxxxx'
    });

    SteamClient.on('loggedOn', function (response) {
        console.log("Logged into Steam with result: " + response.eresult);
    });

    SteamClient.on('webSession', function (sessionID, cookies) {
    	console.log("Got web session event:" + sessionID);
    });

**Comment by DoctorMcKay** [comment]
It's `accountName`, not `account_name`. It's logging on anonymously because you aren't passing the account name properly.
