### ISSUE TITLE
Steam Bot twoFactorCode (2fa) problem

### ISSUE THREAD

**Issue by evanode** [DoctorMcKay/node-steam-user#100]
Hello, sorry for my english i have a problem with steam bot login.. my bot working with no problem on nodejs for windows but on nodejs on freebsd(host) i have problems.. : my 2fa code generated is invalid.. idk why.. and i can't logon on host.. look on my script

`
var TOTP_UserConfig = {"shared_secret":"xxxxxxxxxxxxxxxxxxx/1k/E=","serial_number":"xxx...etc etc (mAfile)

var client = new SteamUser();
var code = SteamTotp.generateAuthCode(TOTP_UserConfig.shared_secret);

var logOnOptions = {
    "accountName": "y",
    "password": "x",
    "twoFactorCode": code
}`

He give me 2fa code but is invalid.. thx for help

**Comment by sp0ok3r** [comment]
Try:

var shared_code = "xxxxxxxxxxxxx";

var client = new SteamUser();
var logOnOptions = {
"accountName": "y",
"password": "x",
"twoFactorCode": SteamTotp.generateAuthCode(shared_code)
}

**Comment by evanode** [comment]
Nope.. i tried to try.. 
Steam Guard App Code: (node:89716) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

Idk.. my code on node for windows work perfect.. thx for reply!

**Comment by evanode** [comment]
He GIVE ME 2FA CODE BUT IS INVALID..

**Comment by sp0ok3r** [comment]
add me [steamlink](http://steamcommunity.com/id/OfficialSp0ok3r/)

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**
