### ISSUE TITLE
joining chats won't work

### ISSUE THREAD

**Issue by Rarapony** [DoctorMcKay/node-steam-user#102]
client.on("chatInvite", function(inviterID, chatID, chatName) {
	client.joinChat(chatID.accountid);
	console.log(chatID);
	console.log(chatName);
})

**Comment by Ne3tCode** [comment]
`client.joinChat(chatID);` works for me.

**Comment by Rarapony** [comment]
I have used chatID in this case instead of chatID.accountid and it did not work

**Comment by Aareksio** [comment]
> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/). Such issues may be ignored!**

`SteamUser.joinChat` works fine, make sure your presence is not set to `Offline`, and `client` is an instance of `SteamUser`.

Code:
```JS
const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');

const secret = require('./secret');

let user = new SteamUser();

user.logOn({
    accountName: secret.username,
    password: secret.password,
    twoFactorCode: SteamTotp.getAuthCode(secret.sharedSecret)
});

user.once('webSession', function(sessionID, cookies) {
    console.log('Web session!');
    user.setPersona(SteamUser.EPersonaState.Online, 'Testing!');
});

user.on('loggedOn', () => { console.log('Logged in!'); });

user.on('chatInvite', (inviterID, chatID, chatName) => {
    console.log(inviterID, chatID, chatName);
    user.joinChat(chatID);
});
```

Output:
```
Logged in!
Web session!
SteamID { universe: 1, type: 1, instance: 1, accountid: 82036586 } SteamID { universe: 1, type: 7, instance: 0, accountid: 10639590 } 'Archi\'s SC Farm'
```

Steam chat:
```
16:58 - Testing! has been invited to chat.
16:58 - Testing! entered chat.
16:58 - Testing! disconnected.
```

**Comment by Rarapony** [comment]
Okay, i'm updating this. As it turns out the code i used was most likely correct. I saw it console.logging what it should have. I wondered why it did not even show an error message or crash when it did not join the chat

As it turns out i made a new account for the bot, and it doesn't meet certain requirements to talk in a group.
