### ISSUE TITLE
Problems with chat members

### ISSUE THREAD

**Issue by Qasde** [DoctorMcKay/node-steam-user#105]
When trying to list all members in group chat it returns only a single user.

> { name: '...',
>         members: { '76561198067864125': { rank: 1, permissions: 891} },
>         private: false,
>         invisibleToFriends: false,
>         officersOnlyChat: false,
>         unjoinable: false } },

other users appear when they join/rejoin chat

**Comment by Qasde** [comment]
I think i have found the issue, in  node-steam-user/components/chat.js (chat enter event):
`for (var i = 0; i < numMembers; i++) {
			member = BinaryKVParser.parse(body).MessageObject;
			this.chats[sid64].members[member.steamid.toString()] = {
				"rank": member.Details,
				"permissions": member.permissions
			};
		}`
It adds the same steamid with each iteration

> debug: [--------] Joined Chat: 103582791458084036
76561198053787900 (printing member.steamid.toString() with each iteration)
76561198053787900
76561198053787900
76561198053787900
76561198053787900
76561198053787900

**Comment by DoctorMcKay** [comment]
Thanks for the report and the info. Fixed in v3.21.3.
