### ISSUE TITLE
Create Account does not work after two.

### ISSUE THREAD

**Issue by Raikiree** [DoctorMcKay/node-steam-user#106]
"I want to create many accounts in short time. But after two success account create can't create more not working. I guess steam block you after two account create.
 
Also i add third minutes for each create still not work after two."

Above is quoted from someone, and I am meeting this same problem now, any suggestions to solve this? Thanks!

**Comment by DoctorMcKay** [comment]
Slow down more.

**Comment by ylms** [comment]
Just curious but, isn't it supposed to be after 5?
