### ISSUE TITLE
Logon with Sentry, requests Auth Code

### ISSUE THREAD

**Issue by Rellfy** [DoctorMcKay/node-steam-user#107]
Hello!

I'm getting the Sentry file from the 'steam' module. When I try to logon using this module, I set the sentry file and it still requests me to input the Steam Guard code. Here's how I'm getting the sentry from Steam.SteamUser:

```js
function MakeSha(bytes) {
    var hash = crypto.createHash('sha1');
    hash.update(bytes);
    return hash.digest();
}

this.steamClientUser.on('updateMachineAuth', (sentry, cb) => { 
	fs.writeFileSync(/* path */, sentry.bytes);

       // Method which uses steam-user module
	this.loginWithSentry();

  	cb({
  		sha_file: MakeSha(sentry.bytes)
  	});

    this.steamClient.disconnect();
});
```

And here, how I set the sentry, reading from the file that was written in the above code.

```js
let sentryFile = fs.readFileSync((/* path */));

this.steamUser.setSentry(sentryFile);

this.steamUser.logOn({
    accountName: this.username,
    password: this.password
});
```

**Comment by DoctorMcKay** [comment]
This should be posted on the forum. How big is the file? It should be 2 KB exactly.

**Comment by Rellfy** [comment]
Oops, sorry for my mistake.

And the file is actually 1KB. When I look into older sentry files of other accounts, they are 2KB. Not sure why this is happening.
