### ISSUE TITLE
Idling custom games while blocked through other session doesn't work

### ISSUE THREAD

**Issue by PixLSteam** [DoctorMcKay/node-steam-user#108]
Due to lines 22 to 28 in components/apps.js, you can't start idling while another session is blocking your playingState. While this makes sense when using Steam's game library, this check doesn't account for custom games (which you could in theory still play). tl;dr: Please let us idle custom games (games passed as strings to gamesPlayed) while the playingState is blocked.

Sincerely, PixL

**Comment by DoctorMcKay** [comment]
Fixed in v3.21.1.
