### ISSUE TITLE
Protobuf error - Error: Parse error at line 1: unexpected '

### ISSUE THREAD

**Issue by Psycho345** [DoctorMcKay/node-steam-user#109]
> /nodesteamuser/node_modules/protobufjs/dist/protobuf.js:784
>                 throw e;
>                 ^
> Error: Parse error at line 1: unexpected '

That character at the end is ETX.

I tried:
- reinstalling everything 10 times,
- basicbot.js example,
- different node versions,
- installing manually,
- copy-pasting protobufs from this git,
- [this fix](https://github.com/systemmovie/node-steam-user/commit/02920915c30173d8db5de9acdee6c2b82bbb7236) (It 'works' but doesn't even log in).

Something must be broken.

**Comment by welwood08** [comment]
I also encountered this as soon as I `require('steam-user')`.

It looks like `./components/protobufs.js` is trying to load `./protobufs/google` as if it were a file when it is in fact a directory. The fix linked above would seem to agree with me.

What is the intended behaviour here? Obviously directories shouldn't be assumed to be files in any case, but does the loading need to be recursive (presumably if login doesn't work with the patch then yes)? How come this is only coming to light now when none of that code has been touched in 2 years?

**Comment by DoctorMcKay** [comment]
What operating system are both of you on?

**Comment by welwood08** [comment]
I was testing my code in a jail on a FreeNAS server when I encountered the problem. I just tried running exactly the same code on a Windows machine via a network share - it does not produce the error. OP of #50 appears to have been using a Ubuntu machine, so *nix vs Windows seems to be the common element indeed.

**Comment by DoctorMcKay** [comment]
All my deployments end up on Linux (Ubuntu and CentOS specifically) so it doesn't seem like it's definitely Linux's fault.

**Comment by welwood08** [comment]
Following the breadcrumbs, looks like `Protobuf.loadProtoFile` expects `Protobuf.Util.fetch` to return null in the case of an error reading the file. That function only returns null if `fs.readFile*` generates an exception, which it seems to do on my Windows machine. In my FreeBSD jail, it succeeds with `<Buffer 03 00 00>` when reading the google directory as a file. Bug in this old version of protobuf.js?

**Comment by Psycho345** [comment]
I also run it on FreeBSD. I checked everything again and I can confirm that the fix works. I've probably broken something while playing with the files first time.
