### ISSUE TITLE
Unable to receive requestValidationEmail() callback

### ISSUE THREAD

**Issue by ryantology** [DoctorMcKay/node-steam-user#11]
I was sure this was working this morning but as of about 2 hours ago nothing I seem to do will receive a full callback from `requestValidationEmail()`. This is tested with accounts that were recently created using the `createAccount()` method. 
Below is example code:

```node

client = new SteamUser();
client.logOn({
	username: '*********',
	password: '*********'
});

client.on('loggedOn', function(){
	console.log('Logged In');
	client.requestValidationEmail(function(response){
		console.log(response);
		// Nothing is logged here.
	})
});
```

Additionally the calls for `enableTwoFactor()` are failing with a buffer exception (also previously working IIRC):

```node
client = new SteamUser();
client.logOn({
	username: '********',
	password: '********'
});

client.on('loggedOn', function(){
	console.log('Logged In');
	client.enableTwoFactor(function(status, secret, revocationCode) {
		console.log(status);
		console.log(secret);
		console.log(revocationCode);
	});
});
```

```
node_modules/steam-user/components/twofactor.js:26
			callback(body.status, body.shared_secret.toBuffer(), body.revocation_code);
			                                        ^

TypeError: Cannot read property 'toBuffer' of null
```

**Comment by DoctorMcKay** [comment]
The first problem is probably caused by Steam being its normal unreliable self.

The second is likely because you don't have a validated email and I need to properly handle that.

**Comment by ryantology** [comment]
I feel like something may have changed today (possibly why there was a 1 hour outage?). With the same account when I login with the steam app I have the button for 'request verification email' which does send and I receive it. Yet the `requestValidationEmail()` method does not return a callback. Is there another step that is needed after create account?

I tried digging into the `node-steam` lib to log the socket data but I quickly got in over my head on the data.

**Comment by DoctorMcKay** [comment]
I just tested it and it still works fine for me.

**Comment by ryantology** [comment]
I know this may sound silly, but do you have an example? I just tried a fresh project with only `steam-user` installed and the file literally has the exact lines above and I get no response call back. I just tried creating new accounts and same thing. Also doesn't work with old accounts.

Would have been nice to do this programatically but probably just going to do it by hand :)

**Comment by DoctorMcKay** [comment]
Can you add this and give me the output?

```js
client.on('debug', function(msg) {
    console.log(msg);
});
```

**Comment by ryantology** [comment]
```
Unhandled message: 1303
Sending message: 5514
Unhandled message: 1305
Unhandled message: 5501
Unhandled message: 5501
Unhandled message: 5501
Handled message: 751
Logged In USERXXXXXX
Sending message: 5448
Unhandled message: 783
Unhandled message: 880
Unhandled message: 5480
Unhandled message: 880
Unhandled message: 1
```

**Comment by DoctorMcKay** [comment]
5449 is the response message. Steam just isn't sending it, and I have no idea why. Is your email already validated perchance?

**Comment by vejbuch** [comment]
Logged In
{ status: 29 }
undefined
undefined

why? :( :wheelchair:

**Comment by vejbuch** [comment]
Sending message: 5577
Sending message: 5583
Sending message: 7524
Unhandled message: 768
Unhandled message: 768
Handled message: 5456
Handled message: 782
Handled message: 767
Handled message: 5553
Unhandled message: 5587
Handled message: 780
Unhandled message: 798
Handled message: 5528
Unhandled message: 779
Unhandled message: 850
Handled message: 5430
Unhandled message: 783
Unhandled message: 880
Unhandled message: 5480
Unhandled message: 880
Unhandled message: 1
Unhandled message: 1
Handled message: 7523
Unhandled message: 1
Unhandled message: 5510
Unhandled message: 1

**Comment by ryantology** [comment]
Does this have to do with creating users? https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/resources/EResult.js is a list of typical error codes.

**Comment by vejbuch** [comment]
Thanks so much! But I'm not sure that duplicates the requirements :(

my code

var SteamUser = require('steam-user');
//var SteamTotp = require('steam-totp');
//var code = SteamTotp.generateAuthCode('cnOgv/KdpLoP6Nbh0GMkXkPXALQ=');
//console.log(code);
var client = new SteamUser();
client.logOn({
	"accountName": "****",
	"password": "E2540*****"
});

client.on('loggedOn', function(){
    console.log('Logged In');
    client.enableTwoFactor(function(status, shared_secret) {
        console.log(status);
        console.log(shared_secret);
    });
});
client.on('error', function(e) {
	// Some error occurred during logon
	console.log(e);
});

**Comment by vejbuch** [comment]
Okey, now its okey :) thanks guys
