### ISSUE TITLE
[Suggestion] Add boolean to GetProductInfo to automatically get tokens for apps that miss it

### ISSUE THREAD

**Issue by Royalgamer06** [DoctorMcKay/node-steam-user#112]
So far I had to handle apps with missing tokens myself, but it's getting a bit tedious. It would be great if this would get build in natively into the function. It will save me and others some coding. Besides, I believe the official SteamCMD get's tokens for apps that miss it by default. 
Here is the snippet of code I am using for this:

    function getSubInfo(subid, callback) {
    client.getProductInfo([], [subid], function(apps, packages) {
        client.getProductInfo(packages[subid].packageinfo.appids, [], function(apps) {
            var tokenlessAppids = [];
            for (appid in apps) {
                if (apps[appid].missingToken) {
                    tokenlessAppids.push(parseInt(appid));
                }
            }
            if (tokenlessAppids.length > 0) {
                client.getProductAccessToken(tokenlessAppids, [], function(tokens) {
                    var tokenAppids = [];
                    for (appid in tokens) {
                        tokenAppids.push({ appid: parseInt(appid), access_token: tokens[appid] })
                    }
                    client.getProductInfo(tokenAppids, [], function(tokenApps) {
                        for (appid in tokenApps) {
                            apps[appid] = tokenApps[appid];
                        }
                        callback(subid, apps);
                    });
                });
            } else {
                callback(subid, apps);
            }
        });
    });
    }
    

This can be converted into something more general. I rather avoid forking the project and creating a pull request, but if you rather have that, I can do it.
Kind regards,
Royalgamer06

**Comment by DoctorMcKay** [comment]
That's a good idea. I'll see when I can get around to it.

**Comment by Royalgamer06** [comment]
So, did you get around to it?

**Comment by Royalgamer06** [comment]
How many more months will it take? 😅

**Comment by Royalgamer06** [comment]
I ended up doing it myself just now: https://github.com/DoctorMcKay/node-steam-user/pull/129
I hope it's OK. My tests were successful.

**Comment by Royalgamer06** [comment]
Almost half a year has passed... When will this already-made feature be added?

**Comment by Aareksio** [comment]
Let me find the quote... :wink:
> This exists because of how painfully slow it is to get new things implemented [...]

**Comment by DoctorMcKay** [comment]
The issues raised in the review in the PR were never addressed. I will fix them myself.

**Comment by Royalgamer06** [comment]
Issue closed

**Comment by Royalgamer06** [comment]
One more thing. Apparently, according to steamdb's dev xPaw, tokens for packages are rarely/never used:
![image](https://user-images.githubusercontent.com/4411977/34791445-494274bc-f645-11e7-9e8d-4015deebb87b.png)
