### ISSUE TITLE
Function redeemKey() returns undefined SubID

### ISSUE THREAD

**Issue by Royalgamer06** [DoctorMcKay/node-steam-user#115]
Somewhere late of the 22nd of June, redeemKey started returning `{ undefined: 'GameTitle' }` for me as package(s). The game titles are correct, but the subid's are not. I assumed it was because of the Summer Sale that just started, but it still hasn't been resolved. I have this bug across devices. I don't think there is anything wrong with the code. Even if the first line of the callback is `console.log(packages);` it prints the undefinied subid. Am I the only one with this issue? Or does it happen for others as well?

**Comment by PixLSteam** [comment]
As far as I know, Valve removed support for named subs: https://twitter.com/SteamDB/status/570951174028963840

**Comment by Royalgamer06** [comment]
It worked all fine before 22th of june.

**Comment by PixLSteam** [comment]
Might be a change made by Valve. I guess McKay might have a clue

**Comment by Royalgamer06** [comment]
Do you also experience this issue?
Here is a steam key to test with `T0JT7-JTIDD-5JV8Y`

**Comment by DoctorMcKay** [comment]
Cannot reproduce.

    { '0': 1, '1': 0, '2': { '128342': 'Guardian\'s Oath' } }

**Comment by Royalgamer06** [comment]
I tried so many variations. Tried to rule out as much as I can. However I can't figure out what the issue is. Is there some way I can send you my code privately, so you can inspect? My program monitors your clipboard redeems detected steam keys or wallet codes, shows a windows notifications and posts to steam friends activity.

**Comment by Ne3tCode** [comment]
Patch:
```patch
diff --git a/components/apps.js b/components/apps.js
index 42c2f1b..4484c1c 100644
--- a/components/apps.js
+++ b/components/apps.js
@@ -499,7 +499,8 @@ SteamUser.prototype.redeemKey = function(key, callback) {
 		var recipeDetails = BinaryKVParser.parse(body.purchase_receipt_info).MessageObject;
 		if (recipeDetails.LineItemCount > 0) {
 			recipeDetails.lineitems.forEach(function(pkg) {
-				packageList[pkg.PackageID] = pkg.ItemDescription;
+				var packageID = pkg.PackageID || pkg.packageID || pkg.packageid;
+				packageList[packageID] = pkg.ItemDescription;
 			});
 		}
```
Also https://github.com/DoctorMcKay/node-steam-user/pull/36#issuecomment-164859965

**Comment by DoctorMcKay** [comment]
I have no way of testing that patch, but I believe it. Classic Valve.

**Comment by Royalgamer06** [comment]
Look at that! It actually worked 😄
