### ISSUE TITLE
getEncryptedAppTicket Can't useful when I want to get PUBG's ticket

### ISSUE THREAD

**Issue by leehark** [DoctorMcKay/node-steam-user#119]
when I use NetHook,I can't find the Message of getEncryptedAppTicket and when I call the function use node , it is not useful,I want to know whether it is valid now.

**Comment by DoctorMcKay** [comment]
This is a better question for the [forum](https://dev.doctormckay.com).

If you aren't observing PUBG requesting an encrypted appticket, then it probably isn't using them anymore.
