### ISSUE TITLE
You're trying to log on with a decoy sentry file.

### ISSUE THREAD

**Issue by EduardChernikh** [DoctorMcKay/node-steam-user#12]
When i'm trying to convert my ssfn file to sentry using this method:
var hash = Crypto.createHash('sha1');
hash.update(ssfn_file);
sentry = hash.digest();

I'm getting this error: You're trying to log on with a decoy sentry file. You're probably looking for the sentry file that's hidden.

What does it mean? Please help me. Thanks.

**Comment by DoctorMcKay** [comment]
Two things:

1. You do not need to hash any sentry files to use them with node-steam-user. It will accept the entire ssfn just fine.
2. As the error implies, the sentry file that you're using is a decoy. In your Steam directory, there is a visible ssfn file, and a hidden one. Show hidden files in Windows and grab the hidden one.
