### ISSUE TITLE
Can't set Custom Game

### ISSUE THREAD

**Issue by TheRhanderson** [DoctorMcKay/node-steam-user#121]
What's the correctly way to make a Non Steam Game visible?
I've tried:

bot.gamesPlayed(["test name", 730]);
And

bot.setGameName(["teste"]);
Still shows CS:GO as currently game running.

**Comment by PixLSteam** [comment]
Have you tried inverting the array order?

**Comment by TheRhanderson** [comment]
I'm using:

bot.on('loggedOn', function(details) {
    console.log('[STEAM] Logged in.');
    bot.setPersonaState(Steam.EPersonaState.Online);
    bot.gamesPlayed(["Game Test"]);
});

If i don't put any appID, Steam account just goes online, but does not shows "Game Test" as currently non-game

**Comment by liamcloss** [comment]
`    bot.gamesPlayed("Game Test");`

not 

`    bot.gamesPlayed(["Game Test"]);`

**Comment by PixLSteam** [comment]
That shouldn't be the issue, you can run multiple games simultaneously

**Comment by TheRhanderson** [comment]
I get this if I use the code:
`bot.gamesPlayed("Game Test");`

![screenshot_6](https://user-images.githubusercontent.com/24517851/28242718-9d4a062c-6989-11e7-9845-2a0ff147f674.png)

**Comment by PixLSteam** [comment]
Do you use steam-user or steam?

**Comment by DoctorMcKay** [comment]
He's using node-steam, which isn't what this is.

**Comment by TheRhanderson** [comment]
Yes, I didn't noticed about that. I changed the module and now it's working!
