### ISSUE TITLE
If I am using this, I still need node-steamcommunity?

### ISSUE THREAD

**Issue by kamilml** [DoctorMcKay/node-steam-user#123]
I am working in a steam trade bot just for send offers, not anymore. And have to use `node-steamcommunity` because I need necessarily the `startConfirmationChecker` metod.

But I want to use just this module `node-steam-user` because the maker says *this is a improve*... the problem is exists the `startConfirmationChecker` metod in this module? :(

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

The different modules are good at different things. steam-user only handles communication with the Steam CM servers. Confirmations don't go through those servers, so you need steamcommunity for that. In my opinion, you should use steam-user, steamcommunity, and steam-tradeoffer-manager for the most robust system.
