### ISSUE TITLE
[Suggestion] Add Family Sharing options

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#128]
I'd really like to see options to authorize and deauthorize accounts for steam family sharing via node.js. This way if you need to use license of an app, you don't have to use your main account. Also, I am not even sure if it is possible to "authorize" family sharing a node.js client bot manually. Can I just use steam client and then after libraries are shared, use node.js and expect it to still be shared? Anyway, I can tell you my idea for an application of this feature I have. I'd like to use it as donation option. Users can share their libraries with me without having to do this manually.

Then, I'd also like to see an option for GetOwnedApps to exclude family shared apps. Maybe add a boolean as option parameter (include family shared by default). I think this can be achieved by querying http://store.steampowered.com/dynamicstore/userdata/, but you already have this function in node-steam-store, if I am not mistaken.

**Comment by Royalgamer06** [comment]
This may help:
https://github.com/SteamDatabase/Protobufs/blob/master/steam/steammessages_deviceauth.steamclient.proto

**Comment by Revadike** [comment]
Okay, I was so confused why my bot said I owned a certain appid, using `getOwnedApps()`. The steam store didn't say I owned it. Yet I was able to install it via steam://install/appid. Then when I check my steam library , I realize it's because the app was family shared.
This is unwanted behavior, at least by default. Please, look into (an option to) excluding family shared games from `getOwnedApps()`. It's probably a flag you need to check with the licenses.

**Comment by Revadike** [comment]
found it! It's `owner_id`

**Comment by Revadike** [comment]
Maybe reopen this issue, because it was only one of the features that was suggested. I also wanted to have options to authorize and deauthorize devices/owners.
