### ISSUE TITLE
loggedOn enhancement

### ISSUE THREAD

**Issue by Papzi** [DoctorMcKay/node-steam-user#13]
I would like to have a feature to test if you are currently logged in or not since if you try to login it causes an error. I know i could use the LoggedOn event to save it but i cant log when it logs off.

**Comment by DoctorMcKay** [comment]
If the `steamID` property is `null`, you're not logged on. Otherwise, you are.

There currently isn't any way to check if the SteamUser is in the process of (re)connecting, would you like something for that?
