### ISSUE TITLE
Group Invite Response

### ISSUE THREAD

**Issue by Royalgamer06** [DoctorMcKay/node-steam-user#130]
I'm not sure if this is the right division to ask this, but I noticed Valve added a response to group invites saying which persons were unable to invite to, at least in the web request. It would be great if you could incorporate this into a callback! :)

**Comment by DoctorMcKay** [comment]
There is no such functionality available in the client.

**Comment by Royalgamer06** [comment]
So yeah, wrong division. That's alright. I don't really need it. I thought it might be useful for others.
