### ISSUE TITLE
requestValidationEmail not working

### ISSUE THREAD

**Issue by Maarethyu** [DoctorMcKay/node-steam-user#131]
The function `user.requestValidationEmail` doesn't execute the callback.

Here is the very basic code im using
````
const SteamUser = require('steam-user');
const user = new SteamUser(),

user.logOn({username, password});

user.on('loggedOn', _ => {
    user.requestValidationEmail(console.log);
});
````

The account im using is completly new

I tried this over 3 different days so it's probably not because of steam being steam

Since the email used for this account is a kind of one-time use email, I tried changed the email but the `user.changeEmail` function does not execute the callback either

The debug event output:
```
// user.logOn()
Unhandled message: 1303
Unhandled message: 1305
Unhandled message: 5501
Unhandled message: 5501
Handled message: 751
Handled message: 783
Got list of 80 WebSocket CMs, with percentage to use at 34%
Handled message: 880
Unhandled message: 5480
Handled message: 880
// user.requestValidationEmail()
Sending message: 5448
// user.changeEmail()
Sending message: 5544
````

**Comment by Ne3tCode** [comment]
https://github.com/DoctorMcKay/node-steam-user/blob/f0094b33fb2766bb65b177920886009ab9096792/components/account.js#L26
There should be `body.flip()`, otherwise it will be an empty buffer.

**Comment by DoctorMcKay** [comment]
Try v3.21.8 and see if that works for you. If not, please reopen.

**Comment by Maarethyu** [comment]
Still doesn't work, no change in the debug messages, exactly the same as far as I see.

**Comment by DoctorMcKay** [comment]
I cannot reproduce, it works fine for me (even on the older version). There must be some problem with your code.
