### ISSUE TITLE
Cant pass email, getting error code 8

### ISSUE THREAD

**Issue by Schknheit** [DoctorMcKay/node-steam-user#133]
Hey, I'm trying to create accounts but cant pass the email as a function. I'm getting error code 8

`function email_parser(){
	var fs = require('fs');
	var email_count = "";
	var array = [];
	
	var array = fs.readFileSync('email.txt').toString().split("\n");
	for(var i = 0; i < array.length; i++) {
		email_count = array[i];
	}
 }`

` email = email_parser();
  client.createAccount(username, password, email, function (result) {
    if (result == SteamUser.Steam.EResult.OK) {
      console.log('>> Account created successfully.');`

thanks!

**Comment by andrewda** [comment]
I don't think `email_parser()` does what you want it to do... Your `email` variable is going to be `undefined` (and therefor Steam is sending you the error code 8, or `InvalidParam`. You need to make sure `email` contains a valid email address (try `console.log`ing it before using it in the `createAccount` method to make sure).

**Comment by andrewda** [comment]
This isn't an issue with the repository, though.

> **Have a question about the module or coding in general? _Do not create a GitHub issue_. GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/). Such issues may be ignored!**

**Comment by Schknheit** [comment]
Nevermind, i forgot the `return email_count` :P
