### ISSUE TITLE
logOff error

### ISSUE THREAD

**Issue by Schknheit** [DoctorMcKay/node-steam-user#134]
Im getting the "Already looged on, cannot log on again" even though I call `client.logOff` in the end of the function!? I know I'm stupid!.

**Comment by Aareksio** [comment]
> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/). Such issues may be ignored!**

Too little info to help.

**Comment by Schknheit** [comment]
Some code I found about account creation and edited for my purposes.

https://pastebin.com/NfH4AaCs

I was getting this error  #106 so I did some ugly code to bypass it. But its not working as usual.
