### ISSUE TITLE
node-stats-reporter keeps process alive

### ISSUE THREAD

**Issue by xaviergmail** [DoctorMcKay/node-steam-user#135]
I noticed the process wasn't terminating properly after calling both user.disconnect and client.disconnect.

[wtfnode](https://www.npmjs.com/package/wtfnode) reports the following:

- Timers:
  - (600000 ~ 10 min) reportStats @ /home/xavier/projects/redacted/node_modules/@doctormckay/stats-reporter/index.js:45
- Intervals:
  - (3600000 ~ 60 min) reportStats @ /home/xavier/projects/redacted/node_modules/@doctormckay/stats-reporter/index.js:44

As a temporary fix for anyone else who tried looking around for the answer, see: https://github.com/DoctorMcKay/node-stats-reporter#opting-out

**Comment by DoctorMcKay** [comment]
Hm, I thought I had unref'd those timers. I did that and published 1.0.3 for stats-reporter which should fix the issue.
