### ISSUE TITLE
Catching failed steamGuard Code

### ISSUE THREAD

**Issue by HybridFox** [DoctorMcKay/node-steam-user#139]
Hello,

Whenever steam fails to use a steamGuard code (mostly since the previous one is already used or it's incorrect) it does not fire an error or disconnected event, instead it keeps trying to use the same steamGuard wich eventually results in a RateLimitExceeded error.

Is there a way to stop it from instantly trying to use the old steamGuard code and let it wait 20-30s when it can generate a new steamGuard code.

**Comment by DoctorMcKay** [comment]
As per [the docs](https://github.com/DoctorMcKay/node-steam-user#steamguard), there is a `lastCodeWrong` argument which tells you if the `steamGuard` event was emitted because you provided a wrong code.
