### ISSUE TITLE
createAccount

### ISSUE THREAD

**Issue by steamaccount123** [DoctorMcKay/node-steam-user#142]
```
const SteamUser = require('steam-user');
var create = new SteamUser();

create.logOn();
setTimeout(1000);
create.createAccount("username", "password", "email"), function (result, steamid) {
    if (steamid) {
        console.log("created account" + steamid);
    }
}
```

This doesnt seem to create me a new account, i have no idea what i am doing wrong, sorry i only know how to code on c#. Can you help me with what to do?
thanks, jim :D

**Comment by Aareksio** [comment]
`setTimeout` is not a `sleep`.  

> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/). Such issues may be ignored!**

**Comment by DoctorMcKay** [comment]
^ and even if it was, that still wouldn't work as you'd be blocking the module from dealing with the connection in the background.

**Comment by steamaccount123** [comment]
what should i do to correct it?
