### ISSUE TITLE
TimeoutOverflowWarning

### ISSUE THREAD

**Issue by mworkg** [DoctorMcKay/node-steam-user#143]
After update to Node V9, i got next error on `.logOn`
![pt_k9zh6sl66tnkyi5oxog](https://user-images.githubusercontent.com/19779985/32414364-8dc41f74-c22d-11e7-929b-0a6e51bf4848.png)

**Comment by Aareksio** [comment]
Do you use tradeoffer-manager? If so, it's probably originating from the bug which have been fixed in 2.9.1.
