### ISSUE TITLE
Get Steam.steamClient for node-csgo

### ISSUE THREAD

**Issue by exellian** [DoctorMcKay/node-steam-user#146]
I am currently programming a Inventoryloader-Bot and I need float values. So I can exstract the inspect-link, but I didn't managed to make a protobufjs request. So I found the node-csgo module for this purpose. My problem is now that the module doesn't work with this kind of Steam User so I want to ask how can I create a node-steam Client Object from a steamuser of this module?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

You can use [node-globaloffensive](https://www.npmjs.com/package/globaloffensive).

**Comment by exellian** [comment]
Thanks!! And sorry for writing a question in the issues tab.
