### ISSUE TITLE
Generating auth session tickets

### ISSUE THREAD

**Issue by molenzwiebel** [DoctorMcKay/node-steam-user#148]
It'd be great if there were methods to generate auth session tickets, so we can use this module to connect to game backends without having Steam or the game running to generate the ticket using Steamworks. Apologies if this was already requested earlier, I couldn't find anything using the search feature.

Some references I found: 
- [The steamworks documentation on the topic of auth session tickets](https://partner.steamgames.com/doc/features/auth#3).
- [A struct detailing the contents of the ticket](https://github.com/SteamRE/SteamKit/blob/master/Resources/Structs/steam3_appticket.hsl). This one seems to not be 100% complete anymore, but most of the fields seem to still be in the payload.
- An example ticket:
```
1400000066BF5D004A6D2E95E7AFDA0301001001A852365A18000000010000000200000074CBF15400000000F19C0C0002000000B20000003200000004000000E7AFDA030100100120D2080074CBF1540138A8C000000000A852365A2802525A01008440020000000000D5AAC4949A50F4A47D15155FA94DCD89C3AFE391E04D1F901F1A420F8B04F41BED286F014C9D8B40656CEBE34881E53860BFA60620A41BE95E817FB9AD3EA073B6E316A6939B10311F186FFD365A14010868B9DB2EE454FECD0CCFE6E69EC120DCFB79676C6330CFEA8A4CA14DA86DCA5FFFB26C019F56285612F9E83F0FDDDB
```

**Comment by DoctorMcKay** [comment]
This is now up, but experimental.

https://github.com/DoctorMcKay/node-steam-user/blob/master/doc/AppAuth.md#getauthsessionticketappid-callback
