### ISSUE TITLE
msg in not defined

### ISSUE THREAD

**Issue by darkredstudio** [DoctorMcKay/node-steam-user#15]
Hi Alexander,
In \steam-user\components\logon.js:287
var e = new Error(msg);
is a little bug: msg in not defined
![screen](https://cloud.githubusercontent.com/assets/5769400/11109115/6ffa5e20-88ed-11e5-92c4-996cc5f4448a.png)

**Comment by DoctorMcKay** [comment]
Thanks for the report, this is fixed in 1.12.2.
