### ISSUE TITLE
bot doesn't accept friend requests sent when bot is offline

### ISSUE THREAD

**Issue by tldrjumps** [DoctorMcKay/node-steam-user#151]
I guess friendRelationship event only listen the notification of friends request while the bot online, Can request following event instead of manually checking friend list and their state?

https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#relationships

**Comment by DoctorMcKay** [comment]
[`friendsList`](https://github.com/DoctorMcKay/node-steam-user#friendslist) does what you want. Wait for that to be emitted then check [`myFriends`](https://github.com/DoctorMcKay/node-steam-user#myfriends).
