### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Schknheit** [DoctorMcKay/node-steam-user#152]
I'm getting error 20 while creating a new account. Its valve fuckup or they changed something?

**Comment by SeRi0uS007** [comment]
It's probably because the Steam Client is now loads "Create Account" webpages from steampowered.com (https://store.steampowered.com/join/)...

**Comment by Stuffa1991** [comment]
They removed the CM Servers capability of creating new accounts, https://store.steampowered.com/join/ is the only option, write a script or do it manually is the only option for now.
