### ISSUE TITLE
Cannot install on Raspberry pi!

### ISSUE THREAD

**Issue by Wolfleader101** [DoctorMcKay/node-steam-user#153]
Hello, i am getting this error when i try to install this module.
`
pi@raspberrypi:~/Desktop/Steam-Bot $ npm install steam-user
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'doctormckay/proxy-agent' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'steam-user'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "steam-user"
npm ERR! cwd /home/pi/Desktop/Steam-Bot
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/Steam-Bot/npm-debug.log
npm ERR! not ok code 0
`

**Comment by DoctorMcKay** [comment]
Your npm is ancient. Update it.

**Comment by Wolfleader101** [comment]
oh thank you for such a quick response. never thought of that
