### ISSUE TITLE
Event not being Triggered

### ISSUE THREAD

**Issue by Wolfleader101** [DoctorMcKay/node-steam-user#155]
Hello, i am getting issues with events being triggered. for example this isnt working. I am not getting any errors 
```client.on('friendRelationship', (steamid, relationship) => {
  if (relationship === 2) {
    client.addFriend(steamid);
    client.chatMessage(steamid, "Hello, Thank you for adding me i hope you enjoy my Services :steamhappy:");
    console.log("Wolfee Bot Added " + steamid + " as a friend");
  }
});
```

**Comment by DoctorMcKay** [comment]
Most likely it *is* being triggered and your code just isn't working. Are you getting any console output? Can you try putting a console.log outside the if?

**Comment by Wolfleader101** [comment]
put a console.log(err) and still notning :/

**Comment by Wolfleader101** [comment]
welp i am not sure why this sint working still :/

**Comment by Wolfleader101** [comment]
@DoctorMcKay have you found a fix yet?

**Comment by andrewda** [comment]
Please show more of your code so we can help diagnose the issue.

**Comment by Wolfleader101** [comment]
```//ALL NEEDED MODULES
const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');
const steamCommunity = require('steamcommunity');
const TradeOfferManager = require('steam-tradeoffer-manager');
const config = require('./config.json');


const client = new SteamUser();
const community = new steamCommunity();
const manager = new TradeOfferManager({
  steam: client,
  community: community,
  language: 'en'
});


const AccountOptions = {
  accountName: config.accountName,
  password: config.password,
  twoFactorCode: SteamTotp.generateAuthCode(config.shared_secret)
};

//logs bot into steam and sets game
client.logOn(AccountOptions);
client.on('loggedOn', () => {
  console.log("Bot successfully logged on!");

  client.setPersona(SteamUser.Steam.EPersonaState.Online);
  client.gamesPlayed("BEING WORKED ON!!");
});


//trading
client.on('webSession', (sessionid, cookies) => {
  manager.setCookies(cookies);
  community.setCookies(cookies);
  community.startConfirmationChecker(10000, config.identity_secret);
});

manager.on('newOffer', offer => {
  if (offer.partner.getSteamID64() === '-----------') {
    offer.accept((err, status) => {
      if (err) {
        console.log("test");
        console.log(err);
      } else {
        console.log("test");
        console.log(`Accepted Offer. ${status}.`);
      }
    });
  } else {
    offer.decline(err => {
      if (err) {
        console.log(err);
      } else {
        console.log("Offer Declined.");
      }
    });
  }
});

// Handling  Friend Requests

client.on('friendRelationship', (steamid, relationship) => {
  if (err) {
    console.log(err);
    console.log('test');
  } else {
    if (relationship === 2) {
      client.addFriend(steamid);
      client.chatMessage(steamid, "Hello, Thank you for adding me i hope you enjoy my Services :steamhappy:");
      console.log("Wolfee Bot Added " + steamid + " as a friend");
    }
  }

});

``` here is the whole thing :)

**Comment by andrewda** [comment]
Ok, so you should probably head over to the forum as referenced in the README:

> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the dedicated forum.**

As for your code, there is no `err` in the `friendRelationship` event handler, so that'll be `undefined`. Also, make sure you're receiving the "Bot successfully logged on!" message in your console and verify that you're adding the bot's account correctly from an account that's not already friends with the bot.

**Comment by Wolfleader101** [comment]
alright so i have changed up the code and removed the` err `in `friendRelationship` and the bot logs on as it always did. My friend who is trying to add the bot has a pending invite for it and still doesn't work.

Also my trading event doesn't work either.

**Comment by Wolfleader101** [comment]
mmm still no solution

**Comment by DoctorMcKay** [comment]
You would have been helped sooner had you gone to the forum as instructed.

`friendRelationship` doesn't get emitted on logon, only when it changes while you're online. To detect pending friend requests you missed, check `myFriends` after [`friendsList`](https://github.com/DoctorMcKay/node-steam-user#friendslist) gets emitted.
