### ISSUE TITLE
gamesPlayed not working?

### ISSUE THREAD

**Issue by Tuccinator** [DoctorMcKay/node-steam-user#157]
I have tried every method mentioned in the wiki but haven't been able to get it to work properly. The only method that works is specifying a "non-Steam game", otherwise nothing happens. Below are the methods I tried:

```
gamesPlayed(730, true);
gamesPlayed([730], true);
gamesPlayed({ game_id: 730, game_extra_info: 'Counter Strike: Global Offensive' }, true);
gamesPlayed([{ game_id: 730, game_extra_info: 'Counter Strike: Global Offensive' }], true);
```

This is the only one that seems to work:
`gamesPlayed(['Counter Strike Global Offensive'], true);`

**Comment by ekifox** [comment]
that doesnt work for me too. So, ``setPersona(SteamUser.EPersonaState.Online)`` too.
