### ISSUE TITLE
getAuthSessionTicket

### ISSUE THREAD

**Issue by myserywork** [DoctorMcKay/node-steam-user#158]
Hello, recently i saw your post about get game ticket. is there anyway to get PUBG game Ticket ?

GetEncryptedAppTicket wont work it gives me a error 

client.on("loggedOn", function (dataAndEvents) {

    console.log("[BOT] Signed in!");
client.getEncryptedAppTicket(578080, function(err,ticket){

console.log(ticket);
});
});

it gives undefined var... is there anyway to get the  ticket like in SteamWorks :  Using this function 

 greenworks.getAuthSessionTicket((data) => {
        ticket = data.ticket.toString('hex').toUpperCase();
console.log(ticket);
        resolve(ticket);
      }, (err) => {
console.log('err');
        reject(err);
      });

it returns something like this : 14000000AA709D6426279EE4DF689D1901001001DBEF735A180000000100000002000000A961CDB14E0FA8C0288A2C0021000000B20000003200000004000000DF689D190100100120D20800A961CDB14E0FA8C000000000D2DF735A528F8F5A0100844002000000000090A62D0F6CDB2A5F4E54A765AAD6D477A384ECF2DAF14CC7FA13A7E925FC7999FB53990D7AC185A77793C559481A674FCBF98774A9F723590940032FA61CB3CC6C19E931D55A19ADB0CEE94DBDF6104BC9FE5F97F8BBDA968F2E2FAD52C305B250DD8E6E3C8C317E960996F1F1AEBA774D602C14E5CE4989F30AB231D5B54355

**Comment by DoctorMcKay** [comment]
I published some basic appticket stuff in v3.35.0.

https://github.com/DoctorMcKay/node-steam-user/blob/master/doc/AppAuth.md#getauthsessionticketappid-callback

**Comment by myserywork** [comment]
After doing the tests
i've see that it gives me a ticket but i dont know how to make it in the format that i gave up there

```
client.on("loggedOn", function (dataAndEvents) {
    console.log("Signed in!");
			client.getAuthSessionTicket(578080, function(err,ticket){
			let parsed = SteamUser.parseAppTicket(ticket);
			console.log(parsed);
			
			console.log(ticket);
		});
});

```

i recive this response runiing that code 


```
{ authTicket: <Buffer 14 00 00 00 36 ce 04 10 fa c8 78 64 df 68 9d 19 01 00 10 01 b0 79 74 5a 18 00 00 00 01 00 00 00 02 00 00 00 aH 61 cd b1 00 00 00 00 26 00 00 00 01 00 ... >,
  gcToken: '72397573773342019',
  tokenGenerated: 2018-02-02T14:46:08.000Z,
  sessionExternalIP: '177.205.97.169',
  clientConnectionTime: 38,
  clientConnectionCount: 1,
  version: 4,
  steamID: SteamID { universe: 1, type: 1, instance: 1, accountid: 429746399 },
  appID: 578080,
  ownershipTicketExternalIP: '177.205.97.169',
  ownershipTicketInternalIP: '186.173.240.13',
  ownershipFlags: 0,
  ownershipTicketGenerated: 2018-02-02T14:38:16.000Z,
  ownershipTicketExpires: 2018-02-23T14:38:16.000Z,
  licenses: [ 1475Z8 ],
  dlc: [],
  signature: <Buffer c3 a6 ac d1 52 Xe 8c 9c da ea bb 7f b8 9c c8 ac 80 c4 30 32 d5 bc e4 68 fc b0 61 8f 76 de 98 5b 2e ce c4 82 35 21 e9 29 c6 9f fb a4 81 a3 76 66 7d 04 ... >,
  isExpired: false,
  hasValidSignature: true,
  isValid: true }

```
do you know how to transform that ticket intto pubg auth ticket?

**Comment by DoctorMcKay** [comment]
Don't parse it. What you get back from `getAuthSessionTicket` is what you want.

**Comment by myserywork** [comment]
i was specting the token But it comes showing me a buffer with only 100 chars 

14 00 00 00 36 ce 04 10 fa c8 78 64 df 68 9d 19 01 00 10 01 b0 79 74 5a 18 00 00 00 01 00 00 00 02 00 00 00 aH 61 cd b1 00 00 00 00 26 00 00 00 01 00

using code `client.on("loggedOn", function (dataAndEvents) {
    console.log("[BOT] Signed in!");
			client.getAuthSessionTicket(578080, function(err,ticket){
			let parsed = SteamUser.parseAppTicket(ticket);
			console.log(parsed);
			


		
		fs.appendFileSync('rpc.txt', ticket.toString('utf8') + '\r\n');
			console.log(ticket);
		});
});
`

and the token is likely  468
,

14000000AA709D6426279EE4DF689D1901001001DBEF735A180000000100000002000000A961CDB14E0FA8C0288A2C0021000000B20000003200000004000000DF689D190100100120D20800A961CDB14E0FA8C000000000D2DF735A528F8F5A0100844002000000000090A62D0F6CDB2A5F4E54A765AAD6D477A384ECF2DAF14CC7FA13A7E925FC7999FB53990D7AC185A77793C559481A674FCBF98774A9F723590940032FA61CB3CC6C19E931D55A19ADB0CEE94DBDF6104BC9FE5F97F8BBDA968F2E2FAD52C305B250DD8E6E3C8C317E960996F1F1AEBA774D602C14E5CE4989F30AB231D5B54355

**Comment by DoctorMcKay** [comment]
toString('hex'), just as in your example above.
