### ISSUE TITLE
Best way to getting Packages Activated Date

### ISSUE THREAD

**Issue by tldrjumps** [DoctorMcKay/node-steam-user#161]
For example, how to get Date of Activation and the Game
https://store.steampowered.com/account/licenses/

I should use 
1) getOwnedGames from WebAPI and retrieve the APP's Package Id and compare with licenses object returned from Licenses?
2) getProductInfo/getOwnedAppsProductInfo with Package in conjunction also with Licenses?

Both way have to have few request to get the job done? Which method have lesser impact on network footprint so that is faster to complete? getOwnedAppsProductInfo seem to be too heavy on the response

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

Assuming you're talking about getting the date when you acquired an app, then you should check the licenses object dates.
