### ISSUE TITLE
gamesPlayed doesn't support Video App types?

### ISSUE THREAD

**Issue by FexileTV** [DoctorMcKay/node-steam-user#164]
It seems that node-steam-user doesn't work with steam Apps that are videos,
Example:
https://steamdb.info/app/635240/

when I use gamesPlayed and this AppID nothing happens, While it should say "in-game Making of Furi: Episode 1 - Conception"

**Comment by DoctorMcKay** [comment]
It's free-on-demand. You need to [get a license](https://github.com/DoctorMcKay/node-steam-user#requestfreelicenseappids-callback) first.
