### ISSUE TITLE
Format of inviteToGroup() is unclear

### ISSUE THREAD

**Issue by Apatetic** [DoctorMcKay/node-steam-user#169]
I tried using client.inviteToGroup() function but I don't know whether to use the 64-bit or 8-bit clan ID, please clarify. Thanks.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

What's an 8-bit clan ID? You mean a 32-bit id?

Either a 64-bit SteamID or a 32-bit id will work, as long as you format the 32-bit id as a Steam3 ID: `[g:1:4]` where 4 is the ID.
