### ISSUE TITLE
Steam-User + Mongoose

### ISSUE THREAD

**Issue by layane** [DoctorMcKay/node-steam-user#17]
I have a problem I update to Node 4.2.2 (TSL),  Steam-User and Mongoose. I'm storing my Sentry file as a Buffer in my mongodb with mongoose. I store successful with mongoose but when i read from mongo crash in the module bytebuffer.

The crash log: https://gist.github.com/layane/0e0224a5ebcdf866b94f

Edit: 
- My Mongo transport layer: https://gist.github.com/layane/49517adcda15114ee051
- Bot model: https://gist.github.com/layane/20ea8e2a8eb7baff9d37

Before upgrade the code run ok.

I tried to fix:
 - Updating bytebuffer to 5.0 and protobufjs 4.1.3.
- I checked that in mongo stored OK as a $binary buffer (db store as "sentry" : { "$binary": "string", "$type" : "00" } )
- I read the nodejs changelogs and the nodejs' guys did lot of changes.

SOLVED: Converting the binary buffer into base64 when write, and reconverting into base64 buffer when read. its ok. Seems the binary type don't support in the new versions of protobuff or bytebuffer.

- To read: new Buffer(data.toString('base64'), 'base64')
- To write: new Buffer(contents.toString('base64'), 'base64')

I dont close the thread because it's ugly my solution. Any other solution more cleaner?

Thanks in advance. Great job McKay

**Comment by DoctorMcKay** [comment]
I don't know anything about mongo+mongoose when used with node. The issue seems to lie in the code between when `steam-user` requests to save/read sentry.bin and storage/reading to/from the database, so I'm closing this.
