### ISSUE TITLE
The application consumes a lot of RAM

### ISSUE THREAD

**Issue by T1MOXA** [DoctorMcKay/node-steam-user#179]
The application consumes a lot of RAM.
My application uses 4 Steam users.
After starting ~140MB - 180MB.
What consumes so much memory ?

**Comment by Royalgamer06** [comment]
Something like https://github.com/DoctorMcKay/node-steam-user/issues/188 may solve this issue.

**Comment by LW2904** [comment]
Using NodeJS and requiring low RAM usage don't usually go well with each other.

In any case, the little script I have running on my server controls three Steam accounts (and even has a small webserver running) usually doesn't go above 50 MB of RAM usage; what makes you certain it's node-steam-user that's the issue?

**Comment by ekifox** [comment]
@Royalgamer06 Are you really sure that caching a couple of objects in memory will take more than a couple of megabytes?

**Comment by DoctorMcKay** [comment]
v4.4.4 should fix most memory issues.
