### ISSUE TITLE
getPersonas not updating...

### ISSUE THREAD

**Issue by dalexhd** [DoctorMcKay/node-steam-user#181]
It seems that this function response is not updated on every call. Is there any fix?
(State updates correctly, but game_played_app_id does not update in some friends).

**Comment by DoctorMcKay** [comment]
No, it comes straight from Steam so if Steam is reporting old data there's nothing we can do.

**Comment by dalexhd** [comment]
Resolved. If clients has blocked the bot the data will not update.
