### ISSUE TITLE
Add downloadGame(appid, branch, language, inclDLC[, callback]) to cdn.js

### ISSUE THREAD

**Issue by Royalgamer06** [DoctorMcKay/node-steam-user#183]
Like SteamCMD, we'll be able to directly download games. You've laid the ground work already in cdn.js, now it would be great to see it come together in this function!

**Comment by DoctorMcKay** [comment]
In my opinion, that's a job for a separate application (like how DepotDownloader is separate from SteamKit).

**Comment by Royalgamer06** [comment]
What are you talking about?
`Steam depot downloader utilizing the SteamKit2 library.` https://github.com/SteamRE/DepotDownloader

Sadly nobody made depot downloading tools for node.js, except partially for your cdn.js.
I've been trying to code functions with cdn.js, but it has quite some issues.
It would be great, if you would take a look at it, improve it and add more depot downloading functions, like downloadApp.

This will make using SteamCMD in nodejs applications obsolete (e.g. https://github.com/meyerbw-zz/SteamMusicLibraryExporter)

**Comment by Royalgamer06** [comment]
https://dev.doctormckay.com/topic/1066-download-manifest-files/

**Comment by DoctorMcKay** [comment]
Downloading entire depots is out of scope. This is a library, not an end-user application.
