### ISSUE TITLE
How to get the clients avatar url?

### ISSUE THREAD

**Issue by KyeNormanGill** [DoctorMcKay/node-steam-user#185]
Not an issue but I've been looking all through docs but i can't seem to find where to get the logged in clients avatar url.
I know how to get a users avatar url from the users cache but not the current user.
Please help!

**Comment by DoctorMcKay** [comment]
You get your own avatar through the users cache, same way as anyone else. You may need to request it with `getPersonas` first.

**Comment by KyeNormanGill** [comment]
Thanks! Sorry about that.
