### ISSUE TITLE
Custom cache engine for picsCache

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#188]
Like the [custom storage engine](https://github.com/DoctorMcKay/node-steam-user#custom-storage-engine) for cached files, allow us to customize the way `picsCache` gets stored. Perhaps we maintain our own (big) database of product infos and we don't want to store it all to memory in the `picsCache` property. Or we ignore it with the potential of duplicated memory, which is terribly inefficient.

For example:
```
user.picsCache.on('updateApp', function(appid, appinfo, callback) {
	someStorageSystem.saveFile(appid + ".json", JSON.stringify(appinfo), function(err) {
		callback(err);
	});
});

user.picsCache.on('readApp', function(appid, callback) {
	someStorageSystem.readFile(appid + ".json", function(err, contents) {
		if(err) {
			callback(err);
			return;
		}

		callback(null, JSON.parse(contents));
	});
});
```

**Comment by DoctorMcKay** [comment]
Unfortunately, I don't think this can be done in a backwards-compatible way. Current architecture requires the PICS cache to be accessible synchronously, and I'm not willing to give end-users the option to synchronously persist data to disk.

**Comment by Revadike** [comment]
Hmm, how about allowing us to choose the storage location and filename instead?

**Comment by DoctorMcKay** [comment]
That still isn't really going to work since any synchronous disk access is going to be blocking, resulting in potentially pretty bad performance.

**Comment by Revadike** [comment]
Wait, but don't you do that already? You cache them in appdata doctormckay folder, right?

**Comment by DoctorMcKay** [comment]
No, the PICS cache is entirely in-memory.

**Comment by Revadike** [comment]
> * Depot decryption keys

ah yes, this is what I remember.
