### ISSUE TITLE
steamGuard event not working as expected.

### ISSUE THREAD

**Issue by dalexhd** [DoctorMcKay/node-steam-user#189]
Currently I'm using this to handle posible disconnects:
```javascript
var steamUser = new SteamUser(steamClient);
steamUser.setOption("promptSteamGuardCode", false);
steamUser.setOption("debug", true);
// ....
steamUser.on("steamGuard", function(domain, callback, lastCodeWrong) {
    console.log("Steam Guard code needed from mobile (main bot)");
    if(lastCodeWrong) {
        console.log("Last code wrong, try again!");
        setTimeout(function() {
            console.log(SteamTotp.getAuthCode("shared_secret"));                      
            callback(SteamTotp.getAuthCode("shared_secret"));
        }, 30000);
    }	
});
```
I don't know what am i doing wrong... The event callback is being fired like 10 times in 1 sec, returning the RateLimitExceeded error.
I also checked the timeOffset which returns 0, so there is nothing to change.

**Comment by DoctorMcKay** [comment]
I don't see any reason why that callback would be called multiple times in that code.

**Comment by dalexhd** [comment]
Doesn't matter, I was doing this because steam servers were not updated, and I was connecting to shit servers... Now, every 24 hours, by bot restarts, and download the new server list onto the node-steam module. :blush:

**Comment by DoctorMcKay** [comment]
Unless you're somehow calling `logOn` multiple times (and even then I don't think that would work), what you describe couldn't be happening.
