### ISSUE TITLE
Not able to run non-steam game

### ISSUE THREAD

**Issue by denis-marecky** [DoctorMcKay/node-steam-user#19]
in description "To play a single non-Steam game by name, use a single string (e.g. "Minecraft")"
I try a lot of ways, but always get an error with Illegal value or nothing has changed. Does it works?

**Comment by DoctorMcKay** [comment]
It works fine for me. ![](https://mckay.media/dhgMw)

What's the error you're getting?

**Comment by denis-marecky** [comment]
throw Error("Illegal value for "+this.toString(true)+" of type "+this.type.name+": "+val+" ("+msg+")");
                ^

Error: Illegal value for [object Object] of type message: string (object expected)
    at Error (native)

**Comment by DoctorMcKay** [comment]
Are you sure you're using node-steam-user?

**Comment by denis-marecky** [comment]
sorry, I use just node-steam instead of this module. What is this module? Better version of node-steam user handler?

**Comment by DoctorMcKay** [comment]
>Better version of node-steam user handler?

Yes.
