### ISSUE TITLE
gamesPlayed and setPersona are not work

### ISSUE THREAD

**Issue by ekifox** [DoctorMcKay/node-steam-user#190]
Like #157
Forum: https://dev.doctormckay.com/topic/1833-did-clientgamesplayed-change/

```javascript
const SteamUser = require('steam-user')
const steamUser = new SteamUser()

steamUser.logOn({
    account_name: '123',
    password: '123'
})

steamUser.on('loggedOn', details => {
    steamUser.setPersona(SteamUser.EPersonaState.Online)
    steamUser.gamesPlayed(440)
})
```

This simple code does not work at all. The bot is authorized and details are full of information. But my profile is labeled as "not online" and TF2 does not appear in the games played.
All privacy settings are set to open.

**Comment by DoctorMcKay** [comment]
![](https://mckay.media/dpNZN.png)

![](https://mckay.media/YZB4e.png)

Double-check your privacy settings.

**Comment by DoctorMcKay** [comment]
`accountName`, not `account_name`.

**Comment by AndreasHassing** [comment]
I had a similar issue, but for me I was using `user.setPersona("Online")` when I should have used either [`SteamUser.EPersonaState.Online` or `1`](https://github.com/DoctorMcKay/node-steam-user/blob/b33da1c8d8a301620582966e6b87c3d1a727cb4a/enums/EPersonaState.js#L6).
