### ISSUE TITLE
How do I return Steam64 ID after 'loggedOn'?

### ISSUE THREAD

**Issue by nodeidlesoffline** [DoctorMcKay/node-steam-user#192]
On another API I was able to just call `steamClient.steamID` which returned the full Steam64 ID.

This doesn't work on this API.

I can't see any specific function. I saw I can get the 'universe' id but I need to return the Steam64 one specifically

Thanks

**Comment by DoctorMcKay** [comment]
`user.steamID.getSteamID64()`
