### ISSUE TITLE
changePassword not deprecated

### ISSUE THREAD

**Issue by Xanazzz** [DoctorMcKay/node-steam-user#193]
Hey, I would like to ask why is **changePassword** marked as deprecated and not working, even though it does still work fine?

**Comment by Xanazzz** [comment]
It explicitly states that the method does not work in the readme that is why i'm confused.

**Comment by DoctorMcKay** [comment]
Confirmed that it no longer works:

```
changing password
Sending message: ClientPasswordChange3
Handled message: Multi
Processing multi msg
Handled message: ClientLoggedOff
Logged off: InvalidProtocolVer
SU handled error: InvalidProtocolVer
```

Maybe it works now, but with the protocol version bump that's coming with v4 it definitely won't work anymore, so it's being removed in v4.

A module to automate the help site (which is where password changing happens now) might be appropriate.
