### ISSUE TITLE
add applicense to the steam account

### ISSUE THREAD

**Issue by idontneedhelp** [DoctorMcKay/node-steam-user#197]
So i want to add a game to the steamaccount (free game) i got another bot which needs to start the game and he cant(obviusly when the game never was started before.)
My idea was to try it with:  client.requestFreeLicense
but i get no respone.
My whole code:
 client.requestFreeLicense([303386], function(error, grantedPackages, grantedAppIDs) {
        if (error) {
            console.log(error)
        } else {
            if (grantedPackages.length === 0) {
                console.log("No packages");
        }
        }
         if (grantedAppIDs.length === 0) {
                console.log("nope nothing was added");
            } 
});
thanks for your help<3

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

303386 is not a valid AppID.
