### ISSUE TITLE
[Question] Multiple bots running on single machine

### ISSUE THREAD

**Issue by EduardChernikh** [DoctorMcKay/node-steam-user#198]
Hey. Can you please tell me if you know any limitations about running multiple instances on the same machine? I need to run something like 50-200 bots for current project. Should i split them for a few machines or it's okay to run them on one powerful machine?

**Comment by titoncio** [comment]
You can get Rate Limit, but this is on Steam Side.
If you code right way theres no problem to run in 1 machine, i ran about 30 in a Raspberry Pi 3

**Comment by EduardChernikh** [comment]
Well, that's what i was looking for if i just can run ~25 bots on one machine. Thanks
