### ISSUE TITLE
node-steam-user instantly disconnects when under electron environment

### ISSUE THREAD

**Issue by busheezy** [DoctorMcKay/node-steam-user#199]
Hello, I'm having an issue when using this library under electron's render process. This might be out of scope but it might be a quick fix to make it work on electron.

I have made a quick reproduction repository.
https://github.com/busheezy/electron-node-steam-user

https://i.imgur.com/6UbEYvV.png

From the image you can see I'm getting an error for just "Disconnected."

```
Error: Disconnected
    at SteamUser._handleLogOff (C:\Users\ryan9\Desktop\steam-test\node_modules\steam-user\components\logon.js:400)
    at CMClient.<anonymous> (C:\Users\ryan9\Desktop\steam-test\node_modules\steam-user\index.js:124)
    at CMClient.emit (events.js:182)
    at CMClient._disconnected (C:\Users\ryan9\Desktop\steam-test\node_modules\steam-client\lib\cm_client.js:345)
    at TCPConnection.emit (events.js:182)
    at Socket.<anonymous> (C:\Users\ryan9\Desktop\steam-test\node_modules\steam-client\lib\tcp_connection.js:105)
    at Socket.emit (events.js:182)
    at TCP._handle.close [as _onclose] (net.js:596)
```

Thanks for all of your work.

**Comment by DoctorMcKay** [comment]
Are you using the latest Electron version? Maybe there's some problem in your version of Electron. `steam-user` uses Node's standard TCP stack so I don't think there would be any issue there.

**Comment by busheezy** [comment]
Thanks for the quick reply. I am using the latest electron version on my actual app. I noticed the example repo that I linked you was using an older version but I have updated it now. Both have the same error. Looking through your source, I didn't see anything wild but it's too large for be to go through completely at the moment. I have noticed that there is a difference between the render process's timers and node's. "unref" was causing an error with your stats collector if I don't opt out of that but I wonder if something else timer related is wonky.

**Comment by DoctorMcKay** [comment]
Could you try the [v4 branch](https://github.com/DoctorMcKay/node-steam-user/pull/165)? You'll need to make adjustments to your code based on the breaking changes.

**Comment by busheezy** [comment]
It doesn't seem to disconnect instantly while on v4. The electron debug event seems to have a lot more content than a regular node environment. https://i.imgur.com/uze0zAE.png It crashes after a few minutes of running. I have updated the test repo in the original post to match what I'm running.

**Comment by DoctorMcKay** [comment]
Your TCP connection is being reset somehow. This is not steam-user's fault, though I don't know where to suggest you start looking.

**Comment by busheezy** [comment]
Well thanks for all of the quick replies. I suppose I can just use your steamcommunity module for now. I was wanting to use the sentry file management that you provide with node-steam-user but I'll work something out with the steamcommunity package. I have no idea where to look for my node-steam-user problem. My few google searches came up empty.

**Comment by DoctorMcKay** [comment]
If it helps you any, it seems like your problem is that some of your TCP connections under Electron are getting reset.

**Comment by busheezy** [comment]
```js
const WS13 = require('websocket13');

const socket = new WS13.WebSocket('ws://demos.kaazing.com/echo');

socket.on('connected', info => {
  console.log(
    'Successfully connected to echo server with HTTP version %s, HTTP status code %d, and HTTP status text %s. Headers follow.',
    info.httpVersion,
    info.responseCode,
    info.responseText,
  );
  console.log(info.headers);

  socket.send('This is a string message.');

  setInterval(() => {
    socket.send(new Date().toString());
  }, 5000);
});

socket.on('message', (type, data) => {
  switch (type) {
    case WS13.FrameType.Data.Text:
      console.log('Received text: %s', data);
      break;

    default:
      console.log('defaulted');
  }
});

socket.on('disconnected', (code, reason, initiatedByUs) => {
  console.log(
    "Disconnected from echo server with code %d and reason string '%s'. Disconnection %s initiated by us.",
    code,
    reason,
    initiatedByUs ? 'was' : 'was NOT',
  );
});

socket.on('error', err => {
  console.log('Fatal error: %s', err.message);
});
```
I was playing around with a test script on an echo server. I haven't had any disconnections. I'll have to play around with seeing if I can get a basic setup to steam with some bare bone sample code.

**Comment by MitchDizzle** [comment]
Just adding my "it works on my machine" comment. I use node-steam-user in my chat logger application that uses electron to create a tray icon and setting window etc. I even package it into it's own executable/installer just fine. If you're still having issues with electron.
Also curious if your issue has anything to do with the steam-user being started within the render script.
ChatLogger github source: https://github.com/MitchDizzle/ChatLogger.JS

**Comment by DoctorMcKay** [comment]
v4 has come out since this was opened, which was a pretty major update. I'm going to close this, but if you're still having the issue please let me know and I'll reopen.
