### ISSUE TITLE
Finalize 2FA not working

### ISSUE THREAD

**Issue by TrueCarry** [DoctorMcKay/node-steam-user#20]
This function not worked for me by default. I changed deprecated
`var code = SteamUser.generateAuthCode(secret, diff);`
to 
`var code = SteamTotp.generateAuthCode(secret);`
and steam accepted my finalization.

**Comment by DoctorMcKay** [comment]
What version were you using? The latest version uses `SteamTotp.generateAuthCode` instead of `SteamUser.generateAuthCode`, but both should work the same regardless...

**Comment by TrueCarry** [comment]
Apparently 2.0.0. NPM verison outdated, check https://registry.npmjs.org/steam-user/-/steam-user-2.0.0.tgz

**Comment by DoctorMcKay** [comment]
The npm version isn't outdated, I just haven't deployed those changes yet. I was mistaken in my previous comment.

Regardless, the method in SteamTotp was directly pulled from here so there's no reason why it wouldn't work on 2.0.0.

**Comment by TrueCarry** [comment]
I don't know why it didn't work for me either, but steam responded with 88 error. Maybe wrong `diff`

**Comment by DoctorMcKay** [comment]
Well, I'll close this since apparently it works with SteamTotp and I should be deploying that soon.
