### ISSUE TITLE
client_supplied_steamid is no loger returned before login

### ISSUE THREAD

**Issue by fcastrocs** [DoctorMcKay/node-steam-user#202]
{ eresult: 63,
  out_of_game_heartbeat_seconds: null,
  in_game_heartbeat_seconds: null,
  public_ip: null,
  rtime32_server_time: null,
  account_flags: null,
  cell_id: null,
  email_domain: 'yahoo.com',
  steam2_ticket: null,
  eresult_extended: 63,
  webapi_authenticate_user_nonce: null,
  cell_id_ping_threshold: null,
  use_pics: null,
  vanity_url: null,
  **client_supplied_steamid: null,**
  ip_country_code: null,
  parental_settings: null,
  parental_setting_signature: null,
  count_loginfailures_to_migrate: 0,
  count_disconnects_to_migrate: 0,
  ogs_data_report_time_window: null,
  client_instance_id: null,
  force_client_update_check: null }
Steam Guard Code:

**Comment by DoctorMcKay** [comment]
All that data comes from Steam. I have no control over it.
