### ISSUE TITLE
EPersonaState.Invisible not behaving as same feature from the UI

### ISSUE THREAD

**Issue by gekkedev** [DoctorMcKay/node-steam-user#209]
This line is a bit confusing:
https://github.com/DoctorMcKay/node-steam-user/blob/83ad7295d17798ea5534699267bb9422b59eefe7/enums/EPersonaState.js#L23
The `Invisible` state seems to have no effect for me, or it does something else that I haven't noticed. Trying it with `Max` did the trick though!
Whatever the value 7 does, 8 is the one that actually turned the client invisible. Is it meant to be like that? If not, would it be possible to change something here, e.g. swapping these values or renaming them to be more self-explanatory?

**Comment by gekkedev** [comment]
Apologies, didnt't have the bugfix from 3.28..

**Comment by DoctorMcKay** [comment]
:+1: Glad you got it working!
