### ISSUE TITLE
Unable to return Product Name via GetProductInfo

### ISSUE THREAD

**Issue by helloitsm3** [DoctorMcKay/node-steam-user#210]
I've tried getting all the apps name that I owned but it keeps giving me "cannot read property "5" of undefined" when the ID of the app is 5. 

```
 let gameArr = client.getOwnedApps();

    client.getProductInfo(
      gameArr,
      [],
      (apps, packages, unknownApps, unknownPackages) => {
        for (var appid in packages) {
          console.log(appid);
        }
        console.log(packages[5].appinfo.common.name);
      }
    );
```

**Comment by DoctorMcKay** [comment]
App data is in `apps`, not in `packages`.

**Comment by helloitsm3** [comment]
I tried accessing app but it returns null

**Comment by helloitsm3** [comment]
Yeah it doesn't but that's what it's returning on my side. I'll try again and let you know the result
