### ISSUE TITLE
EPersonaState

### ISSUE THREAD

**Issue by DatColdCat** [DoctorMcKay/node-steam-user#214]
Every time that I run this code - 
*
const SteamUser = require('steam-user');
const config = require('./config.json');
const client = new SteamUser();

const logOnOptions = {
  accountName: config.username,
  password: config.password
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
  console.log('Logged into Steam');

  client.setPersona(SteamUser.Steam.EPersonaState.Online);
  client.gamesPlayed(440);
});
* 

I get an error message saying - 
*
  client.setPersona(SteamUser.Steam.EPersonaState.Online);
                                    ^

TypeError: Cannot read property 'EPersonaState' of undefined
*

**Comment by Billason** [comment]
dat error

**Comment by DoctorMcKay** [comment]
[v4](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.0.0) came with many breaking changes. Please read the release notes and familiarize yourself with what changed.

In your specific case, you need to replace `SteamUser.Steam.EPersonaState` with `SteamUser.EPersonaState`.

**Comment by Billason** [comment]
thank u

**Comment by kartikchandra14** [comment]
Try this:-
client.setPersona(SteamUser.EPersonaState.Online);

Instead Of:-
client.setPersona(SteamUser.Steam.EPersonaState.Online);
