### ISSUE TITLE
enableTwoFactor documentation is wrong

### ISSUE THREAD

**Issue by Mr-KoKa** [DoctorMcKay/node-steam-user#217]
In readme there is
https://github.com/DoctorMcKay/node-steam-user#enabletwofactorcallback
It states that callback will receive err and response
But in fact callback receives only response

**Comment by DoctorMcKay** [comment]
The documentation is for [v4](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.0.0) which does, in fact, receive an err argument.
