### ISSUE TITLE
Rich presence problem.

### ISSUE THREAD

**Issue by dalexhd** [DoctorMcKay/node-steam-user#220]
It seems that rich presence data portion is only available when a presence change has been made (For example he changed from CSGO deadmatch to danger zone). How can I get rich presence when a user property has been changed (of course, that user is playing csgo).

**Comment by TAKKEN666** [comment]
Wait for @DoctorMcKay fix that bug

**Comment by DoctorMcKay** [comment]
Please give 4.4.1 a try.

**Comment by dalexhd** [comment]
@DoctorMcKay It seems to be working now! ^^
