### ISSUE TITLE
How can to send a request to the GC?

### ISSUE THREAD

**Issue by dalexhd** [DoctorMcKay/node-steam-user#224]
How can I send a request to the CSGO game coordinator?
For example, I need to get a user rank.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

You can use [node-globaloffensive](https://github.com/DoctorMcKay/node-globaloffensive).
