### ISSUE TITLE
event.game_id.toNumber is not a function

### ISSUE THREAD

**Issue by chudakM** [DoctorMcKay/node-steam-user#225]
getting this error under angular + electron development

error in friends.js:765

**Comment by DoctorMcKay** [comment]
Do you have a way to reproduce this?

**Comment by chudakM** [comment]
yesterday changed toNumber() to Number() on friend.js:765
was
` user.gameid = user.gameid.toNumber();`
now 
`Number(user.gameid)`
today got one more event.game_id.toNumber is not a function now on friends.js:618 
also found toNumber in twofactor.js:70
mb problem is that js dont have function called toNumber?
can you add me on steam or somewhere else so i can tell you the way how to reproduce the error?

**Comment by tabam1** [comment]
I run with npm forever

**Comment by DoctorMcKay** [comment]
This *should* be fixed in v4.3.1, but I have absolutely no idea why it would have been happening. You'll probably see `gameid` as some sort of object instead where it would normally crash. Please let me know if you do.
