### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by TAKKEN666** [DoctorMcKay/node-steam-user#226]
How to fix that?
Im creating a steam Chat idling bot

twoFactorCode: SteamTotp.generateAuthCode(config.sharedSecret)
        ^^^^^^^^^^^^^

SyntaxError: Unexpected identifier

thats my .js

const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp')
const config = require('./config.json');
const client = new SteamUser ();

const logOnOptions = {
	accountName: config.username,
	password: config.password
	twoFactorCode: SteamTotp.generateAuthCode(config.sharedSecret)
};

client.logOn(logOnOptions);

	console.log('succesfully logged on.');
client.on('loggedOn', () => {
	client.setPersona(SteamUser.EPersonaState);
	client.gamesPlayed(["Custom Game",730]);
});

client.on("friendMessage", function(steamID, message) {
	if (message == "hi") {
		client.chatMessage(steamID, "hello");
	}
});

**Comment by chudakM** [comment]
you missed comma after config.password

**Comment by TAKKEN666** [comment]
> you missed comma after config.password

thanks ;)
