### ISSUE TITLE
Unexpected token a in JSON at position 4

### ISSUE THREAD

**Issue by TAKKEN666** [DoctorMcKay/node-steam-user#227]
thats error when i run the project
SyntaxError: C:\Users\Tanjil\Desktop\steambot\config.json: Unexpected token } in JSON at position 66
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Tanjil\Desktop\steambot\bot.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

thats my project
const SteamUser = require('steam-user');
const config = require('./config.json');
const client = new SteamUser();

const logOnOptions = {
	accountName: config.username,
	password: config.password	

};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
	console.log('succesfully logged on.');

**Comment by chudakM** [comment]
without your config.js its hard to say smth

**Comment by TAKKEN666** [comment]
> without your config.js its hard to say smth
thats my config.json
{
	accountName: ***********
	password: ***********
}

obviusly i dont show the letters on this discussion but i writed on config (sry for my bad english)

**Comment by TAKKEN666** [comment]
> without your config.js its hard to say smth

and now is that error Unexpected token a in JSON at position 4

**Comment by chudakM** [comment]
{
  "accountName": "1",
  "password": "2"
}
replace 1 and 2 with your account name and password

**Comment by TAKKEN666** [comment]
> { 
> "accountName": "1", 
> "password": "2" 
> } 
> substitua 1 e 2 pelo nome da sua conta e senha
> 
> Parece que você mais uma vez perdeu vírgula e não envolveu chaves e valores em "
i replaced 1 and 2 but the error its the same


so i writed
 {
	"username":"tanjil_08072005",
	"password":"tanjil08072005",
}
and when i run the error is again :  Unexpected token } in JSON at position 66

**Comment by chudakM** [comment]
{
"username":"tanjil_08072005",
"password":"tanjil08072005",
}
should be
{
"username":"tanjil_08072005",
"password":"tanjil08072005"
}

**Comment by chudakM** [comment]
btw your issues not even connected with steam-user so try to google first please

**Comment by TAKKEN666** [comment]
> btw your issues not even connected with steam-user so try to google first please

thanks thats worked

**Comment by 8fn** [comment]
> { "username":"tanjil_08072005", "password":"tanjil08072005", } should be { "username":"tanjil_08072005", "password":"tanjil08072005" }

how the hell u discover my old credentials 😭
