### ISSUE TITLE
Add a way to provide custom token values for appid at rich presence.

### ISSUE THREAD

**Issue by dalexhd** [DoctorMcKay/node-steam-user#229]

**Comment by DoctorMcKay** [comment]
I have no idea what this means.

**Comment by dalexhd** [comment]
I want to customize the rich presence tokens value. For example, instead of "playing casual game at cobblestone", "playing casual at cobble"

**Comment by DoctorMcKay** [comment]
In your use-case, I would suggest that you [download the rich presence localizations](https://github.com/DoctorMcKay/node-steam-user#getapprichpresencelocalizationappid-language-callback) and implement your own decoder if you want to modify the text in that way.

**Comment by dalexhd** [comment]
> In your use-case, I would suggest that you [download the rich presence localizations](https://github.com/DoctorMcKay/node-steam-user#getapprichpresencelocalizationappid-language-callback) and implement your own decoder if you want to modify the text in that way.

What do you meant with my own decoder?

**Comment by DoctorMcKay** [comment]
Your own code to turn the stuff in `rich_presence` in the `user` event into the string you want.

**Comment by dalexhd** [comment]
> Your own code to turn the stuff in `rich_presence` in the `user` event into the string you want.

Maybe... i will try later...
