### ISSUE TITLE
my bot stops listening user events after some hours...

### ISSUE THREAD

**Issue by dalexhd** [DoctorMcKay/node-steam-user#237]
It seems that my bot stops listening user events after some hours... How can I handle those type of things...
Do I need to send random user requests every x time to keepalive my bot user events handler...?

**Comment by DoctorMcKay** [comment]
Maybe your bot got disconnected from Steam? The `error` event would get emitted in that case.

**Comment by Revadike** [comment]
Probably related to the problem more of us are facing. @dalexhd you're on v4 too?

**Comment by dalexhd** [comment]
Yep

**Comment by MitchDizzle** [comment]
...have you tried reconnecting after you get disconnected?

**Comment by dalexhd** [comment]
Even if I have autoRelogin enabled?

**Comment by MitchDizzle** [comment]
From the doc: https://github.com/DoctorMcKay/node-steam-user#error
It suggests that if the error event happens it's a fatal error and the autoRelogin feature doesn't happen when it's a fatal error.

**Comment by dalexhd** [comment]
```js
[06-03-2019 00:52:58.834] [Steam] Disconnected from steam: [eresult: 3] NoConnection
[06-03-2019 00:53:59.685] [Ts3] TS3 stuff.
[06-03-2019 00:54:16.416] DB stuff.
[06-03-2019 01:01:46.939] [Ts3] TS3 stuff.
[06-03-2019 01:01:47.837] [Ts3] TS3 stuff.
```
As you can see no errors are being emitted...

This is my part of code:
```js
steamUser.on('error', function(err) {
    log.error("Logon error: " +err, "steam");
});
steamUser.on('disconnected', function(eresult, msg) {
    log.error("Disconnected from steam: [eresult: " + eresult + "] " + msg, "steam");
});
```

**Comment by MitchDizzle** [comment]
Well from the docs it seems 'disconnected' *only* fires when the client lost connection and it's relogging in.
https://github.com/DoctorMcKay/node-steam-user#disconnected
> Emitted when we're disconnected from Steam for a non-fatal reason and autoRelogin is enabled.

**Comment by dalexhd** [comment]
@MitchDizzle I also have that event added into my code. But seems that there are not logs telling me that its loggedOn again.

**Comment by MitchDizzle** [comment]
Oh my bad, apperently the steam-user docs do not mention the fact that NoConnection (EResult:3) does not relogin. Which is the same error you're getting.
https://github.com/DoctorMcKay/node-steam-user/blob/master/components/logon.js#L464

**Comment by dalexhd** [comment]
Let's wait @DoctorMcKay to answer this...

**Comment by MitchDizzle** [comment]
I don't think this is an issue McKay should have to answer. I've looked at your ts-steam code and most of it makes no sense. I've had my steam-user app on for over a week now and haven't had issues with it not reconnecting or erroring out, not saying this as a "works on my machine".
You're using an EventListener but treating it as a Promise (don't know exactly how to describe it) Why does your code need to use async? You've created a bot and separated it into a ton of files for which could have been made into a single file perhaps more since you do have a webpanel.

**Comment by dalexhd** [comment]
That is not the project issue, it's just a project that I forked or starred. Nevermind, I have been running my bot for 2 days without errors... So let's wait a week and I will tell here how it goes...
Pd: I also think that it's a bad code... That is why I started my own teamspeak and steam bot. Much better of course, as it has live status on teamspeak... Xd. That is only my opinion...

**Comment by dalexhd** [comment]
Okay... Today it stopped working again. As I can see on the logs, it stopped with eresult 20, and it reconnected "successfully" again... For some reason, 1 min after stopped again with same eresult, but after that, it doesn't reconnect it again. Also, seems that user events are not even fired on that "connected period"... I think that I will basically kill process when disconnect event happens...

**Comment by MitchDizzle** [comment]
Mind showing your repo/code for managing the SteamUser EventEmitter? Maybe it'll show some light on the matter.

**Comment by dalexhd** [comment]
I've updated all my code to promises instead of shit async unnecessary code parts...
Now seems to be working, at leat 2 days without disconnecting. Let's wait until Friday before closing this "issue"

**Comment by dalexhd** [comment]
Okay... It has been working 4 days, nice!
Today stopped with eresult 3, and didn't try even to reconnect... What do u recommend to do? Restart the process on error?

**Comment by Revadike** [comment]
but rewriting all callbacks to promises doesn't really solve the problem. It's aimed to support both.

**Comment by dalexhd** [comment]
For some reason it has been alive much more time than before... Take a look at steam-ts github repository lib/launch.js file, and tell me if that cloud be the reason...

**Comment by dalexhd** [comment]
This is my current code:
```javascript
try {
    var config = JSON.parse(fs.readFileSync(path.join(__dirname, "../", "config", "config.json")));
} catch (err) {
    console.log("Could not read config.json: " + err);
    process.exit();
}

var initialize = function () {
    return new Promise(function (resolve, reject) {
        var community = new SteamCommunity();
        var steamUser = new SteamUser({
            language: 'spanish'
        });
        steamUser.setOption("promptSteamGuardCode", false);
        steamUser.setOption("debug", true);
        steamUser.setOption("autoRelogin", true);

        steamUser.logOn({
            accountName: config.steam.main_account.username,
            password: config.steam.main_account.password,
            twoFactorCode: SteamTotp.getAuthCode(config.steam.main_account.shared_secret)
        });
        
        steamUser.once('loggedOn', function () {
            log.success("logged in", "steam");
            steamUser.setPersona(2, config.steam.main_account.bot_name);
            steamUser.webLogOn();
            steamUser.once('webSession', function(sessionID, cookies) {
                log.success("Got web session", "steam");
                community.setCookies(cookies);
            });
            
            steamUser.on('error', function(err) {
                console.log(err);
                log.error("Logon error: " +err, "steam");
            });
            steamUser.on('disconnected', function(eresult, msg) {
                log.error("Disconnected from steam: [eresult: " + eresult + "] " + msg, "steam");
            });

            var csgo = new GlobalOffensive(steamUser);
            csgo.on('connectedToGC', function () {
                log.success("Connected to GC", "csgo");
            })
            steamUser.gamesPlayed([730]); 

            resolve({
                steamUser,
                community,
                csgo
            });
        });
    })
}


initialize().then(function (result) {
    let steamUser = result['steamUser'];
    let community = result['community'];
    let csgo = result['csgo'];
    liveSteamStatus(steamUser, teamSpeakClient, csgo, database, cache, events);
    csgoRanksUpdater(steamUser, teamSpeakClient, csgo, database, cache, events);    
});
```
Here are my logs:
```text
[12-03-2019 02:44:27.152] [Ts3] Not relevant line.
[12-03-2019 03:50:57.980] [Ts3] Not relevant line.
[12-03-2019 04:00:00.356] [Ts3] Not relevant line.
[12-03-2019 04:39:07.575] [Ts3] Not relevant line.
*[12-03-2019 07:00:42.396] [Steam] Disconnected from steam: [eresult: 3] NoConnection
[12-03-2019 07:29:21.150] [Ts3] Not relevant line.
[12-03-2019 07:31:55.641] [Ts3] Not relevant line.
[12-03-2019 08:07:39.147] [Ts3] Not relevant line.
[12-03-2019 08:08:05.222] [Ts3] Not relevant line.
```
The problem comes on the line with *.
As you can see it prints a Disconnected event log, which is correct according to my js code:
```javascript
steamUser.on('disconnected', function(eresult, msg) {
    log.error("Disconnected from steam: [eresult: " + eresult + "] " + msg, "steam");
});
```
According to node-steam-user code: https://github.com/DoctorMcKay/node-steam-user/blob/5aac40cfe0930f93029e4de327a293e424a1d202/components/logon.js#L469 if the bot gets disconnected with "EResult.NoConnection", the bot should try reconnect... But as you can see on the logs, there are no lines regarding to an attempt of relogging again... If the relogging proccess whould be successfull, my code should log that attempt automatically into the logs file as below:
```javascript
steamUser.once('loggedOn', function () {
    log.success("logged in", "steam");
	...
```

**Comment by MitchDizzle** [comment]
"steamUser.setOption("autoRelogin", true);" why are you doing it this way instead of just adding it when you create the SteamUser object?

**Comment by dalexhd** [comment]
@DoctorMcKay I have seen some issues regarding to "setOption"... If that could cause my problem, please update the docs and tell that options need to be set AFTER creating the user.

**Comment by dalexhd** [comment]
Changed from:
```javascript
steamUser.setOption("promptSteamGuardCode", false);
steamUser.setOption("debug", true);
steamUser.setOption("autoRelogin", true);
steamUser.logOn({
    accountName: config.steam.main_account.username,
    password: config.steam.main_account.password,
    twoFactorCode: SteamTotp.getAuthCode(config.steam.main_account.shared_secret)
});
```
To:
```javascript
var steamUser = new SteamUser({
    language: 'spanish',
    promptSteamGuardCode: false,
    autoRelogin: true
});
steamUser.logOn({
    accountName: config.steam.main_account.username,
    password: config.steam.main_account.password,
    twoFactorCode: SteamTotp.getAuthCode(config.steam.main_account.shared_secret)
});
```

Hope this works...

**Comment by MitchDizzle** [comment]
From what you posted you only hook the logged on event once so you'll have no log into it next time the event fires.
```steamUser.once```
and 
```steamUser.on``` 
are different functions.

**Comment by dalexhd** [comment]
@MitchDizzle Does autoRelogin get triggered with manual logOff?

**Comment by MitchDizzle** [comment]
autoRelogin only relogs if it's not a forced shutdown or logOff, so running SteamUser.logOff won't trigger autoRelogin.

**Comment by DoctorMcKay** [comment]
Setting those options in the constructor vs. using `setOption` immediately after should make no difference.
