### ISSUE TITLE
TypeError: Cannot read property 'EFriendRelationship' of undefined

### ISSUE THREAD

**Issue by maxwell187** [DoctorMcKay/node-steam-user#238]
client.on('friendRelationship', function(steamID, relationship) {
 
     if (relationship == SteamUser.Steam.EFriendRelationship.RequestRecipient) {
         client.addFriend(steamID);
         console.log(" ");
         console.log("Accepted friend request from: " + steamID);
         client.chatMessage("it works");
     }
  });
This is my code, my error is the title. I have no idea whats wrong

**Comment by DoctorMcKay** [comment]
Per the release notes for v4, `SteamUser.Steam` no longer exists. Just use `SteamUser.EFriendRelationship`.
