### ISSUE TITLE
How would I go about logging off a specific account?

### ISSUE THREAD

**Issue by alrie** [DoctorMcKay/node-steam-user#239]
I'm trying to run multiple bots at once but am unable to log off accounts separately, how would I go about doing this? (sorry if this is a stupid question but I'm stuck)

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

Just call `logOff` on the appropriate user object.
