### ISSUE TITLE
[Question] How would I connect this to Garry's Mod Server?

### ISSUE THREAD

**Issue by NismoGraphics** [DoctorMcKay/node-steam-user#240]

**Comment by dalexhd** [comment]
I have never worked with gmod servers, but idk that node steam user provides support with game servers like csgo, gmod or even dota2

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

You wouldn't.
