### ISSUE TITLE
custom gameplayed

### ISSUE THREAD

**Issue by dasyah** [DoctorMcKay/node-steam-user#242]
this is will great if node steam-user have custom gameplayed feature like node-steam

client.gamesPlayed({
  games_played: [{
    game_id: '730',
    game_flags: '1234134',
  game_extra_info: 'Custom text'
  }],
  client_os_type: '123123'
});

**Comment by DoctorMcKay** [comment]
You can already do that like this:

```js
client.gamesPlayed([
    {
        game_id: '730',
        game_flags: '12341234',
        game_extra_info: 'Custom text'
    }
});
```

**Comment by CellSplitter** [comment]
No this run into an Error
Try This:

client.gamesPlayed("Custom Text", 730);

**Comment by DoctorMcKay** [comment]
You need brackets. Without passing an array, you aren't playing the second argument.

**Comment by SimonMillerIO** [comment]
what does game_flags ?
