### ISSUE TITLE
Question about .client property

### ISSUE THREAD

**Issue by EduardChernikh** [DoctorMcKay/node-steam-user#243]
Hi after update for version 4.x.x there is missing .client (steam-client) property.

Is there some replacement for this or i need to switch for something else?

**Comment by DoctorMcKay** [comment]
steam-client is gone in v4. [Here are the release notes.](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.0.0)

Is there something you needed to do that isn't covered in the release notes?

**Comment by EduardChernikh** [comment]
I guess no. I was trying to find replacement for steam-client. I was using it with `node-dota2`, and there is `node-steam` compatible client is required. But there is a lot of functionality implemented on top of node-steam-user. Can i use session from `steam-user` somehow in n`ode-steam-client`?

**Comment by DoctorMcKay** [comment]
No, steam-client is completely incompatible with steam-user v4. You can continue to use v3 with node-dota2 if you need, request that the author update it to be compatible with steam-user v4, or fork it and make it compatible yourself.

**Comment by EduardChernikh** [comment]
- "You could also potentially make a shim that translates between the steam-user v4 and steam-client APIs."

will try to do it :) Thanks for your time 👍
