### ISSUE TITLE
Depreciating 2FA code

### ISSUE THREAD

**Issue by dolanmiu** [DoctorMcKay/node-steam-user#25]
Could you not depreciate: 

```js
enableTwoFactor(callback)

finalizeTwoFactor(secret, activationCode, callback)

disableTwoFactor(options, callback)
```

It says:

This method is deprecated and may be removed in a future major version. Use node-steamcommunity instead.

I use node-steam and node-steam-user primarily and do not want to use another unnecessary library on top of those two! 

I feel having node-steamcommunity on top of node-steam + node-steam-user too much.

Correct me if I am wrong

**Comment by DoctorMcKay** [comment]
`disableTwoFactor` no longer works at all.

I'm undeprecating the other two-factor methods but note that since Valve doesn't technically support them, they could break at any time. `disableTwoFactor` already suffered from this.
