### ISSUE TITLE
Bug when trying to login using ClientLogonToken

### ISSUE THREAD

**Issue by dmitriev02** [DoctorMcKay/node-steam-user#250]
## Describe the bug
I'm trying to login using this code:
https://pastebin.com/rQa0p14E

Details are:
{ steamID: { universe: 1, type: 1, instance: 1, accountid: myaccid },
accountName: 'xtranavona',
webLogonToken: 'here_is_my_token' }

Everything is ok, but I receive an error:

> TypeError: (this.steamID || this._tempSteamID).getSteamID64 is not a function

## Versions
Node.JS v8.16.0
Node-steam-user - latest

## Screenshots and Error Logs
Screenshots:
<img width="872" alt="Снимок экрана 2019-04-21 в 13 24 46" src="https://user-images.githubusercontent.com/26174297/56468727-f69de580-6438-11e9-917f-2b1cc43b4912.png">

**Comment by DoctorMcKay** [comment]
Your `steamID` is that object literal? That's not going to work. It either needs to be a [SteamID object](https://www.npmjs.com/package/steamid) or a string that can parse into one, e.g. "[U:1:46143802]" or the 64-bit ID.

**Comment by dmitriev02** [comment]
Hmm... Yea, that's works, thank's!
