### ISSUE TITLE
getSteamLevels

### ISSUE THREAD

**Issue by ZOODEN** [DoctorMcKay/node-steam-user#251]
How can I get the steam level value of a user? For now it just returns undefined.

```
	client.getSteamLevels(['76561197961753878'], function(results) {
		console.log(results['76561197961753878']);
	});
```

**Comment by DoctorMcKay** [comment]
I assume that you've recently updated to v4 and haven't read the [release notes](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.0.0).

**Comment by ZOODEN** [comment]
well, my bad xD
