### ISSUE TITLE
Incorrect connections

### ISSUE THREAD

**Issue by Linnni** [DoctorMcKay/node-steam-user#254]
## Describe the bug
I use your api, on my windows 10 it starts up correctly, but on windows 7 it does not work, it connects to the same account, it says that InvalidePassword ( windows 7 ), but it works on my (windows 10).On some computers with windows 10 also did not connect

## Versions
10.15.3 LTS

## Screenshots and Error Logs
![bandicam 2019-05-18 21-04-58-400](https://user-images.githubusercontent.com/38401362/57972233-09142c00-79b1-11e9-87f5-5fad0111b405.jpg)

**Comment by DoctorMcKay** [comment]
You're going to need to show some code.

**Comment by Linnni** [comment]
> You're going to need to show some code.
-----BEGIN PGP MESSAGE-----
Version: OpenPGP.js v0.5.1
Comment: http://openpgpjs.org

wcBMA7O/EqMafqShAQgAg/7jpBosKWnINNbwwqTpbxqHYt9pogNYguJQxIL0
SzLq6CZNdsbi2z8Zvy4aprmvCis2Z2/WhZdupqIeKKi87doCqH7IdFT2D0o9
Dj2D2NHjxIvtGsxHxm32fupfgKnth2yjSXCJetUQj1XxPnkND6GkwhwP03CR
R91M0VhZTABVi2neuQLsUaG348spR5uFgu7psx11EDeQOramMyXPOU4VXO2Z
kffC1jeuU4rrZ3FPo9P6R2YdgNzN6+Sx0eIq1Myb+atLRobpSWZVsUNF2NZg
adot1iCzC2/eVN0UrFGOw+QXCTJOrU307JAg3AUugfrizbo1C6Iz5stVhkLb
L9LaxgFc3eN6kOPwqMPYCJwBdBKSKny141a68fuNB+tpkPmdagpqWzanT4Lz
0lCFQ61JiuCVUUjBVEYMqPra45s2gDemdZTJHIdt79ammBkh5PtimMxj333j
p7kRcKV7IoWz0O0s3dnNIKPizAII6sStowSnoWuAfo75slxmjR7k2YQdIF9b
Rmmh6Mh/utJaMhHafLaVwjTZInFWmBIzxe8N0Br4f8yjlngxPmhQwjueyRMa
Lgh+TkU+1WjMivUt9Opoz1pTYt4kFx2vcyKd3Jvvwiwfjnai9IH9akmUWrzu
nHBLRtzDysTfi/TUmJpiofCNY2nBrNe4QJvPz9omjw+f7KVMudODJ95B2MA+
qmZ+CZh3lTdDV4RPStQPQulLpYrVolwdB7YoeyHyCzwWS+9wDB7QT2xRtGk+
YJutScRKznqVB6lCOPSrjRQoXcW3ZwTtR2xfQa3vGvnDYBbBC8vUzsnfPsED
0Gj2D+Ytx/nN8yZGu2ifg8JnZgyuB6Q656kwe0L5Ws7O+FWXHKOifY5Mj9Rd
XuHKAR69wR1etTDbRRlBX1l177L6dNd2r36mbrrv6CMRijeJff1cc1TsbnTW
bOOz9qhFJh1FAAJHZxCn7nboTV9ohOOg/beUn3/+xYmciV6qas74a1kSPRlG
DdquuA0K0VkK5+faqeogqMyF/zJFJ6/zHVdkZImiQMgrSIQtMcQHB16PDphm
+dVckKJDbsKXuRLmwQMam3DPw05SguhSwkIaIzauBzcIKWNPQzjS36RrGPP2
Xlmw2ClDHvGM0sqfJjGi931a11aMLiPz+RdE4+YRCzjozgrK7GQuP2wRx2dJ
K7c1mhfKJQ18egsj8Jxlkkr7N+MmIeBQKnjLHFZRB3vWHbBNB62VwIMkStlV
GniDuBEvNe8bwWQOzw7IBbLTI6UmahLWGQIV1HTMaDEqB+vOnbFcipHkeU8H
bedP8qnT30ocNl0FIojTCtKgGG9JNM5X37Gy24NkZUzraXHsbY6Hupm6krHj
CfroHNIX2AqE3hHwelVo1NCwQkLlq1I6ekd/L5xkuE0jYuK4XgWC1wzXbr2C
U4ZjROncaU2i+VTnqjRkCXIV3h4cXyPAwF/ZsR+hQ7zkV2ijeBZZRTg5D8SR
oNagL3CkKPpsm99EgBXyLAa/tE5AxQPBlbkfTZiCmjLcGLkH7EuGzqwZAZ1s
qnTyWGJXWbTF5+OPo6PYbLu1CiVU+rXMSYQE104qspQiQ6GRk1gXCmC+KyXR
hhXqnT8O9AvoUn4GDKbNm1b6J13Gpyr9jWLB13Mj/o3SvyBqb3NcFKDZXgfE
simyNI7tjmf6QgAJ12glzn7C3EihvPlrtmxV4BpE4AXMi8082CWMiMB9ho2O
dOEu/r1tUMKXofthmXkAx8z+U/nX0xX4zHrKOgrPiANgAYry3baTox+zDMxW
Pl27jo5OxJm6bStqDjh8I1yWXfj73zyyrnytEN4uEFzn3p9XKoAxnDKL/SXc
6PIjfeHDPR4808PnHB7tql9jr5Y3S6rR/Se4KJVNy9HEwgS1WOlA/XLuzx0f
748PPu27wgYSr2RoLxEzhX/bCV5gpxIMyz6zWkTulzysz6ZhRSMxb5jMlx6I
Iil+Yqw6W/BS51pBSDGNp4BNYyBhP8oiWIGQ9sz/HxMW4VpWf0tJiJZk0oiT
vYi2Bpn9LQkGrnFoah/fFKmDAEaPoblVmwvCU+4t6QQzZjc/kxI6KAEWc/AG
/1IN//rUflP8c0l2Y5ui1tQqiizT0r3Od71/JRsOIsurGZdvqr65fWfbJCPk
7hJBYGJmX4qdV2FV1w4EB1hhxmf/KJissIJu6OpEAQivijBhOCutbzRLvE0P
SYq2KBywvJn9zgtg/AXMN9XXvUIF2qaX2ToPcEdip1p1zyzsvJFJ6+wCLlw0
4LvZ32e4ZQDkxLGbatzCv+oYDKrepDXxMYmThk6ClV1M1HiUuPmgHjQoXhS2
I9KHnFk/ucrCl2W3PFTPTLnfY9Oc1ZQL86fIKrG3Xft8s8/MvKPRwLsg7XN1
zj01Q+oYDyTyFkyJi8KN+f45hx8XN0+Z3q5ceKuOm6E4D2jH46z6BpLsJJZP
aABw9mnRLqoEeAfulUiR0q8+5RiZ0+BHeATDLJGv8MMMg0FlaoriOcNVsgGh
fwiiqbIOELn12yuEKWqELxYqdTNMf58vDxppV2y5/Sgo/dWIbxn0tXHKr/Tn
kPmTRUi7Vmxj5lihKdWOoge+P2SzihXoM1pLvQfoL8qlHMP+fKEPMeDAYa0V
YlZqEjR2fMyf3ks/dPqh34YtoVdAl5HVjjLPS7LvC57bODx6EzpcgrNbJS6Q
8OsrSbULahZqWTsAGxDXAUGvNIJAhbgemkjGiwNoNcPzS/UXzsFtKdZnACu/
4dDCiHEJFECVrti3zs5pUnNJ3OPUDEyN06SAkA8CC1Wg76WVZhmq6phMC4LT
F//a+WhDKxbKcM7iEkNM2M2khGf6dtWLD9VIM0DwQ62HBTOwjzWGxfWry5Nm
hawJYQzS97tlPtXBIAxw6HHWH1cFCFenoBrGK1GWJae4A+K/Dk9cFcp8z0kJ
uTRy4XXKd6RykY22lfr6yIckl5JXZI7WFSivxtB0y5JNqxb8yJoSXzzkDCZI
vMNiNdxPnZSIFBwZuzxtrw08eKtgBNhshx6zFEfvWEKR/CwiJdduhiLNOND4
cOWGiW7YicJ94UOnL3uZsUW04GAQtj2gljw/7AjEYF9ybV9d+mwQ2TNIziaX
b9NKuNFmpupvH4GY7oLvLeYBsX0c7bd9QmbPw5KGtBr8aFsj+5E8tltffxDd
m9iqAOsrmDwAhYgvHiv7zwKgl/V6dhvcUlbjLJHsedzsk5eBD9nVvFbt+hK2
ig7/rEVtD0d5OBxcOpjPMC/Ki2fkTaX9Gb+FNjk4kkpEp51x1eLmivw1MRCl
4c1Oi3lHtTAXkMzqiCYE3/yuR96DQhoxyN4N22uo/eQNaCw8B4xDoRd6QH47
pdwN5RSJDz5S0TT8nrHsb5glig86A41oJ994WpsCKsRw7tYUi4M2L0xmJ6Lr
ZwKvfXLJ9qVU+Y74fV2wZVw5tHILeSYubSvgvsmVb+tiqU6zLpPPgNwTd+K6
H6OdFF/1Y7hFYolsmYM7UlwSVZf48Z2Jjd/Hr872/PV+KGk30RgRsJgPMoxM
Hp5nZiJHZWb4SDIhn2w8M9hCtPh3eXh70Z5KFkWej2pHdrTVgbzsLpHn9y1A
CB5DCeBkPPV6wZUj+2I+MmLK2UpuqohKmXMgMk9wBAbPdtcWcv1Q8dAtKlnG
FgBsAN9wotb9CJvSocLYg5PycSHwpcT69PXxZ9V3TuUQv9+gAXZSe6LcgeIm
NYOBBboobwEVsPT8IUwETQL8nD4FtCuhamZ44HwTzwyf6+sUZv7GajcavWto
gKNFyIIMYPHtXujE2boXJLF+se1DluLEOKLO8NzjqLh1QpDIS+2NqCn6c66q
Q9qkZ0mi7VmQpozd/n50gLiCaIWnPCxPuexu3VAxXdeVuNP+4SYLmQRV3xzz
w9sM0ZDX1Op267uxnFlxw8e/WHW5eY18cIWkUlsxD+Wif94PEiWJQlOaCqEr
2pR7Y4Q6bWtlMclw6/9IOFWlekzMX4ydZIwzmdANi5ABwVjHZX9SMyZtdm/M
j1hnizXZeZK5id2Qwmt/567zy6alOSyEYQsiPtfqmUkwNb2dLk4qid/0N+gG
SCgKzeXUM7Cw3Dl7r9WijP9DDWTh/ITggGxu2lCs2Er2EeoBrk959g82mRCK
cGakYhWG3d5co9FzmJkTkUM1ND8/TPloHAXxaN3QwFCvciKeMSnhQj9cO2+i
viOgh2W3CvjMWKPlREXg3qUnANdz849Cob090QNLWxuUKZs9wZLMr4z1KlMX
ntw8mskxEKigPhCVBwLxMdeGgUF+JKvI/6o7c2dnQX50oQbtDvKRPTJkGSmn
ZmGuGV8FvLjl9Tl5c2cRZ5W3Ju424wGKBPF8d792dffkkLMq6Q93HrrRNLnn
TgzgjB1bDNcOPkP7oQ3GHRzmzwVkfkLsJIFkYPtKzfZ+xEB78tFF3epZoZJO
iQWRUPZLpHQ5wKmQRTlbNUtKXO49ezrsd5u/u6rcUEhg/fkdbJlwB5MHUDx2
dwOEaxOULcgc+7CLXlTWFhzW9otyH7gCvVrCQh5YqE3I7G1bN6NXt+ByrdqW
PZm8y0B+BxNMTBsbccCR1CBBUkm7yRoO+nHZAmpHAGJeHNWe5jHcXHOtqeAE
bGq85DlmZF88jhQQSVLack0/WRTezvljdfENW4ZFc7h5l6xkdSJuRXBvOYDG
EWIva6swVGHk+9D5nu0yYoVYhf3NbRK4Lmw1ANLs4Qz7QLlU4JhoOU+lo08A
WOrh6+21vF4waayGWcRHl49TNErSS/Nfr9W7jV+gTuSALZ39Aw7tNkyN10QW
nRRqBEc5vAIt2VFZN4MVR0kEEhidcfMn4tpZk/yaUbBDQrSgath80CZETLpE
LSDSBuXYQfATO+nQKuFM+qDiyIaXH+wWVQyqsEeTYV3D4vYdAsjhiXH58r9+
6Vo5yrwQ3I167ennnKeZBjArXVKehKLQeyAqCdZNlSzoDlE9wjw4OFzZEJXR
Ku3incZ/jmdAAiQ4s1bt+XML4L0MLdn1sAs3zUEWDbZhwotDiutwc7/g96+2
odlq4Ll+qzzfDGGUMl4tWiRIW4uI/g5tLZ0KGBkLTBDQDjE8QeJvDBbqXjy1
MHoibtJw8OpE33Y28M8nBy/F0iUn3DFXEE3o5HU+9CUhWvmj917O+kxsCNpO
3Oc64fPZAHZff59/wNjBy3Rn0lf5rtnTGJnHKp0fX8PpcJjb2dC89dIQH0dZ
4rbPPGucHG7V51ItdHJ4TkT73VvdqMO8u5Ux2X4DiuudSiKedG1/pdgAgWr0
7wjsZi1UcgqiJzRWLdDR1q3Uf23VoPZ6HzqygGBAYq1uNFhoyMCd6s69Vi43
s6mbTA0U4jk78m2WqRT/oIrgf6vo5VBo/lqpgrbnHWxKzGSVVLZr7SoPn5Yt
u2jzzx50INxsF8JhUHJA2ZArWCtn67J11XrNxibV3NiHpXbB2FbXglnIJ4cr
6VJw6yknsXbcNn9faqG1tV1h1cCQe0L10/s0UJSYgjxvxvpFvD5jk+by+m6T
40P5FTFpdCJVWnyggBwOweCOt6xwZ0nX6h0dt8508i6JuzVeTbrDiCjjPgDQ
HM4JBbhvasOx1+f7mVXDzhuxa0FwpYchAoRP8qiLk6ohxctyZKWuq99Oa4B4
FPF+C9/iIXhkveyKbJzalJ+lxL3wZ15BOsj0WdxNZd7/halksNFuLQRTBGQJ
BRBJoAv0vgIfybE4uUlbV1RruuSmGxlSyhy390ufHSA8g0YHWPuAZeDMVjKF
pwyoe9VhsZJwH6Ctmk7bKxz3b41JPYoHWSY3qkLyr941OnERMWZPrlwf1fTk
oOVxtLI58gxP5WPF2JWKMHwPr71ChtaqZNdIY9rONLbKWZyB45s1L97ACtr8
3JjgtSiJ3qfXT4Vx0HqvWoiSpMVcAKMa5y0gtoS57O7Tgme52LfDc7NS6NtU
Zl2sEUf19B5bwcyjl3WrhpovcAX5g0t/VW+rrE/paD0ZVc1GgDvdOXOS4Fb5
KLsSBhRyzYkWfNERnhp5CuW6pGPjXvtPUgYhROMk2Fp952a66nf5Kab1icgi
CFAcr6JMmc565DPgoIkQbZN95aDDemXF14Xtm/Ir37arjpSewLvTWSglsYf2
SNeGuTSkqPKmZAmMdmeOqB56zMYeP2O0SRXWDjnqPd4Eh0MIDvksKMVLJZPi
n3hsaSLAXtxUmSs7NUbyUkRb6OeL5Y+MiTCJq/yZHSLJOJKPF43IDX+lUerA
PrOb2Tq3gp+Xj8HWzASMVPPjVAof9XGpmM4U600FB2CNJxLQCJK63W19F5nq
U/RIXnLtgQqaSoe4qydvPjRpKQ7JEaP1hb1O5RnKGOKcJ9ttqW9TfOAwlRcs
jE7rWczsOPlT/kLFLgl6KC9YfUlR47BW8RLIYvmBNnRmzMXHBu/Yj1U7uo95
6al7EtXNiFNh6inb26xIzhZjXpw+kxKwTHgGV7A1j9jc7pKscrzYYjWq50sa
5YbzFtW1KsVYO60MrxmpoMs3pHOqp0UdHeBXclVzQwH0JMzTNtkoIH88eaZO
FyAMqHwvG1qGrD2mqZcW5EM3043BSB2QLHDat0XfhD0AOKWa6uQ1qvkodF5C
Y/1A5DNmm2bZ1uoOI0MRGhyZVmrZXOVL3vDSkfj8ExD/pS2xwv6xHPsK9wuv
GRvvNPr2CJdyS0XCkUSHxzzfwbzEuS85T2t5RuzOGEJNXYjaPbKmzpVqNu3d
lPy1DtaPMQ0E0XxG/u6AeIKrFH+tsuUsbVktHE7O+Y8fpm5M2OgfcNh6yDGk
adPgrImtMqqsGEeRIUEBeVNejUe4NxC1Iy7V4Jnzprz/9L6wp0IPx00+1TKm
JgfyyThAA4Uub6/z19LpmMZLy3anngvg0DF0xzCweSUGo2pcZlq2pKISCPZg
yQV7TtX2BT77Q2zVudeVqOhwCt9P0JJLCjY7V2ywaTPXJwFl7/Br4rzL2W26
BozMc2TvtngmPltI+WTd5Jc+8mtciUaaO8ASYptRapy+YWLFRuNWp3BvZpxT
/7z5gZ9d0wAvUTAB5M3Wc7YfP6d9lhgZpM8YyESqSMaNNv08qJi333+SDdm0
Yie4q3v0OxxAqejQ937XWlNoz/Xc8yLXp3VhJEEtBG7JCZCpkJJU1M3xcw5J
z8QGc7wBfZDF1f7N3lqPzaxUh8fb6uK6MilBewwixPQS1nH6//S89mqtLwY4
xhbwbClZg4GFYCVnhSDAOWGXlX8LWtMe3q1QRLrhsFdNeiZhSejkeBEIVlmi
cxxLWgM0YEINgvWG0s8JzQvpg1MIWBhimSuXTRpHFnMUVG05eYrR661Ky9U3
URXGpeWv9dIFI6V4Ty/JaMNSqTzzlp+UtWjtXDtr08kDuLZ4TSK8zIkWjc65
VdNgmGZytdwleG7VwumQygy+bYgbyew2iBklNX38cWYBD8nDiDQkcTz9n+Wf
GVLZQUFpeyJOqXbkTcBBMDa58CLtgC+0QWsdXe3LXLJGPUbDPmJb7OgN+Lyp
oSnxr2k2rkC92d8ZtWhgs1G3D9C9slPyc2HKbDUCDHmi41VWr25M9rYGtNyO
2C4qaWXDJO0Ya9oqhv0Xz649lp0KxBTov9NG98VQ3evwi+knxHvgdY7IWfAt
w8uiPJ8rMywAiJfhA+9sSdTYokYTSjUkA7aI7t+Kv/UkkZ8y89tDLRTSf2mv
jmDoI6QekTVaVUqRKIdS+RniU4KnT0RlFEy1czOHOrbSCLHnbSnI2Yg3Bizy
MGt4FlBthSQGZU0omwrgv95W7GbiksDWkiFp4AS8C5xwKMK6IlXnIjVQ75cC
tBpLWBvU57kZPCoRC0+kavEfYMb5uDsU+C5R4e02i97Z3WZyV4zKp3XL7MdO
7M40dP26WxV19z/rhBolwXpM0VTzRPUr/O7/DVg3MA9JrfEd00Q7FVjMNDnY
SlWr1BPr96g+gXawEPY5JWE34OFPFjq0k0K08+SrY6Ttpg2fmnfVE65R2XLN
mbbp+wgH1f8K5frPaV2l+6Fyd4MN0dGX34XbwYRXbHqJVS5xg9kECdmuzppX
lQcfllNIyNQxfRnOtLVSrxYzEIBzNZPliqvWf14rNXkXR1SeBO+vVmAHTH0i
v7GuzBBMh/od+M1F7yFMFUfwIA8TaIp9aUAWpgcc0MCNAbydpBTAR4qVwHMZ
muSs9cVuO3dXXlClfRZ7zRdWTv9ieIzcc5mnVznl9Ln9caAuifX93mSoLG/G
iDKicRncCgUxCb+whH01IkABlOBR8ukP1UryadZuu1+GsimgqmGSeyFBYUaf
F2uK1CEwkS2ZsAKH0IIhKGTwR7RK8xG9Q725U53djbT1wzY0wxwA+hJzzkzd
Z0ITUM9UxTmZfP/HRiDwbhsAW+c8vFbS6IJn+nKr6znR/k0o8CFzMdL7D3nq
/Kqiu7I78FGksqg4FgEr57tE8PuYSq5mUI1Nnai8QOCHPqF30Xd3ZdmtIDHn
rcGuuhbcDU8f/4zKy3sp/Kxbm1n6NwTlWxiQ3B6sde+MiBQwtsE1XcaWiTSB
w2LOql0mmRCiRZeB6mRHaOq5a1WUZXMsWK/G3IyNqhLPFBoFpD6g8e3a8VoK
VrQb/guech5VkKJ6epKkjemhqyaOQNZbi1SMpG8l6Z/Cjs8QCMezcK6rDju7
N32IAMfUH8bQjlio/asW6uSi9tMmrXWcbBtLp2ddHw+kqpbJPy1ZpMW2o6vf
P1/4RCOMr96AS/7w+u5wMVesIbnrBVkmxsUr7ltw0UPQzffX4XdLNpKfgSnE
zeltV0g04bsht+XE9L9bqZHHEC38QXb/PdX53oYVqjsOBQ7xo8ThPuCv1KfC
iQFb2hImeOevIs7e2zlHI0500Z6ACV6Y4vjAq6bcs+4/YgeH3/f8xmDDdG/I
0+eKjVweC1IUiBrEY+pyZyq97Sjhw5m5rJ5EC7YduLDeawvcmIwYKO4Iyx+T
u+QOSZPYMrAuCknhXOUchNoUA6kRFgZGYUoJKLDxikCPq1N9nWmCkc1v1gr0
Q33ZhwVmMYPycs5dzEiwRc281AGLmGpRvDy8Sob7ica1trfCYCAnU7OvLVFf
rVlP9oXBlRD6T/pdf8ClCGt97LsQPbagaDo7ssgkdWAzedlEzgFlMLWBlLEW
Gpx/zu5SqnwSsxNIvvCR3SoJC7DWqqZyoyNwYXp1kxOK/HCEAMS6TWwpbO57
jroXce3dOVqVa2i0ndUibn49keCSh+yszlKea7BwidNdAjQhDh1Y4t2vwyKE
AqspRUrkuyjAvVnBWalxRXr/yfkqxbPE0APvuz10lOu7RXE6G39MJ7ParvOo
sPzP3BilO1PnhhXsNFTHk1i1cQt5DAOfy5YZi0dOnqzUyXGsXE5WPDqJgX/n
AbJqGs03gLyLLwARuCkfdrDPrLMKSZCyecJ/3bEZRqYF8Y6jekBQFAOxuF37
vYaXyCbhcjSgdyPXH3mf/TVQx9Ul/+A19FQOAwOk0Yq8NtIsEf3X1ySp1DIP
vnDKQnf+ufS5gBDqsF8uuIRpOK/XgrrtS9TrXYWgIo+2XbXcpPBNrCa21wrk
pBbLl3MOy9nZ260fR0CMKgMeeYuUq/THamf0UHwTMx7JuxhAD71FYPMHa5p4
apRkP2jDyPViYUWLC0cvIdh9TgtiTL5gtCCp0uKgJp6SXZhU5T5r4JN+emtB
BkOBA/aUghaTUrpP5dFUynIXiI8gxJ3GdpTot0SVK6xwzOJzSIxnmBTjsage
XHUxchGAkNVPJ2ZqLdhO2Zfz6JlWiV72KKOjr/vv
=U7q5
-----END PGP MESSAGE-----

**Comment by DoctorMcKay** [comment]
I don't see anything obviously wrong. Your password is probably wrong, or else Steam is shadow-rejecting you because you seem too suspicious. Make sure you're up-to-date as well.
