### ISSUE TITLE
Get offline/unread messages

### ISSUE THREAD

**Issue by DataWorm** [DoctorMcKay/node-steam-user#255]
I am not entirely sure if this should be a bug or a feature request. In the deprecated chat versions I saw that there was the 'unread' property available in the deprecated chat history method. But the new chat features seem to be missing that property. I can use the offlineMessages event to check from which friends I received offline messages. Then I can request chat history for those friends to actually get those messages. However I still don't see how I could determine which of those old messages in history are unread offline messages. Is it possible to fix that or re-add that feature?!

**Comment by DoctorMcKay** [comment]
Update to [v4.9.1](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.9.1) and I've added an `unread` property to `getFriendMessageHistory`.
