### ISSUE TITLE
Retrieving chat history

### ISSUE THREAD

**Issue by DataWorm** [DoctorMcKay/node-steam-user#256]
When I try to retrieve the chat history I only get an error that doesn't really help me to find the issue. This is how my code looks like:

```
userClient.on('offlineMessages', (count, friends) => {
	for(var key in friends) {
		console.log("Offline messages received from: "+friends[key]);
		userClient.chat.getFriendMessageHistory(friends[key], {}, (err, response) => {
			if(err != null) {
				console.log("Could not load message history. Reason: "+err);
				return;
			}
			for(message in response.messages) {
				if(message.unread) {
					// ...
				}
			}
			userClient.chat.ackFriendMessage(friends[key], new Date().getTime());
		});
	}
});
```

And the output I get:
```
Offline messages received from: 76561198037818611
Offline messages received from: 76561197974973438
Could not load message history. Reason: ReferenceError: message is not defined
Could not load message history. Reason: ReferenceError: message is not defined
```

Is it a bug or am I just doing something wrong? 

Btw, thanks for the help and this useful library! =)

**Comment by DoctorMcKay** [comment]
for(**var** message in response.messages)

**Comment by DataWorm** [comment]
Oh boy, that's embarrassing... I didn't look that far in my code cause the log line printing this error comes earlier. I suspect your code tries to call the 'success' handler, catches the exception caused by my code and then calls the handler again but this time with the error message?
Anyway, thanks to your help everything seem to work just fine now! =)
