### ISSUE TITLE
internet issue probably, but still..

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steam-user#257]
## Describe the bug
this happened once so far, my internet is not good, but still should be a way to avoid this crash right?

## Versions
im using atm, the latest release

## Screenshots and Error Logs

> TypeError: Cannot read property 'eresult' of undefined
>     at SteamUser.user._sendUnified (c:\JustAzul\OnGoing Projects\Bluebot\V4\node_modules\steam-user\components\chatroom.js:404:45)
>     at SteamUser._handleMessage (c:\JustAzul\OnGoing Projects\Bluebot\V4\node_modules\steam-user\components\messages.js:530:34)
>     at SteamUser._handleNetMessage (c:\JustAzul\OnGoing Projects\Bluebot\V4\node_modules\steam-user\components\messages.js:467:7)
>     at TCPConnection._readMessage (c:\JustAzul\OnGoing Projects\Bluebot\V4\node_modules\steam-user\components\connection_protocols\tcp.js:193:12)
>     at Socket.emit (events.js:198:13)
>     at emitReadable_ (_stream_readable.js:539:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by DoctorMcKay** [comment]
Thanks, this crash will be fixed in the next release.
