### ISSUE TITLE
BBCode issue

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steam-user#258]
## Describe the bug
Im not sure if this is a bug, but when a message to send is to big, and i use something like "/pre", in the end of the message sent, it shows "[/pre]"

**containsBbCode** is seted to **true**

## Versions
Latest

## Screenshots and Error Logs
![bugr](https://user-images.githubusercontent.com/30638036/59164020-5c742880-8ade-11e9-9450-d84631fc6ea3.JPG)

**Comment by DoctorMcKay** [comment]
Yep, this isn't a bug. When you use a command like `/pre`, Steam rewrites the message and injects BBCode. So `/pre foo` ends up as `[pre]foo[/pre]`
