### ISSUE TITLE
Sending game invitation as friend message

### ISSUE THREAD

**Issue by jkune** [DoctorMcKay/node-steam-user#259]
Hi all,
 
I am trying to send a game invitation friend message using node-steam-user.

I am using sendFriendMessage function with EChatEntryType option established as 3 (InviteGame value at https://github.com/DoctorMcKay/node-steam-user/blob/master/enums/EChatEntryType.js)

```
const SteamUser = require('steam-user');
const client = new SteamUser();
 
client.chat.sendFriendMessage("steam64Id Here", '[lobbyinvite  appid="App Game IdHere" lobbyid="Lobby Id Here"][/lobbyinvite]', {chatEntryType: 3});
```
The result is that there is no invitation sent in steam chat

I supposted to fill the message parameter like that because of im getting the lobbies invitation history chat in that format. I saw all node-steam-user docs and i did not found any tutorial or explain about how to use this function with EChatEntryType as InviteGame value.

¿How can i use this function to send a game lobby invitation message to a friend?
 
¿What data and would be the message parameter in the function?
 
Thanks in advance

**Comment by DoctorMcKay** [comment]
https://dev.doctormckay.com/topic/2176-chat-invitegame-message/
