### ISSUE TITLE
webSession not being fired

### ISSUE THREAD

**Issue by dolanmiu** [DoctorMcKay/node-steam-user#26]
The webSession event is not being fired for some reason.

> webLogOn()

> SteamUser will automatically log onto steamcommunity.com when a successful connection to Steam is established (as an individual user)

```
var steamUser = new SteamUser();
loginBlob.create(botDocument, authCode).then(function (logOnOptions) {
    steamUser.logOn(logOnOptions);
});

steamUser.on('webSession', function (sessionID, cookies) {
    console.log("Got web session");
    // Do something with these cookies if you wish
});
```

Do I need to add anything extra?

**Comment by DoctorMcKay** [comment]
As established [here](https://github.com/steam-forward/node-steam-forum/issues/136), you logged on anonymously.
