### ISSUE TITLE
blockUser() isn't working

### ISSUE THREAD

**Issue by Triniayo** [DoctorMcKay/node-steam-user#263]
## Describe the bug
I'm trying to block users, who try to spam my bot.

`steam.on('friendMessage', function(steamID, message) {
   if (recentCommand === command && recentSteamID === steamID) {
        steam.chatMessage(recentSteamID, "You have been blocked due to spamming. If you feel like this shouldn't have happened, feel free to contact us.");
        steam.blockUser(recentSteamID);
    }`

## Versions
4.11.1

## Screenshots and Error Logs
I don't get any errors/screenshots. Result is null. According to the documentation, null = successful blocked. Unfortunately, nothing happens.

**Comment by Triniayo** [comment]
Nevermind. Steam bugged out... No idea how I'm still able to message someone who blocked me, but alright x)

#closed

**Comment by DoctorMcKay** [comment]
Could be that the Steam client applies filtering to incoming messages to ignore messages from blocked users client-side.
