### ISSUE TITLE
Wrong data type in Custom Storage Engine

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steam-user#264]
## Describe the bug
The **cellid** file its sending on "save" event a non-buffer type, and this is casualy making some unhandled promises error in your module, i managed to temp fix that by converting any non-buffer types to a string type, but im afraid that it might not be the best solution..

## Versions
Latest

**Comment by DoctorMcKay** [comment]
I don't see how that's possible, since the file-manager module [converts strings to Buffers automatically](https://github.com/DoctorMcKay/node-file-manager/blob/master/index.js#L52).

**Comment by DoctorMcKay** [comment]
This should be fixed in v4.12.2.
