### ISSUE TITLE
No callback when disconnected from steam

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#265]
![image](https://user-images.githubusercontent.com/4411977/62640506-0be44480-b942-11e9-9903-fa62abda49ea.png)
So, what I suspected happening was: I redeem a steam key, I lost connection to steam (and relogged). However, the steam key was redeemed without calling the callback. This leads to an invalid state in my app. Could this possibly be fixed?

**Comment by DoctorMcKay** [comment]
If you lose connection to Steam after a request is processed but before a response is received, there's no way to recover that response. You'll have to make your app more robust to handle this case.

**Comment by Revadike** [comment]
Maybe add a timeout option?
