### ISSUE TITLE
chatTyping

### ISSUE THREAD

**Issue by fjexe** [DoctorMcKay/node-steam-user#266]
A notification is displayed for only a few seconds. 

In some cases, the bot needs more time to process the data and send a response.

I suggest, if possible, to repeat the notification until the bot sends a message.

00.00.01 USER: !Check // (need 20 sec)
00.00.02-00.00.05 BOT: *bot is typing*
00.00.06-00.00.20 BOT:  // *nothing*. should be "bot is typing"
00.00.21 BOT: Results // any message (as well as any other actions: trade offer, invite to game etc.) from the bot should complete "bot is typing"

**Comment by DoctorMcKay** [comment]
Hm, I don't know if this would be useful enough to warrant building into the module. I think you should instead just keep sending typing notifications until you have a response ready to send.
