### ISSUE TITLE
Force redeem steam key for freeondemand cases

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#268]
Ok, I didn't know this. I thought steam keys would "overwrite" freeondemand activations, but apparently not. 
So, what you should do:
AlreadyPurchased => get apps => get owned sub of apps => check sub billingtype => if EBillingType.FreeOnDemand, deletepackage => redeem again => restorepackage (for extra package).
Again, this could be optional by using a boolean.
Delete- and restorepackage can be performed using help.steampowered.com API, which you probably find troubling, as this is out of steam-user's scope.

**Comment by DoctorMcKay** [comment]
I do agree that help.steampowered.com interaction is out-of-scope for steam-user. Also, I believe that Steam should only reject a key as AlreadyRedeemed if you already own all of the stuff it grants. Is this not the case?

**Comment by Revadike** [comment]
> I do agree that help.steampowered.com interaction is out-of-scope for steam-user. Also, I believe that Steam should only reject a key as AlreadyRedeemed if you already own all of the stuff it grants. Is this not the case?

Yes, if a package includes all owned apps, it returns `AlreadyPurchased`, even if you don't actually own that particular package. The benefit here, is a free-on-demand package doesn't give you a +1 or make the games show up in your steam library. It also doesn't allow card farming for that app. That's why it will be beneficial to add a non-free package. 
I've heard from a friend that Valve did allow "free-on-demand overwriting" at some point, but changed it later.

**Comment by DoctorMcKay** [comment]
Free-on-demand licenses can be removed via the store site by making a POST to https://store.steampowered.com/account/removelicense with `sessionid` and `packageid` parameters. I could build this into steamstore.

**Comment by Revadike** [comment]
> Free-on-demand licenses can be removed via the store site by making a POST to https://store.steampowered.com/account/removelicense with `sessionid` and `packageid` parameters. I could build this into steamstore.

yes, I know. Would be a nice addition to steamstore. But this API only works for free-on-demand packages (yes, that's in this case), but doesn't allow restoring it. Yes, you can request free license again, but that's not possible if you redeem a "equivalent-package" steam key after removing the free license.

**Comment by DoctorMcKay** [comment]
I don't see why you'd want to restore the free-on-demand package if you have a paid package for the same thing.

**Comment by Revadike** [comment]
> I don't see why you'd want to restore the free-on-demand package if you have a paid package for the same thing.

Yeah, it has no real benefit, except a +1 for your licenses.

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steamstore/releases/tag/v2.2.0
