### ISSUE TITLE
[Error: Error 88] on finalizeTwoFactor

### ISSUE THREAD

**Issue by dolanmiu** [DoctorMcKay/node-steam-user#27]
I have a function:

```
function (secret, code) {
                var deferred = Q.defer();
                
                console.log('Confirming two-factor: ' + secret + ' ' + code);
                this.user.finalizeTwoFactor(new Buffer(secret), code, function (err, response) {
                    if (err) {
                        console.log(err);
                        return deferred.reject(err);
                    }
                    deferred.resolve(response);
                });
                return deferred.promise;
}
```

But it gives me ```[Error: Error 88]```

What is wrong? Is ```new Buffer(secret)``` bad?

the ```secret``` and ```code``` are both strings.

**Comment by dolanmiu** [comment]
Did some research and 88 means:

[Error: Invalid activation code]

But I swear it is the 100% the correct code

**Comment by DoctorMcKay** [comment]
88 is TwoFactorCodeMismatch. Depending on what kind of string `secret` is, you need to construct the `Buffer` differently. If it's base64, you need to do `new Buffer(secret, 'base64')`. Doing it the way you are is just constructing a Buffer containing the string literally.

**Comment by dolanmiu** [comment]
I looked inside your code, and it seems like you use ```steam-totp``` internally.

I looked into: https://www.npmjs.com/package/steam-totp

and it says it can use a String. Should I just use a string instead and not bother with buffers? If so, you 

> ```secret``` - Your shared_secret, as a Buffer, hex string, or base64 string

**Comment by DoctorMcKay** [comment]
Yes, that should work fine.

**Comment by dolanmiu** [comment]
Thank you! it worked perfectly.
