### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Slydelix** [DoctorMcKay/node-steam-user#270]
## Describe the bug
Error occured when fetching the servers from the server list

## Versions
Node v10.15.3
Module: 4.12.3

## Screenshots and Error Logs
![image](https://user-images.githubusercontent.com/7862481/64393037-e2f1c500-d04f-11e9-9b8f-e8d0f7e0f619.png)

**Comment by DoctorMcKay** [comment]
I am unable to reproduce this. Please show the code you wrote that causes this.

**Comment by Slydelix** [comment]
![image](https://user-images.githubusercontent.com/7862481/64446850-2f81e280-d0da-11e9-9dee-e3e25320635f.png)

**Comment by dilawfird** [comment]
Do you have this error each time ?

**Comment by Slydelix** [comment]
It happened only once so far and I've been using the module for months now so I guess it's really rare?
