### ISSUE TITLE
Error: LogonSessionReplaced

### ISSUE THREAD

**Issue by Slydelix** [DoctorMcKay/node-steam-user#271]
## Describe the bug
The bug occurs when logging off (?)

## Versions
Node: v10.15.3
Package: 4.12.4
## Screenshots and Error Logs

```
Error: LogonSessionReplaced
    at SteamUser._handleLogOff (C:\Something\node_modules\steam-user\components\logon.js:508:11)
    at SteamUser.<anonymous> (C:\Something\node_modules\steam-user\components\logon.js:475:7)
    at handlers.forEach (C:\Something\node_modules\steam-user\components\classes\HandlerManager.js:37:12)
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Something\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Something\node_modules\steam-user\components\messages.js:543:24)
    at SteamUser._handleNetMessage (C:\Something\node_modules\steam-user\components\messages.js:478:7)
    at SteamUser.processMulti (C:\Something\node_modules\steam-user\components\messages.js:570:9)
    at SteamUser.<anonymous> (C:\Something\node_modules\steam-user\components\messages.js:564:16)
    at handlers.forEach (C:\Something\node_modules\steam-user\components\classes\HandlerManager.js:37:12)
```

**Comment by DoctorMcKay** [comment]
Show your code, please.

**Comment by Slydelix** [comment]
`User.on("loggedOn", async details => {
    try {
        let received = false;
        setTimeout(() => {
            if (!received) User.logOff();
        }, 10 * 1000);

        let result = await User.getProductInfo([252490, 258550], []);
        if (result) {
            LatestClientUpdate = Number(result.apps[252490].appinfo.depots.branches.public.buildid);
            LatestServerUpdate = Number(result.apps[258550].appinfo.depots.branches.public.buildid);
            LatestRelease = Number(result.apps[252490].appinfo.depots.branches.release.buildid);
        }

        //Slow AF
        let servers = await User.getServerList("\\appid\\480\\gamedir\\rust\\secure\\1", 100);

        received = true;

        if (!servers) return;
        if (servers.servers.length < 1) return;

        LastServerListUpdate = new Date();
        ServerList = servers.servers;
        User.logOff();
    }
    
    catch(Ex) {
        CreateWebhookRequest("Woah, an exception while getting info from Steam!\n" + Ex);
    }
});`

and I occasionally run `try {User.logOn(); }
    catch(ex) {
        console.log("Got an exception while trying to log onto Steam!\n" + ex);
        return;
    }`

**Comment by Slydelix** [comment]
`User.on("loggedOn", async details => {
    try {
        let received = false;
        setTimeout(() => {
            if (!received) User.logOff();
        }, 10 * 1000);

        let result = await User.getProductInfo([252490, 258550], []);
        if (result) {
            LatestClientUpdate = Number(result.apps[252490].appinfo.depots.branches.public.buildid);
            LatestServerUpdate = Number(result.apps[258550].appinfo.depots.branches.public.buildid);
            LatestRelease = Number(result.apps[252490].appinfo.depots.branches.release.buildid);
        }

        //Slow AF
        let servers = await User.getServerList("\\appid\\252490\\gamedir\\rust\\secure\\1", 100);

        received = true;

        if (!servers) return;
        if (servers.servers.length < 1) return;

        LastServerListUpdate = new Date();
        ServerList = servers.servers;
        User.logOff();
    }
    
    catch(Ex) {
        CreateWebhookRequest("Woah, an exception while getting info from Steam!\n" + Ex);
    }
});`

**Comment by DoctorMcKay** [comment]
It looks like you aren't checking whether your timeout has elapsed and you've already logged off before attempting to call `getServerList` or `logOff` at the end. That might be causing it.
