### ISSUE TITLE
Steam guard code is asked for every time despite sentry file being created

### ISSUE THREAD

**Issue by fuwwy** [DoctorMcKay/node-steam-user#275]
I've been trying to get basic authentication working with the module and have faced an issue where despite the sentry file being created and the account logging in successfully, further attempts to login will ask for an auth code again.

```
const SteamUser = require("steam-user");
const client = new SteamUser({
  dataDirectory: __dirname + "/data/",
  debug: true
});

client.on("loggedOn", function(details) {
  console.log("Logged into Steam as " + client.steamID.getSteam3RenderedID());
});

client.logOn({
  accountName: "----",
  password: "-----"
});
```

This is the console output:
![image](https://user-images.githubusercontent.com/9268058/66001057-9eafe400-e498-11e9-9f60-f17b21fab377.png)

I've checked both the sentry event which is being called correctly after login and using the default data directory which doesn't change the issue.

**Comment by DoctorMcKay** [comment]
If you're using a mobile authenticator, you have to enter a code every time you log on, regardless of sentry file.

**Comment by fuwwy** [comment]
Is there any way around this that doesn't require the secret? Perhaps anything around remembering the session?

**Comment by fuwwy** [comment]
I looked into how a project on github implements this and figured it out using the loginKey, thanks for the info

**Comment by systemofapwne** [comment]
> I looked into how a project on github implements this and figured it out using the loginKey, thanks for the info

Could you please elaborate which project this was? I am facing the same problem right now and unfortunately, you did not share your solution. Thanks in advance.

**Comment by itsfolf** [comment]
> > I looked into how a project on github implements this and figured it out using the loginKey, thanks for the info
> 
> Could you please elaborate which project this was? I am facing the same problem right now and unfortunately, you did not share your solution. Thanks in advance.

It's been a while on this one, I managed to track down the project files thanks to the screenshot above but I am not entirely sure if what I'm saying is correct. Basically, you had to listen to the `loginKey` event for the session key, and then pass it on to the `client.logOn` parameters.
It seems like `loginKey` [has since been deprecated](https://github.com/DoctorMcKay/node-steam-user/wiki/v4-%E2%86%92-v5-migration-guide#removed-deprecated-login-key-functionality) though, and you should be looking for `refreshToken` instead.
The project's README includes [some documentation on refresh tokens](https://github.com/DoctorMcKay/node-steam-user?tab=readme-ov-file#using-refresh-tokens).

**Comment by zahrasalehi** [comment]
hi, why dont you use sentry instead? although i have some difficulty implement sentry to login without auth code, but this seems to be another good solution too that i gotta ask which one of these solution you suggest? (due to your experience) thank you.

**Comment by kotleni** [comment]
just a...

```
client.logOn({
	accountName: STEAM_LOGIN,
	password: STEAM_PASSWORD,
});

client.on('loginKey', function (key) {
    fs.writeFileSync(STEAM_KEY_FILE, key);
    console.log(`[${this.username}] Login key saved!\n`);
});

client.doLogin = function () {
    var details;
    if (fs.existsSync(this.loginKeyPath)) {
            let loginKey = fs.readFileSync(this.loginKeyPath, {
                    encoding: 'utf8',
                    flag: 'r',
            });

            try {
                    jwtDecoder(loginKey);
            } catch {
                    fs.unlinkSync(this.loginKeyPath);
                    bot.doLogin();
                    return;
            }

            details = {
                    ...commonProperties,
                    accountName: this.loginKey,
                    loginKey,
            };
    } else {
            details = {
                    ...commonProperties,
                    accountName: this.username,
                    password: this.password,
            };
    }
    this.logOn(details);
};

bot.on('steamGuard', function (domain, callback) {
    if (!this.sharedSecret) {
            var authCode = readlineSync.question(
                    `[${this.username}] Steam Guard ${
                            !domain ? `Code (Mobile App): ` : `Code (${domain}): `
                    }`
            );
            callback(authCode);
            return;
    }
    var authCode = SteamTotp.generateAuthCode(this.sharedSecret);
    console.log(`[${this.username}] Generated Auth Code: ${authCode}\n`);
    callback(authCode);
});
```
