### ISSUE TITLE
Avoid connection leak

### ISSUE THREAD

**Issue by Luluno01** [DoctorMcKay/node-steam-user#277]
## Describe the bug

Connections to GC/CM will sometimes not close after a success call of `logOff`.

### Bug Reproduce

_Not sure if these steps can reproduce the bug 100%._

1. Create `SteamUser` instance `user` and log on via `user.logOn`
2. Create `GlobalOffensive` instance `csgo` with the `SteamUser` instance
3. Invoke `user.gamesPlayed(730)` and wait for `connectedToGC` event emitted by `csgo` (as required by the documentation)
4. Invoke `user.gamesPlayed([])` (this call will success in my case)
5. Invoke `user.gamesPlayed([ 730 ])` (this call will also success in my case)
6. Wait for a long time until the GC/CM goes down and `user` **re-logged-on** automatically
7. Make sure `user` is "playing" CSGO using `user.gamesPlayed`
8. Invoke `user.gamesPlayed([])` to tell Steam the user is no longer playing CSGO
9. Log off via `user.logOff`
10. Check connections using `netstat -anop`, you may possibly find some unclosed connections

I am not sure which steps are not necessary and if these steps are guaranteed to reproduce the bug.

## Versions

* `node-steam-user` version: `4.12.4`
* `Node.js` version: `12.10.0`
* `node-globaloffensive` version: `2.0.2`

## Screenshots and Error Logs

Unfortunately, no.

**Comment by Luluno01** [comment]
I found **auto-reconnection** will also (probably) lead to connection leak.

**Comment by Luluno01** [comment]
When steam's servers went down, I saw more memory consumed after reconnection.

**Comment by Luluno01** [comment]
It seems like the TCP connection is not destroyed after the stream ended

https://github.com/DoctorMcKay/node-steam-user/blob/da6c14ce0d91aa06be45356847857ff7a6853208/components/logon.js#L272
https://github.com/DoctorMcKay/node-steam-user/blob/da6c14ce0d91aa06be45356847857ff7a6853208/components/logon.js#L281

**Comment by DoctorMcKay** [comment]
This was probably fixed by some changes I recently made to connection code. Please reopen if you still see this happening.
