### ISSUE TITLE
Built-in polling system for PICS not working

### ISSUE THREAD

**Issue by h1nk** [DoctorMcKay/node-steam-user#278]
## Describe the bug
After looking at [this](https://github.com/DoctorMcKay/steam-pics-api) and [this](https://github.com/Js41637/Steam-PICS-Monitor/blob/master/src/steam.js) project I tried making a simple script to get changelist updates like https://steamdb.info/realtime/.
```javascript
const SteamUser = require('steam-user');
const user = new SteamUser(null, {
    enablePicsCache: true,
    changelistUpdateInterval: 5,
})

user.on('loggedOn', _=> {
    console.log("Logged onto Steam as", user.steamID.getSteam3RenderedID());
});
user.on('changelist', (changeNumber, apps, packages) => {
    console.log("New change", changeNumber);
});

console.log("Logging onto Steam anonymously...");
user.logOn();
```
The problem is I never get any data in my 'changelist' callback. I'd ideally like to get updates for everything in https://api.steampowered.com/ISteamApps/GetAppList/v2/.

## Versions
Node.js version `v10.16.3` & latest library version

**Comment by DoctorMcKay** [comment]
If you're sending update requests every 5 milliseconds, Steam is probably dropping your requests.
