### ISSUE TITLE
How to catch ClientLogOnResponse?

### ISSUE THREAD

**Issue by jsieler** [DoctorMcKay/node-steam-user#28]
I've managed it so far to auth my app automatically, even with 2FA. But i've noticed that 2FA code is not always valid if logging within few seconds again. Looks like the code is getting invalid.
If i start my app, wait until it logged in, then close it and start again, this part of code is fired and im asked for a new 2FA code. 
https://github.com/DoctorMcKay/node-steam-user/blob/master/components/logon.js#L189

Is there a way to catch this event within my app so i can check the EResult by myself?

**Comment by DoctorMcKay** [comment]
No, you shouldn't need to. You're likely trying to reuse a code that you already used, which isn't possible.

**Comment by jsieler** [comment]
Can this even be catched, so i have to tell my app to wait for next code?

**Comment by DoctorMcKay** [comment]
I could add an argument to the steamGuard event indicating whether or not the code is requested because the last one was wrong.
