### ISSUE TITLE
How do you find the Steam ID for a Steam username?

### ISSUE THREAD

**Issue by PomegranateApps** [DoctorMcKay/node-steam-user#281]
I tried signing up for the forum but the security check seems broken. Is it possible using this to find the steam ID for a steam username that's not signed in? This posts eludes to it but there is no solution.
https://dev.doctormckay.com/topic/2230-how-can-i-fetch-public-steam-info-of-steam-profiles-by-their-steam-id-without-the-users-being-logged-in/

**Comment by DoctorMcKay** [comment]
By username, do you mean account name (what you use to login with), or their Steam persona name?

Actually, either way, I can't think of a way to get a SteamID from a name programmatically.

**Comment by PomegranateApps** [comment]
Thank you for the response! I was able to do it through the Steam Web API.

`http://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?key=APP_KEY&vanityurl=VANITY_NAME`
