### ISSUE TITLE
Cannot use on AWS Lambda

### ISSUE THREAD

**Issue by PomegranateApps** [DoctorMcKay/node-steam-user#282]
I'm trying to use this in a Lambda function on AWS. When I create a SteamUser object I get this error.

`var user = new SteamUser();`

```
{
  "errorType": "TypeError [ERR_INVALID_ARG_TYPE]",
  "errorMessage": "The \"path\" argument must be of type string. Received type undefined",
  "trace": [
    "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type undefined",
    "    at validateString (internal/validators.js:125:11)",
    "    at Object.join (path.js:1147:7)",
    "    at userData (/opt/nodejs/node_modules/appdirectory/lib/appdirectory.js:21:29)",
    "    at AppDirectory._setTemplates (/opt/nodejs/node_modules/appdirectory/lib/appdirectory.js:134:34)",
    "    at new AppDirectory (/opt/nodejs/node_modules/appdirectory/lib/appdirectory.js:129:10)",
    "    at new SteamUser (/opt/nodejs/node_modules/steam-user/index.js:106:34)",
    "    at main (/var/task/index.js:213:13)",
    "    at Runtime.exports.handler (/var/task/index.js:290:18)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

I'm assuming I need to create my own custom storage engine but the error is happening at the constructor so I'm not able to add any custom storage options.
https://github.com/DoctorMcKay/node-steam-user#options-

**Comment by DoctorMcKay** [comment]
Configuring a dataDirectory in your constructor will fix this.

```js
var user = new SteamUser({dataDirectory: '/some/path'}); // or you could use null to disable data storage
```

**Comment by PomegranateApps** [comment]
Thank you for the response! I tried `let user = new SteamUser(null);` but I'm still getting the same error. It works fine on a local machine both ways.

**Comment by PomegranateApps** [comment]
Sorry, I misunderstood your last reply. This gets me past the error but now I'm being prompted for a "Steam Guard Code". I can't input these things through a console in a Lambda function.
`var user = new SteamUser({dataDirectory: null});`

**Comment by DoctorMcKay** [comment]
Please read through the docs a little more thoroughly. You're looking for either the `steamGuard` event, or `authCode` / `twoFactorCode` in the logOn method.

**Comment by PomegranateApps** [comment]
Thank you for the reply! I understand these codes but my understanding is you have to get them from a text or email which isn't practical for a Lambda function.

Can I ask why the module needs to save data to files? I'm only interested in the "logOn" and "getEncryptedAppTicket" functions.

**Comment by DoctorMcKay** [comment]
The primary thing it needs to save to disk is the sentry file. Assuming you're using email-based Steam guard, the sentry file is what it uses to not require a code every time you login.

You have two options here. Either disable Steam Guard, or use the `sentry` event to save a sentry file after logging in with a code and then use `setSentry()` on every login to use that sentry file.

**Comment by Heartz66** [comment]
I would advice you to create a custom data directory that would retrieve and save files from object storage.

**Comment by PomegranateApps** [comment]
Ok, that worked to just disable Steam Guard but now "getEncryptedAppTicket" doesn't give me any data for the ticket. I'm just using this module for that function.

**Comment by DoctorMcKay** [comment]
Please show the code you're trying to use.
