### ISSUE TITLE
BUG: Asks for "Steam Guard" despite using Shared_Secret !

### ISSUE THREAD

**Issue by siparisapp** [DoctorMcKay/node-steam-user#284]
console asks me "Steam Guard:" although I use shared_secret. 

doesn't ask when I start the bot for the first time, but every 30 minutes the bot shuts down and asks? "Steam Guard:"

My logOn Code:

```
const settings = {
	accountName: config.bot.name,
	password: config.bot.pass,
	twoFactorCode: SteamTotp.generateAuthCode(config.bot.shared_secret)
};

client.logOn(settings);
```
And websession code;

```
client.on('webSession', (sessionid, cookies) => {
	manager.setCookies(cookies, function(err) {
		if (err) {
			print(`${auto.log('info')} Err Cookies ${err}`);
                process.exit(1); // Fatal error since we couldn't get our API key
            }

            community.setCookies(cookies);
            community.startConfirmationChecker(30000, config.bot.identity_secret);

        }); 
});

setInterval(function() {
	if (client.steamID) {
		client.webLogOn();
	} else {
		client.logOn(settings);
		console.log("Again Re-Log");
	}
}, 1800000); //30Min.
```

Somebody please help me I'm going crazy I've been trying for weeks!  i could not find a solution. maybe, this is a bug?

**Comment by Ne3tCode** [comment]
You have to set new `settings.twoFactorCode` every time you log on.
#notabug

**Comment by siparisapp** [comment]
> You have to set new `settings.twoFactorCode` every time you log on.
> #notabug

Can you give an example I do not understand what you mean? I'm not a js expert

**Comment by Ne3tCode** [comment]
```javascript
setInterval(function() {
	if (client.steamID) {
		client.webLogOn();
	} else {
		settings.twoFactorCode = SteamTotp.generateAuthCode(config.bot.shared_secret); // <--
		client.logOn(settings);
		console.log("Again Re-Log");
	}
}, 1800000);
```

**Comment by siparisapp** [comment]
> ```js
> setInterval(function() {
> 	if (client.steamID) {
> 		client.webLogOn();
> 	} else {
> 		settings.twoFactorCode = SteamTotp.generateAuthCode(config.bot.shared_secret); // <--
> 		client.logOn(settings);
> 		console.log("Again Re-Log");
> 	}
> }, 1800000);
> ```



> ```diff
> setInterval(function() {
> 	if (client.steamID) {
> 		client.webLogOn();
> 	} else {
> +		settings.twoFactorCode = SteamTotp.generateAuthCode(config.bot.shared_secret);
> 		client.logOn(settings);
> 		console.log("Again Re-Log");
> 	}
> }, 1800000);
> ```

I'll try it, but do you think "twoFactorCode" is a need to write a second value, already assigned a value to "settings" const?

**Comment by DoctorMcKay** [comment]
Not a bug.

Yes, you do need to re-set it every time you log on. You can't just keep using the same code.

**Comment by siparisapp** [comment]
> Not a bug.
> 
> Yes, you do need to re-set it every time you log on. You can't just keep using the same code. That would kinda defeat the point.

Hi, tried trying as you say but the bot is going offline

New Code ;

```
setInterval(function() {
	if (client.steamID) {
		client.webLogOn();
	} else {
		settings.twoFactorCode = SteamTotp.generateAuthCode(config.bot.shared_secret);
		client.logOn(settings);
		console.log("Again Re-Log");
	}
}, 1800000);
```
this works but the bot is offline, I'm about to go crazy, I've looked at all the codes in detail again, but there's no problem please help

**Comment by Ne3tCode** [comment]
1. RTFM
2. get it [online](https://github.com/DoctorMcKay/node-steam-user/blob/master/README.md#setpersonastate-name)
3. learn to debug
4. ask questions on the [forum](https://dev.doctormckay.com/forum/7-node-steam-user/)

**Comment by siparisapp** [comment]
First of all, be careful with your speech;

1- I haven't asked you this question, I've been looking for solutions for weeks, sharing my problem with people, and asking people who are developers, but it's not clear.
2- I know what debug is, but I can't get a useful output.
3- I shared the question from the forum, but I have not yet received a clear answer because there are not as many active users as github.

I hope these are enough for you. Because you don't know what I've been doing for weeks.I don't like to ask people questions without researching the solution of the problem.

And I never use the library without reading the readme section. Thank you.

**Comment by DoctorMcKay** [comment]
Since this is not a bug in the module, this needs to go to the forum.
