### ISSUE TITLE
getAliases method doesn't return current name if list is cleared

### ISSUE THREAD

**Issue by DAmNRelentless** [DoctorMcKay/node-steam-user#287]
## Describe the bug
If you want to get the name of a steam user by his/her Steam-ID, you should normally get back a list with all of his/her previously used Aliases. However if the user cleared his/her list and no aliases are available, the current name isn't returned as well. I think the method should still return the current name even if the alias list is cleared. Maybe by converting the SteamID to the name or something.

## Versions
steam-user: 4.12.5
node.js: 13.8.0
JS: ECMA 2019
VSCode: 1.42.0

## Screenshots and Error Logs
You can see the code and the result in this screenshot:
https://i.imgur.com/HFMIdfZ.png

**Comment by DoctorMcKay** [comment]
If you want the user's current name, you should use getPersonas for that. You shouldn't be using getAliases to get their current name.

**Comment by DAmNRelentless** [comment]
I'll give that a try. However I think getAliases should return the current name if the list was cleared tho.

**Comment by DoctorMcKay** [comment]
I'm going to close this because the fact that the current name is also returned from Steam along with aliases is not necessarily guaranteed and may change in the future.
