### ISSUE TITLE
User is Offline

### ISSUE THREAD

**Issue by Jaeger33211Sec** [DoctorMcKay/node-steam-user#288]
## Describe the bug

I call: user.getAuthSessionTicket after i set gamesPlayed to 730 and EPersonaState to online, then i parse the ticket and send it to verify.
The response from steam is everytime:
Errorcode: 100
Errordesc: User is offline

## Versions
What version of the module and what version of Node.js are you using?
13.2.0 (also tested on: 11.9.0)
## Screenshots and Error Logs
If applicable, add screenshots and error logs to help explain your problem.

**Comment by DoctorMcKay** [comment]
Where are you sending the ticket?

**Comment by Jaeger33211Sec** [comment]
> Where are you sending the ticket?

Might sound stupid, But i send it to:
https://api.steampowered.com/ISteamUserAuth/AuthenticateUserTicket/v1/?key=******&appid=730&ticket=*****

**Comment by DoctorMcKay** [comment]
Not stupid, that should work. Bug is fixed in [v4.12.6](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.12.6).
