### ISSUE TITLE
 How to change nickname

### ISSUE THREAD

**Issue by Madaspe** [DoctorMcKay/node-steam-user#294]
not work
```
client.setNickname(details.steamID, 'NICKNAME').then(r => {
            console.log(r)
        })
```
not work
```
        client.setNickname(client.steamID, 'NICKNAME').then(r => {
            console.log(r)
        })
```
not work
```
        client.setNickname(client.steamID.accountID, 'NICKNAME').then(r => {
            console.log(r)
        })
```

**Comment by Madaspe** [comment]
Please help

**Comment by DoctorMcKay** [comment]
Are you getting an error?

**Comment by Madaspe** [comment]
Yes, i have `UnhandledPromiseRejectionWarning: Error: InvalidSteamID` or `UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object`


I want to change my nickname in Steam

**Comment by Madaspe** [comment]
I have` UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object`
when i use
```
        client.setNickname(client.steamID.accountID, 'NICKNAME').then(r => {
            console.log(r)
        })
```

**Comment by DoctorMcKay** [comment]
I would assume that you can't nickname your own account.

If you're trying to change your profile name, use `setPersona()` for that.
