### ISSUE TITLE
the bot I created is not online

### ISSUE THREAD

**Issue by gunduz1905** [DoctorMcKay/node-steam-user#300]
the bot I created is not online

looks offline

but it works
what should i do to be online

urgent

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

You probably need to add `user.setPersona(SteamUser.EPersonaState.Online)` to your loggedOn event listener.
