### ISSUE TITLE
Steam-Rep-Bot problem

### ISSUE THREAD

**Issue by ovykun1121** [DoctorMcKay/node-steam-user#303]
Hello!
I tried the +Rep bot by agasking1337 (https://github.com/agasking1337/steam-auto-comment) but when I try to actually start it (node index.js), the only message displayed is "Logged In!", and nothing else after.

Notice that since the NotePad file was outdated I modified it myself by replacing SteamUser.Steam.EPersonaState with SteamUser.EPersonaState.

**Comment by andrewda** [comment]
This is not relevant to `node-steam-user` -- ask at the [repository in question](https://github.com/agasking1337/steam-auto-comment/issues). If you create an issue there, @ me and I can try to help you through any issues you have.
