### ISSUE TITLE
addFriend hangs

### ISSUE THREAD

**Issue by Markovnin** [DoctorMcKay/node-steam-user#307]
Sometimes I see that addFriend method does not call the callback at all.

My app hanged in this state waiting a response for more than 5 mins until I killed it.

What might be problem? Does it fire a callback if Steam does not respond, or returns and error?

**Comment by DoctorMcKay** [comment]
In the majority of cases (pretty much everything except new-chat requests), if Steam has an error processing the request, it just doesn't respond. At the moment, the module doesn't have any mechanism to timeout a request that never gets responded to.

I've been meaning to add it... I'll see when I can find the time.
