### ISSUE TITLE
logOn() without an internet connection results in great CPU usage

### ISSUE THREAD

**Issue by HerrEurobeat** [DoctorMcKay/node-steam-user#317]
Not a gamebraking bug but something I wanted to let you know. (enhancement label could be added)

## Describe the bug
Calling `new SteamUser().logOn()` while having no internet connection results in the node process using a great amount of the CPU.

Situation on my Thinkpad T430 (Ubuntu):
Successful login: CPU 0-1%, 42°C Temperature
Without internet: CPU 36%, 58°C Temperature

Situation on Ryzen 5 2600 (Windows 10):
RAM usage shoots up to ~280 MB (normal ~80 MB)
CPU usage goes up from ~1% to ~17%

## Versions
What version of the module and what version of Node.js are you using?
Node: `v12.17.0`
steam-user: `4.16.1`
OS: `Ubuntu 18.04.4 LTS x86_64`
OS: `Win10 Version 1903 Build 18362.836`

## Idea for a solution
If pinging Steam before trying to log in results in a no connection error then throw an error or make a callback that can be catched with `logOn(options, (err) => { if (err) console.log(err) })` instead of trying to log in even though this fails all the time.

And thank you so far for creating steam-user and steamcommunity, haven't had any problems so far with my `steam-comment-service-bot` project, which isn't the smallest project anymore ^^

**Comment by DoctorMcKay** [comment]
I don't want to change the auto-reconnect behavior since that may break some people's stuff, but I can add a 1-second delay between connection attempts. That should cut down on the crazy CPU usage when attempting to connect without Internet.
