### ISSUE TITLE
getProductInfo inclTokens

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#318]
I'm setting `inclTokens` parameter to `true`
![image](https://user-images.githubusercontent.com/4411977/85189608-c6f2a380-b2b0-11ea-8d70-cc74dfdaca12.png)

However, I'm still getting packages with `missingToken` is `true` as response
![image](https://user-images.githubusercontent.com/4411977/85189624-ea1d5300-b2b0-11ea-8cb0-bbf0a41ab63c.png)

Could you please fix this?

**Comment by Ne3tCode** [comment]
Steam does not return pics token for packages anymore. Get it from [`licenses`](https://github.com/SteamDatabase/Protobufs/blob/f6e91fd80e618c83a7d30e377a6ecfe33f493959/steam/steammessages_clientserver.proto#L231) list and include in a request manually.

**Comment by Revadike** [comment]
> Steam does not return pics token for packages anymore. Get it from [`licenses`](https://github.com/SteamDatabase/Protobufs/blob/f6e91fd80e618c83a7d30e377a6ecfe33f493959/steam/steammessages_clientserver.proto#L231) list and include in a request manually.

I know I can do it manually, but the `inclTokens` boolean should do it automatically for me
