### ISSUE TITLE
Steam Guard App Code required when logging in frequently

### ISSUE THREAD

**Issue by timavo** [DoctorMcKay/node-steam-user#32]
Hi, 

when I login and logout frequently (eg. login, logout and instantly login again), the console is asking for a `Steam Guard App Code`. 

The code I am using:

```
var SteamUser = require('steam-user');
var SteamTotp = require('steam-totp'); 

var client = new SteamUser();

client.logOn({
    accountName: 'username',
    password: 'password',
    twoFactorCode: SteamTotp.generateAuthCode('my_shared_secret')
});
```

So generally this is working, but not if I am logging in and out frequently. 

I also tried with:

```
var client = new SteamUser({
    promptSteamGuardCode: false
});

client.on('steamGuard', function (domain, callback) {
    console.log("Steam Guard code needed from " + (domain ? "email ending in " + domain : "app") + ".");
    var code = SteamTotp.generateAuthCode('my_shared_secret')
    callback(code);
});
```

But this doesn't work. The code seems to be wrong... 

Any help is very much appreciated.

**Comment by Ne3tCode** [comment]
New Auth-Code generates every 30 seconds. You can not use the same code twice "by design". You'd better need to use [`login_key`](https://github.com/DoctorMcKay/node-steam-user/blob/master/README.md#loginkey) for re-login.

**Comment by timavo** [comment]
Thanks for the fast reply! :)
