### ISSUE TITLE
Add method for confirm change password with steam guard

### ISSUE THREAD

**Issue by gespispace** [DoctorMcKay/node-steam-user#321]
## Is your feature request related to a problem? Please describe.
I want change password steam account, but don't see method for this.

## Describe the solution you'd like
Method for confirm change password. 

## Describe alternatives you've considered
I thought about change with confirm email and sms code, but for this I should remove steam guard and get trade ban on 15 day. 

## Additional context
I don't have steam mobile guard, I have only identitySecret, sharedSecret, botName, password. That's why I can not change password the usual way.

**Comment by DoctorMcKay** [comment]
Changing your password is done through the help site, which is outside the scope of steam-user. You can use [steam-totp](https://github.com/DoctorMcKay/node-steam-totp) to get a code from your shared_secret.

**Comment by gespispace** [comment]
@DoctorMcKay Okay, but how i confirm change password? Password change must be confirmed in steam guard app. Isn't that part of the steam-user?

**Comment by DoctorMcKay** [comment]
They switched to an in-app confirmation? That would be [steamcommunity](https://github.com/DoctorMcKay/node-steamcommunity)'s job.

**Comment by gespispace** [comment]
@DoctorMcKay I should add issue in steamcommunity?

**Comment by gespispace** [comment]
I tried add method for change, but i can't see http request steam guard. 
I installed [Fiddler](https://www.telerik.com/fiddler), but http request don't saw. 
These requests were encrypt, after add user cert in android, requests anyway were encrypt. 
What tools do you use to watch http requests?

**Comment by DoctorMcKay** [comment]
Do the normal confirmations methods not work?

**Comment by gespispace** [comment]
What does normal confirmation methods mean?
You can confirm the change only through Steam Guard in the application, or through mail and SMS, but then you need to remove Steam Guard and install it again after receiving a trade block for 15 days.

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#getconfirmationstime-key-callback

**Comment by gespispace** [comment]
@DoctorMcKay Thank you so much, it works. But for me it is very difficult to understand how it works.
