### ISSUE TITLE
How to use enableTwoFactor method ?

### ISSUE THREAD

**Issue by MertDemirok** [DoctorMcKay/node-steam-user#324]
https://github.com/DoctorMcKay/node-steam-user/blob/79e3fc2fb5ec0be6a26a2c076479dd9876a26f75/components/twofactor.js#L11

I can't use enableTwoFactor method. I need shared_secret code so I want to use enableTwoFactor  response

**Comment by DoctorMcKay** [comment]
Read the docs.
