### ISSUE TITLE
Another "Cannot read property 'setTimeout' of undefined" crash when Steam goes down

### ISSUE THREAD

**Issue by itsjfx** [DoctorMcKay/node-steam-user#325]
## Describe the bug
When Steam went down at midnight Aug 4 2020 another crash exception occurred in the `connection.js` file similar to https://github.com/DoctorMcKay/node-steam-user/issues/274 - but instead of occurring in `ChannelEncryptRequest` it happens in `ChannelEncryptResult`. 

## Versions
What version of the module and what version of Node.js are you using?
Node.js: v12.16.1
node-steam-user: 4.17.1

## Screenshots and Error Logs
If applicable, add screenshots and error logs to help explain your problem.

From what I can see, Steam went down and the bots called logOn a few minutes earlier before crashing. I have a feeling I get these crashes because my bots are re-logging into Steam (this is with an interval and timeout however). Nonetheless this isn't a great exception to have possible in the module.

```
2020-08-04T23:20:25.567Z [app.js] ERROR uncaughtException: Cannot read property 'setTimeout' of undefined
TypeError: Cannot read property 'setTimeout' of undefined
    at SteamUser.<anonymous> (/app/node_modules/steam-user/components/connection.js:54:26)
    at /app/node_modules/steam-user/components/classes/HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (/app/node_modules/steam-user/components/classes/HandlerManager.js:36:12)
    at SteamUser._handleMessage (/app/node_modules/steam-user/components/messages.js:569:24)
    at SteamUser._handleNetMessage (/app/node_modules/steam-user/components/messages.js:504:7)
    at TCPConnection._readMessage (/app/node_modules/steam-user/components/connection_protocols/tcp.js:193:12)
    at Socket.emit (events.js:311:20)
    at emitReadable_ (_stream_readable.js:562:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

I suppose the solution could again be the fix used before where it will not continue handling this message unless a socket is available. I'm going to continue trying to debug why this crash occurred, but if I don't have any luck I'll submit a PR with the same return logic as before.

**Comment by VaibhavBarot** [comment]
Hi did you find any solution? I got the same exception today. 
![error2](https://user-images.githubusercontent.com/21966185/93967169-38486380-fd84-11ea-8ac4-09017cbca1f1.png)

**Comment by itsjfx** [comment]
Nope, did you write functionality to your bot to relog itself back based on events like SessionExpired etc? I'm thinking it may be because of that.

**Comment by VaibhavBarot** [comment]
> Nope, did you write functionality to your bot to relog itself back based on events like SessionExpired/error etc? I'm thinking it may be because of that.

Yes, 
![logon](https://user-images.githubusercontent.com/21966185/93967478-ed7b1b80-fd84-11ea-9f44-1cd9ea54cbf6.PNG)

**Comment by DoctorMcKay** [comment]
I think what might be happening is Steam goes down, steam-user disconnects, steamcommunity therefore has its session expire, and your code to call logOn gets executed. But steam-user is already internally trying to reconnect, so things get out of sorts.

You shouldn't ever need to call logOn again unless you specifically get an `error` event.

**Comment by itsjfx** [comment]
> I think what might be happening is Steam goes down, steam-user disconnects, steamcommunity therefore has its session expire, and your code to call logOn gets executed. But steam-user is already internally trying to reconnect, so things get out of sorts.
> 
> You shouldn't ever need to call logOn again unless you specifically get an `error` event.

Yep I was just about to comment this lol. Alternatively you could also disable auto relogging and implement it yourself if you'd prefer to do that.

**Comment by VaibhavBarot** [comment]
Ok, thanks you mean like this?
![dix](https://user-images.githubusercontent.com/21966185/94006114-fdaeed00-fdbc-11ea-8f6c-87d9f12ebf9c.PNG)

**Comment by itsjfx** [comment]
I believe he's referring to this event called in node-steam-user: https://github.com/DoctorMcKay/node-steam-user#error

**Comment by VaibhavBarot** [comment]
Alright, thanks I will try your approach

**Comment by DoctorMcKay** [comment]
> I believe he's referring to this event called in node-steam-user: https://github.com/DoctorMcKay/node-steam-user#error
> 
> I think only call webLogon in sessionExpired IF client.steamID is defined - otherwise do nothing else there.
> And then in the error event in node-steam-user (the one linked above) login again if that event runs.
> 
> You should assume that if your web session expires and node-steam-user is logged out it is already trying to log back in (unless error event runs).
> 
> These are my assumptions but I believe they are correct.

I realize this is a very late response, but your assumptions are correct.
