### ISSUE TITLE
.getPersonas retrieves mostly null, including the user Persona

### ISSUE THREAD

**Issue by Harmonised7** [DoctorMcKay/node-steam-user#326]
## Describe the bug
calling .getPersonas only retrieves a few of the values as non-null, the rest are null.

## Versions
Module: 4.17.1
Node: v10.16.0

## Screenshots and Error Logs
`rich_presence: 

persona_state: null

game_played_app_id: null

game_server_ip: null

game_server_port: null

persona_state_flags: null

online_session_instances: null

persona_set_by_user: null

player_name: Blackjack

query_port: null

steamid_source: null

avatar_hash: 6�vm^��6���9=J�p

last_logoff: Sun Aug 16 2020 10:17:41 GMT+0200 (Central European Summer Time)

last_logon: Sun Aug 16 2020 10:06:40 GMT+0200 (Central European Summer Time)

last_seen_online: Sun Aug 16 2020 10:17:41 GMT+0200 (Central European Summer Time)

clan_rank: null

game_name: null

gameid: null

game_data_blob: null

clan_data: null

clan_tag: null

broadcast_id: null

game_lobby_id: null

watching_broadcast_accountid: null

watching_broadcast_appid: null

watching_broadcast_viewers: null

watching_broadcast_title: null

avatar_url_icon: https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/36/36ed9a766d1b5e8e9f369395ca390f3d074ae070.jpg

avatar_url_medium: https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/36/36ed9a766d1b5e8e9f369395ca390f3d074ae070_medium.jpg

avatar_url_full: https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/36/36ed9a766d1b5e8e9f369395ca390f3d074ae070_full.jpg`

**Comment by DoctorMcKay** [comment]
Not a bug, that's the only data Steam decided you're able to see.
