### ISSUE TITLE
My bot is not accepting Gifts , It just stays logged In

### ISSUE THREAD

**Issue by lordswift** [DoctorMcKay/node-steam-user#329]
My code for main javascript file is : 
```
//modules required
const SteamUser= require('steam-user'); //module for steam api
const SteamTotp= require('steam-totp'); //module for auth code automation
const SteamCommunity =require('steamcommunity'); //module for steam community
const TradeOfferManager =require('steam-tradeoffer-manager'); //module for steam trades

const config= require('./config.json');//reads config file
//const prices= require('./prices.json');//reads prices file

//objects required
const client=new SteamUser();          
const community= new SteamCommunity(); 
const manager=new TradeOfferManager({
	steam: client,
	community: community,
	language: 'en'
});

//options
client.setOption("promtSteamGuardCode",false);


//imports login details
const logOnOptions = {
	accountName: config.username,
	password: config.password,
	twoFactorCode: SteamTotp.generateAuthCode(config.shared_secret)
}

//Post-login functions
client.logOn(logOnOptions);
client.on('loggedOn',() => {
	console.log('Login Succesfull');
	client.setPersona(SteamUser.EPersonaState.Online);
	client.gamesPlayed("Just message!!");
});

//Trade offers Accept and Declines 
manager.on('newOffer', offer => {
  if (offer.itemsToGive.length === 0) {
    offer.accept((err, status) => {
      if (err) {
        console.log(err);
      } else {
        console.log(`Donation accepted. Status: ${status}.`);
      }
    });
  } else {
    offer.decline(err => {
      if (err) {
        console.log(err);
      } else {
        console.log('Donation declined (wanted our items).');
      }
    });
  }
});

//web session for steam community
client.on('webSession',(sessionid,cookies) => {
	manager.setCookies(cookies);
	community.setCookies(cookies);
	community.startConfirmationChecker(10000, config.identity_secret);
});

//accepting friend requests
client.on('friendRelationship', (steamid, relationship) => {
  if (relationship === 2) {
    client.addFriend(steamid);
  }
});

```

**Comment by lordswift** [comment]
I tried sending offers from different account and it doesnt accept them even though my javascript is open.
But it logs in successfully and changes steam status

**Comment by DoctorMcKay** [comment]
First, don't use the confirmation checker.

Second, add a callback to manager.setCookies and see if you get an error.

**Comment by lordswift** [comment]
okay thanks

> First, don't use the confirmation checker.
> 
> Second, add a callback to manager.setCookies and see if you get an error.

i am weak with js , can u suggest how to add callback 
probably which part of code i need to change

**Comment by DoctorMcKay** [comment]
```js
manager.setCookies(cookies, (err) => {
    if (err) {
        console.log(err);
    } else {
        console.log('Manager cookies set successfully');
    }
});

**Comment by lordswift** [comment]
> ```js
> manager.setCookies(cookies, (err) => {
>     if (err) {
>         console.log(err);
>     } else {
>         console.log('Manager cookies set successfully');
>     }
> });
> ```

Bot logged on, listening for trade offers!
Error: Access Denied
    at SteamCommunity.<anonymous> (D:\@SOFTWARES\Steam bot using node\Projects\Steam Gift Accepting Bot\node_modules\steamcommunity\components\webapi.js:15:20)
    at Request._callback (D:\@SOFTWARES\Steam bot using node\Projects\Steam Gift Accepting Bot\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (D:\@SOFTWARES\Steam bot using node\Projects\Steam Gift Accepting Bot\node_modules\request\request.js:186:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (D:\@SOFTWARES\Steam bot using node\Projects\Steam Gift Accepting Bot\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (D:\@SOFTWARES\Steam bot using node\Projects\Steam Gift Accepting Bot\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)

**THIS IS ERROR AFTER RUNNING , I CHANGED AS YOU SAID**

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#setcookiescookies-familyviewpin-callback
