### ISSUE TITLE
How to obtain a sentryFile?

### ISSUE THREAD

**Issue by panp858** [DoctorMcKay/node-steam-user#33]
Hello!

I needed to update the sw because of a lot of changes recently. When I login for the first time I'm forced to insert the steam guard code. For the node-steam you get a callback when the login is correct with the new sentryFile which you can store elsewhere. Is this possible here too?

**Comment by Jallvar** [comment]
client.on('sentry',function(sentryHash) {
  require('fs').writeFile('sentry.hash',sentryHash,function(err) {
    if(err){
      console.log(err);
    } else {
      console.log('Saved sentry file hash as "sentryfile"');
    }
  });

**Comment by DoctorMcKay** [comment]
SteamUser saves it and reuses it automatically from the disk.

If you want to save it yourself, see [here](https://github.com/DoctorMcKay/node-steam-user#sentry).
