### ISSUE TITLE
Incorrect type 'function' provided for option clone

### ISSUE THREAD

**Issue by catalizcs** [DoctorMcKay/node-steam-user#331]
## Describe the bug
when i start my server and take "Incorrect type 'function' provided for option clone"

## Versions
im using 12.0.0

## Screenshots and Error Logs

![BC8A9A81-2029-4159-9078-6E0D80A2D7CD](https://user-images.githubusercontent.com/36947924/95608131-e5122880-0a86-11eb-90fb-4491ebc459e1.jpeg)
![A0348E2D-DB27-4771-9A00-30534A34AE79](https://user-images.githubusercontent.com/36947924/95608746-c82a2500-0a87-11eb-8964-404b4675b51c.jpeg)

**Comment by DoctorMcKay** [comment]
It looks like you've done something that's poisoned the master Object prototype with additional methods (extend and clone). That environment is not supported.
