### ISSUE TITLE
Friendmessage Event not triggering from Mobile

### ISSUE THREAD

**Issue by piman51277** [DoctorMcKay/node-steam-user#332]
The `friendMessage` event does not trigger for messages coming from the mobile Steam App.
It functions normally for messages coming from Desktop.

This broke very recently, and might have to do with the recent Steam Friends update.

## Versions
steam-user v4.18.0
node v12.18.3

**Comment by DoctorMcKay** [comment]
Can you please show the code for your event listener?

**Comment by piman51277** [comment]
```
this.client = new SteamUser();
const loginCredentials = {
            accountName: <username>,
            password: <password>,
            twoFactorCode: SteamTotp.generateAuthCode(<sharedSecret>),
            autoRelogin: true,
            machineName: "PiBot"
        }
this.client.logOn(loginCredentials);
this.client.on('friendMessage', (steamID, msg) => {
            this.processCommands(steamID, msg)//msg parsing/processing function
        })

```

**Comment by piman51277** [comment]
The friendMessage event listener is only added after the loggedOn event

**Comment by DoctorMcKay** [comment]
Please try using the [new Steam chat version](https://github.com/DoctorMcKay/node-steam-user/wiki/SteamChatRoomClient#friendmessage). It would be `this.client.chat.on('friendMessage', (message) => {})`

**Comment by piman51277** [comment]
The error persists. It exhibits the same behavior as before.

**Comment by piman51277** [comment]
The error has stopped occurring. This might have been a problem with Steam.
