### ISSUE TITLE
Node Js SteamUser is not a constructer or SteamUser is not a Function Error

### ISSUE THREAD

**Issue by tibitipi** [DoctorMcKay/node-steam-user#336]
Hi. In my code I'm trying to make a basic steam chat bot which accept all friend request and answer basic questitions.

Bot when i write this code [https://imgur.com/a/zOr7VfY](url) Getting this error. What i need to do ?
`
var config =require("./config.json");
var SteamUser=require("steam-user");
var SteamUser=require("steam-totp");

var client = new SteamUser();

client.on('LoggedOn',() => {

	console.log("success");

});

client.on('friendRelationship',() => {

	if(relationship == 2){
	console.log("new friend added");
	client.addFriend(steamId);
	}

});

client.on("friendMessage",function(steamId,message){
	console.log("an object came " + steamId +":"+ message);

	if(message.toLowerCase()=="ping"){

		client.chatMessage(steamId,"pong");
		console.log("someone sent smt");

		}

	if(message.toLowerCase()=="hi"){

		client.chatMessage(steamId,"hi");
		console.log("we sent smt");

		}

	if(message.toLowerCase().includes("cs")){

		client.chatMessage(steamId,"busy");

	}

});

	client.LogOn({

		accountName:config.username,
		password:config.password,
		twoFactorCode:SteamTotp.generateAuthCode(config.shared_secret)

	});

`

**Comment by DoctorMcKay** [comment]
You've imported steam-totp as `SteamUser`, overwriting the actual steam-user import.
