### ISSUE TITLE
Improve requestFreeLicense

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#339]
## Is your feature request related to a problem? Please describe.
Nowadays `requestFreeLicense` is rate limited by Steam. We know this rate limit too. It is 50 requests per hour.

## Describe the solution you'd like
Add a flag/bool to consider this rate limit, by queuing the input if it's over 50 appids. Or do this by default. A user can provide an array of appids as input after all.

## Describe alternatives you've considered
You can implement this yourself, but it would be real handy to have this logic handled by the library. 

## Additional context
Considering the goal of this library to make the Steam interface easy to use in node.js, I'm suggesting to add this convenient feature.

**Comment by DoctorMcKay** [comment]
Hm... I don't like the thought of a queue that delays a request by an hour or even more. Plus that would be a breaking change considering the fact that `requestFreeLicense` has a callback.

**Comment by Revadike** [comment]
Yes, the callback may take hours to fire. Or you have a callback for each appid request.

**Comment by DoctorMcKay** [comment]
I'm going to close this. This really seems like something user-space code should be doing, especially since the module can't guarantee that it'll even still be running in an hour when it's time to try the next request.

I will add a note to the docs about this rate-limit.
