### ISSUE TITLE
Function to set the vanityURL property on the user

### ISSUE THREAD

**Issue by itseramin** [DoctorMcKay/node-steam-user#343]
## Is your feature request related to a problem? Please describe.
I can listen for change on the vanityURL and can access it, but I'm not able to change it.

## Describe the solution you'd like.
An easy function to change the vanityURL. Ex.: client.setVanityURL('newurl');

**Comment by DoctorMcKay** [comment]
It's not possible to change your vanity URL through the client protocol.

You can do this with node-steamcommunity: https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#editprofilesettings-callback
