### ISSUE TITLE
Having issue with bot.uploadRichPresence()

### ISSUE THREAD

**Issue by VaasKahnGrim** [DoctorMcKay/node-steam-user#347]
So when using the function, its setting most of the data correctly, except for the connect portion. When clicking Join Game on the bots steam profile its for some reason notconnecting to the server. infact in chrome its showing the link as steam:// instead of steam://connect/IP:PORT

this is what I'm currently putting into the rich presence at the moment(some data has been changed, however this is the exact format. The IP shown there is changed from my VPS IP to a local IP just for this issue being opened)

```
bot.uploadRichPresence(4000,{
	"status": "Join text message here",
	"gamemode": "sandbox",
	"map": "gm_construct",
	"multi": "Community name here",
	"game:state": "Multiplayer",
	"steam_display": "#status_playing",
	"connect": "192.168.0.2:27015"
})
```

current version of both NodeJS and the module being used

No errors are popping up in the console, just when I go the the bots profile and click Join Game it doesn't seem to be able to connect to the game server

**Comment by DoctorMcKay** [comment]
I'll need to test this to be 100% sure, but I'm pretty sure that the connect key in RP doesn't control the join game button on your profile. Rather, I think you need to actually join a game server with an appticket, which isn't really doable with steam-user.
