### ISSUE TITLE
Broken-but-continuing state possible after droppage of client param in 3f73fcec

### ISSUE THREAD

**Issue by Lagg** [DoctorMcKay/node-steam-user#349]
Not sure if I'm a rare user affected by this due to my stability reqs spanning into the years, but I wanted to drop a quick note that anyone who didn't catch the removal of the client param in the commit above (presumably replaced by httpProxy going by publicIP) will get weird silently failing behavior due to the options param being passed second. Example in my case being a schrodinger's data dir and somehow managing to auth but none of the web stuff working.

If the user doesn't do an explicit check on publicIP for proxy presence this could present a data leak and odd backwards behavior.

Beyond that though, neat cleanups. Literally years and my porting footprint was 18 lines. :D

## Versions
All after commit in subject

**Comment by Lagg** [comment]
I'd recommend just noting in the ctor section that after `[release following that commit]` this arg was removed. I scanned the README to check that I didn't miss any breaking changes and likely would have noticed an advisory similar to your **vX.Y.Z or later** ones

**Comment by DoctorMcKay** [comment]
The full list of breaking changes is noted in the [v4 release notes](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.0.0).
