### ISSUE TITLE
Steam Guard App Code: Unhandled message: 1

### ISSUE THREAD

**Issue by Jallvar** [DoctorMcKay/node-steam-user#35]
Steam return: Steam Guard App Code: Unhandled message: 1
1. I got a file Steam Guard-76561198...252743 from mobile-app.
2. i took code (shared_secret(S..iW)steamid)

mycode:
var SteamTotp = require('steam-totp');
var SteamUser = require('steam-user');
var client = new SteamUser();
client.on('debug', console.log);
var code = SteamTotp.generateAuthCode('S..iW');
var logOnOptions = {
accountName: ...,
password: ...,
twoFactorCode: code
};
client.logOn(logOnOptions);
Please tell me, what did not

**Comment by DoctorMcKay** [comment]
Your code is wrong. 

Assuming S..iW is your secret with characters cut out, that doesn't look right. It should end with a =.

**Comment by Jallvar** [comment]
file and it looks

**Comment by DoctorMcKay** [comment]
What?

**Comment by Jallvar** [comment]
Sorry for my English.
I use this script to generate a key.
I leave to others.
https://github.com/bulgakovk/steamBot/blob/7ca69cedb86477567a1a292b2b6aea9c3d6344cd/2FA.js

**Comment by andrewda** [comment]
That script has nothing to do with node-steam-user

**Comment by Jallvar** [comment]
I used it to generate shared_code

**Comment by DoctorMcKay** [comment]
Again, make sure you're providing the *entire* shared_secret to generateAuthCode.

**Comment by Jallvar** [comment]
Yes, came the received code and the codes work.
thank you
