### ISSUE TITLE
SsteamGuard Loop ?

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steam-user#353]
## Describe the bug
module sends a lot of SteamGuard code requests, and it make it trigger the 'RateLimitExceeded'

## Versions
Latest

## Screenshots and Error Logs
![image](https://user-images.githubusercontent.com/30638036/118188413-baba8c00-b416-11eb-91c7-cfe19150a029.png)

**Comment by DoctorMcKay** [comment]
I suspect that you aren't checking the `lastCodeWrong` argument in the `steamGuard` event. If it's true, that means the last code you provided was wrong, and you need to wait 30 seconds for a new code.

**Comment by JustAzul** [comment]
thanks, will do that
