### ISSUE TITLE
Get null on getOwnedApps

### ISSUE THREAD

**Issue by PdA1337** [DoctorMcKay/node-steam-user#354]
client.on('loggedOn', (details) => {
    console.log("Logged into Steam as " + client.steamID.getSteam3RenderedID());
    client.setPersona(SteamUser.EPersonaState.Online);
    client.getOwnedApps();
});
I can see the log"Logged into Steam as [a:1:237480254]".
But it returned null

**Comment by DoctorMcKay** [comment]
Per the docs, `getOwnedApps` cannot be used unless the `enablePicsCache` option is set to true, and not before `appOwnershipCached` is emitted.

**Comment by PdA1337** [comment]
> 根据文档，`getOwnedApps`除非将`enablePicsCache`选项设置为true，否则不能使用它，除非`appOwnershipCached`发出此选项。
var client = new SteamUser({ "enablePicsCache": true });
i set it to true yet

**Comment by DoctorMcKay** [comment]
You also need to wait for `appOwnershipCached`. Using `getOwnedApps` inside of the `loggedOn` event is too early.
