### ISSUE TITLE
net message from ghost connection

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steam-user#355]
## Describe the bug
image explains everything

## Versions
v4.19.7

## Screenshots and Error Logs
![image](https://user-images.githubusercontent.com/30638036/118415561-594a2580-b681-11eb-806f-9cb26bb21908.png)

**Comment by DoctorMcKay** [comment]
Can I get the entire output please? Or at least don't cut off the warning you're reporting about.

**Comment by JustAzul** [comment]
Warning: Received net message from ghost connection W3 (expected W10)

**Comment by JustAzul** [comment]
![image](https://user-images.githubusercontent.com/30638036/118576372-c4b5f500-b75e-11eb-84d5-e6980bf20c0f.png)

this happends a lot since your rewrite

**Comment by DoctorMcKay** [comment]
What caused disconnection in the first place?
