### ISSUE TITLE
getSteamGuardDetails() returned a wrong result

### ISSUE THREAD

**Issue by PdA1337** [DoctorMcKay/node-steam-user#356]
client.on('loggedOn', function (details) {
    console.log("Login Success.");
    client.setPersona(SteamUser.EPersonaState.Online);
    client.getOwnedApps();
    client.getSteamGuardDetails().then(function callback(callback) {
        //err, isSteamGuardEnabled, timestampSteamGuardEnabled, timestampMachineSteamGuardEnabled, canTrade, timestampTwoFactorEnabled, isPhoneVerified
        console.log(callback);
    })
});

returned
{
  canTrade: false,
  isSteamGuardEnabled: false,
  timestampSteamGuardEnabled: null,
  timestampMachineSteamGuardEnabled: null,
  isTwoFactorEnabled: false,
  timestampTwoFactorEnabled: null,
  isPhoneVerified: false
}
but this account has been VerifiedPhone and Opened 2f

**Comment by DoctorMcKay** [comment]
You've logged on anonymously, not to your own user account.
