### ISSUE TITLE
Release as GitHub package

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#360]
You can release this library both as npm and github package. Having it on both repositories is beneficial for everyone. Also, it allows you to easily see which public projects on github uses this library.

**Comment by DoctorMcKay** [comment]
https://dev.to/joeattardi/how-to-publish-an-npm-package-to-npm-and-github-package-registry-simultaneously-using-github-actions-213a

> One note before starting: The GitHub registry only supports scoped packages. So if your npm package currently has a name of my-package, you will have to rename it to @username/my-package, or else GitHub will reject your package. This is easy enough to do, but you will need to redirect users of your package to the new package name. This is easily done with the npm deprecate command.

Doesn't really seem worth the trouble, in my opinion.

**Comment by Revadike** [comment]
I am using this myself: https://www.npmjs.com/package/npm-multi-publish?activeTab=readme

**Comment by DoctorMcKay** [comment]
It looks like using that would still necessitate renaming the package to comply with GitHub's scope requirement. Trying to programmatically edit package.json between publishes sounds nasty.
