### ISSUE TITLE
 TypeError: Cannot set property 'rich_presence' of undefined

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steam-user#363]
## Describe the bug
image says everything.

## Versions
v4.19.10

## Screenshots and Error Logs
![image](https://user-images.githubusercontent.com/30638036/120954631-f7338c00-c725-11eb-9019-1d9b53ad0f6c.png)

**Comment by Revadike** [comment]
You sure that's your version? The line referring in the error stack does not include `rich_presence` in the latest version. Try updating.

**Comment by Karlend** [comment]
Same problem
![Termius_nwdjj1yhul](https://user-images.githubusercontent.com/21314556/124598922-d1f18500-de6d-11eb-9bfc-fb744abd8634.png)

**Comment by Revadike** [comment]
> Same problem
> ![Termius_nwdjj1yhul](https://user-images.githubusercontent.com/21314556/124598922-d1f18500-de6d-11eb-9bfc-fb744abd8634.png)

Do you have the latest version as well?

**Comment by Karlend** [comment]
> > Same problem
> > ![Termius_nwdjj1yhul](https://user-images.githubusercontent.com/21314556/124598922-d1f18500-de6d-11eb-9bfc-fb744abd8634.png)
> 
> Do you have the latest version as well?

Yes

**Comment by Karlend** [comment]
As i see, object is undefined, but there is check strictly for null ( !== instead of != )

**Comment by DMPR-dev** [comment]
It also happened for me.

The steps in my case were:
1. Log into steam
2. Set Persona State to invisible
3. Get wallet, inventory, games
4. Log off
5. Randomly get this error.

It feels like handler tries to handle client persona state message after logging off 
![image](https://user-images.githubusercontent.com/45971281/125197146-3abd7080-e265-11eb-8e48-c83bde062f0b.png)
