### ISSUE TITLE
User::playerstate returns false data

### ISSUE THREAD

**Issue by SamHoque** [DoctorMcKay/node-steam-user#365]
## Describe the bug
User::playingState returns blocked as false even when I am logged into a game elsewhere, I got the error "LoggedInElseWhere" as well.

## Versions
Steam-User v4.19.10
Node: v12.19.0

## Screenshots and Error Logs
`{ blocked: false, appid: 0 }`

**Comment by DoctorMcKay** [comment]
Please show your code.

**Comment by SamHoque** [comment]
> Please show your code.

`console.log(user.playingState);` calling this on a `setTimeout` loop inside `LoggedInElsewhere` error event.

**Comment by DoctorMcKay** [comment]
When the error event gets emitted, you're disconnected from Steam. All account data in the SteamUser object becomes invalid at that point.
