### ISSUE TITLE
`redeemKey` response is sometimes `undefined`

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#367]
I don't know what triggers it, it appears completely random, but sometimes `result`, `packages` and `details` are all `undefined`. I have checked whether the problem lies with me, but I tracked it down to `redeemKey`'s actual response. Also, this has been happening for a while now. My earliest encounter with this bug was at  2019-03-03. It is annoying because the key may or may not be actually redeemed. You have to check manually for this. Please look into this.

**Comment by Revadike** [comment]
Found the issue!

![image](https://user-images.githubusercontent.com/4411977/125813141-0a15b1df-cff4-4337-a150-f06569299c35.png)

So I think having a larger timeout for key redemptions should fix it.

**Comment by DoctorMcKay** [comment]
I'm confused. Are you treating an error as if it were an actual response?

The timeout is 10 seconds. It certainly could be increased, though it seems weird to me that Steam would regularly take longer than that. Although I guess there might be some rate-limiting delays built in?

**Comment by Revadike** [comment]
I initially said `result` was returning `undefined`, but I was wrong about that. I was incorrectly checking it (by assuming it's always a steam `EResult` object) at the time. The timeout error is undesired, as it appears the key redemption has failed, yet the key may or may not be activated (important info).

I am currently testing a higher timeout set. It's hard to properly test, because I don't have a bunch of working keys, and you can get rate limited easily. Additionally, I am still unsure what triggers the longer response time, but since the occurrences have increased, at the same time as my licenses count has increased, I bet that is correlated.

**Comment by Revadike** [comment]
So, I've been testing the increased timeout, and it definitely solves the issue. I had it set for 60 seconds. That worked great. I only had it timeout once, so maybe crank it to 90 seconds. I don't see why not.
