### ISSUE TITLE
Is it possible to get the text?

### ISSUE THREAD

**Issue by perssBest** [DoctorMcKay/node-steam-user#368]
I wanted to write one script, but for this I need to watch the messages that were left in my profile/manual, etc. Is it possible to somehow see the text of the message that has already been left?

```js
<>.on("newComments", ...)
```
I only found this event, but it only provides numbers and not the message itself. 
Searched `steamcommunity` too, found nothing.
Maybe there is some other method, event or even another library to see the content of new comment?

**Comment by Revadike** [comment]
You are looking for this: https://github.com/DoctorMcKay/node-steamcommunity/pull/220
Sadly, this PR is not yet approved.
