### ISSUE TITLE
EnableTwoFactor Error: Cannot read property 'toBuffer' of null

### ISSUE THREAD

**Issue by Krash-ua** [DoctorMcKay/node-steam-user#37]
Hi guys. I am trying to use EnableTwoFactor function and receiving the following error

node_modules/steam-user/components/twofactor.js:26
            callback(body.status, body.shared_secret.toBuffer(), body.revocation_code);
                                                    ^

TypeError: Cannot read property 'toBuffer' of null

The code is typical :
```javascript
var client = new SteamUser();
client.logOn({
    accountName: config.username,
    password: config.password
});

client.on('loggedOn', function (details) {
    console.info("Logged into Steam as " + client.steamID.getSteam3RenderedID());
    client.enableTwoFactor(function(status) {
       console.log(status);
    });
});
```

I have seen https://github.com/DoctorMcKay/node-steam-user/issues/11 but havent found an answer there. My email is validated. I have taken a look into variable body in enableTwoFactor.
It returns:
```javascript
{ 
shared_secret: null,
  serial_number: null,
  revocation_code: null,
  uri: null,
  server_time: null,
  account_name: null,
  token_gid: null,
  identity_secret: null,
  secret_1: null,
  status: 29
 }
```

Could you please give me an advice what can be possibly wrong with my code?

**Comment by DoctorMcKay** [comment]
Firstly, this crash was fixed some time ago. You should update.

Secondly, 29 = DuplicateRequest, which means that you already have 2FA enabled.

**Comment by Krash-ua** [comment]
Thank you!
