### ISSUE TITLE
Remove `enablePicsCache` requirement for `changelist` event.

### ISSUE THREAD

**Issue by trbodev** [DoctorMcKay/node-steam-user#379]
## Is your feature request related to a problem? Please describe.
It's a bit confusing why the `enablePicsCache` option is required for the `changelist` event when the full cache isn't even used in the event. (Im aware that cache is used for the previous changenumber)

## Describe the solution you'd like
Separate `enablePicsCache` option in to `enablePicsCache` and `enablePicsCacheChangenumber` or add more specific `picsCache` options object (this could probably be another issue for only caching certain apps/packages)
```js
const client = new SteamUser({
	picsCache: {
		enabled: false,
		changenumber: true
	}
});
```

## Describe alternatives you've considered
Setting `enablePicsCache: true` and then clearing unused app/package caches on a timer

## Additional context
N/A

**Comment by magne4000** [comment]
I second that, I'll need to have a long running connection to listen to all changes, on a machine with between 512MB and 1GB of RAM. `picsCache` for this use case is not necessary, so conceptually I think it would be great to just have a minimal version of `changelist`.
But more than that, if I want to listen to a all changes, I would probablty need more RAM than what I will have available, and this is subject to memory leaks (so crashes).
