### ISSUE TITLE
disable notifications

### ISSUE THREAD

**Issue by RobotXX1** [DoctorMcKay/node-steam-user#384]
hello, I need an option so that I can disable all notifications eg ClientUserNotifications

**Comment by DoctorMcKay** [comment]
You can't disable those. Why do you think you need this?

**Comment by RobotXX1** [comment]
I just need to maintain the session. I don't need notifications.

**Comment by DoctorMcKay** [comment]
Notifications arrive passively. There's no way to tell Steam not to send them.

**Comment by RobotXX1** [comment]
Is data sent via WebSocket? If that's okay! I want to limit the requests to steam as we have account bans.

**Comment by DoctorMcKay** [comment]
Yes, steam-user doesn't make any HTTP requests at all except one right after you log on, and when you use webLogOn.
