### ISSUE TITLE
Add GetLegacyGameKey 

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#388]
https://github.com/SteamRE/SteamKit/pull/1071

**Comment by Revadike** [comment]
🙀
That was quick!

**Comment by Revadike** [comment]
@DoctorMcKay rip, you forgot to add it to docs though

**Comment by DoctorMcKay** [comment]
🤦

**Comment by Revadike** [comment]
So, I just [dumped all cd keys of my owned apps](https://github.com/DoctorMcKay/node-steam-user/pull/390) and there are a few bad/weird keys among them. Most of them are fine, but some are like base64 encoded buffers. This happened for these apps:
 - https://steamdb.info/app/236591
 - https://steamdb.info/app/359600
 - https://steamdb.info/app/359610
 - https://steamdb.info/app/591121
 - https://steamdb.info/app/783930

**Comment by DoctorMcKay** [comment]
Those are all Ubisoft games and they all activate with an API, so I'm guessing that's just the format they went with for those keys. Nothing says a key *must* look like XXXXX-XXXXX-XXXXX.

**Comment by DoctorMcKay** [comment]
Update from Discord:

> I decoded the base64 but didn't get anything super interesting in the binary data
the first 4 bytes are 0x01 0x01 0x01 0x00 but beyond that I don't see a noticeable pattern
> no steamid, for example
> I'd thought maybe it would be an app ownership ticket given the LegacyKeyProofOfPurchaseTicket appdata key
> https://steamdb.info/search/?a=app_keynames&type=-1&keyname=391&operator=1&keyvalue=
> these all look like ubisoft games
> it might just be something special valve did for ubisoft
> I don't really understand why that would be necessary given encrypted app tickets are a thing, but ¯\_(ツ)_/¯

**Comment by Revadike** [comment]
So I checked https://steamdb.info/search/?a=app_keynames&type=-1&keyname=179&operator=1&keyvalue= and after dumping all my cd keys, a bunch appears to be missing. Maybe I did something wrong? Possibly I was rate limited?
