### ISSUE TITLE
Callback does not receive sessionTicket parameter in createAuthSessionTicket call

### ISSUE THREAD

**Issue by Jadd** [DoctorMcKay/node-steam-user#391]
The following example outputs _null_ for both _err_ and _sessionTicket_ callback parameters.

```
g_SteamClient.logOn({accountName: '***************', password: '***************'});

g_SteamClient.on('loggedOn', () => {
  g_SteamClient.createAuthSessionTicket(480, (err, sessionTicket) => { console.log(sessionTicket); });
});
```

Additionally, a call to getActiveAuthSessionTickets() will indicate that the session ticket was in fact created.

**Comment by Jadd** [comment]
Problem arises from callbackPromise specifying the argument name as _appTicket_ whereas the callback is invoked with the argument key _sessionTicket_.

https://github.com/DoctorMcKay/node-steam-user/blob/7a8082e30c5aefce301db100bb51b268880dda09/components/appauth.js#L88
https://github.com/DoctorMcKay/node-steam-user/blob/7a8082e30c5aefce301db100bb51b268880dda09/components/appauth.js#L123

Unfortunately I'm unable to submit a pull request at the moment.

Thanks!

**Comment by DoctorMcKay** [comment]
Brought it in line with the documentation.
