### ISSUE TITLE
[CDN] Add `ContentServerDirectory.GetManifestRequestCode`

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#398]
https://steamdb.info/blog/manifest-request-codes/

Soon, this may be required.

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-user/wiki/Steam-CDN-Client#getmanifestrequestcodeappid-depotid-manifestid-branchname-branchpassword-callback
