### ISSUE TITLE
Get manifest throws error from 401 response

### ISSUE THREAD

**Issue by AndreasWJ** [DoctorMcKay/node-steam-user#400]
## Describe the bug
I don't know the module's source the best or know Steam but it seems like the manifest endpoint requires a manifest request code now. Otherwise you'll end up with a 401 error.

In cdn.js-`getRawManifest()` there's an if statement that will upon its condition append a manifest request code onto the url. This if statement's condition is you providing a branch name argument to `steamUser.getManifest(...)`. You can circumvent this error by simply providing one. In CS:GO's case it's `branch`. This is the if statement I'm speaking of:
```
let manifestRequestCode = '';
if (branchName) {
	let {requestCode} = await this.getManifestRequestCode(appID, depotID, manifestID, branchName, branchPassword);
	manifestRequestCode = `/${requestCode}`;
}
```

Is this intended behaviour? I might have done something wrong or misinterpreted the branch argument's purpose.

## Versions
Module: Latest
NodeJS: v16.14.2

## Screenshots and Error Logs
```
Error: HTTP error 401
    at ClientRequest.<anonymous> (C:\Users\known\Desktop\Code\Self-Written Packages\MyPackage\node_modules\steam-user\components\cdn.js:574:13)
    at Object.onceWrapper (node:events:646:26)
    at ClientRequest.emit (node:events:526:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:482:22)
    at TLSSocket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by AndreasWJ** [comment]
Branch name is required to fetch manifest now, might have to do with Steam collecting statistics on number of players in each branch. https://steamcommunity.com/groups/steamworks/announcements/detail/3222900587026809494

**Comment by DoctorMcKay** [comment]
https://steamdb.info/blog/manifest-request-codes/

Valve's statement on this:

> "We are actually not planning to disable downloading old builds. What we are working on is an approach on handling edge cases involving unowned content, and helping partners more easily take down builds that need to be removed for things like copyright issues. We’ll have more to share on that work when it’s ready to ship."

**Comment by DoctorMcKay** [comment]
This is intended behavior, at least at the moment. When support for manifest request codes was added to steam-user, they were not yet mandatory and it wasn't 100% certain that they would become mandatory. They are now, so you'll always need to provide the branch name so steam-user can retrieve the request code.

The default branch should always be "public".

**Comment by DoctorMcKay** [comment]
4.24.4 now assumes you meant "public" if you don't pass a branch name, and warns via stderr when it makes the assumption. You should always pass a branch name, and the docs have been updated to reflect this.
