### ISSUE TITLE
Enums no longer works?

### ISSUE THREAD

**Issue by idinium96** [DoctorMcKay/node-steam-user#402]
## Describe the bug
Any time I want to access enums, it just throws `undefined`.

## Versions
- Module version: v4.24.5 ([TF2Autobot](https://github.com/TF2Autobot/tf2autobot/blob/5e08146bf308ac5dd4084b64d943f7ede35d42a2/package.json#L62))
- Node.js: > 16.x

## Screenshots and Error Logs
- From TF2Autobot ([tf2autobot/src/classes/Bot.ts#L1402](https://github.com/TF2Autobot/tf2autobot/blob/5e08146bf308ac5dd4084b64d943f7ede35d42a2/src/classes/Bot.ts#L1402)):
![tf2autobot-error](https://cdn.discordapp.com/attachments/818538675573882911/1001633400534347826/unknown.png)

- Simple test:
![image](https://user-images.githubusercontent.com/47635037/181806682-1797ac90-1e6b-49a4-ad03-1baf316da9dc.png)

**Comment by DoctorMcKay** [comment]
You need to access enums as properties of the SteamUser class, not your instance.

`SteamUser.EResult`, not `steamUser.EResult`.

**Comment by idinium96** [comment]
Oh yeah I see. I just re-tested it this way, and it works.
![image](https://user-images.githubusercontent.com/47635037/181809534-e6f53f10-efcf-434b-b291-716dd9b36cb6.png)

Probably importing this way https://github.com/TF2Autobot/tf2autobot/blob/5e08146bf308ac5dd4084b64d943f7ede35d42a2/src/classes/Bot.ts#L2
is a no no.

I will try `SteamUser.EResult` instead. Thank you.

**Comment by DoctorMcKay** [comment]
I don't see why that import wouldn't work.

**Comment by idinium96** [comment]
I am honestly not sure, probably just a TypeScript compilation issue on the tf2autobot repository.
Doing this (https://github.com/TF2Autobot/tf2autobot/pull/1266/files) will fix it because it will compile to CommonJS like so:
![image](https://user-images.githubusercontent.com/47635037/181864691-e01bf559-f701-4bb7-9940-ff8417a81482.png)

Previously, only `steam_user_1`, which might be the one you said earlier (instance instead of class).

**Comment by dukeofsussex** [comment]
> Probably importing this way https://github.com/TF2Autobot/tf2autobot/blob/5e08146bf308ac5dd4084b64d943f7ede35d42a2/src/classes/Bot.ts#L2 is a no no.

Same for me, haven't looked into why it stopped working with that syntax, but I can confirm it has.
