### ISSUE TITLE
Request Timed Out

### ISSUE THREAD

**Issue by WinterFe** [DoctorMcKay/node-steam-user#406]
## Describe the bug
Getting a request timed out error (see #312)
-- exact same issue

## Versions
Node: v16.15.1
node-steam-user: 8.14.0

## Screenshots and Error Logs
https://i.lunardev.group/xozRPFk/direct

**Comment by DoctorMcKay** [comment]
There's no such thing as node-steam-user 8.14.0. I need to see your code.

**Comment by WinterFe** [comment]
Apologies - 
node-steam-user version: 4.24.3

I'm really just using a provided example: https://i.lunardev.group/iCKE2hP/direct

**Comment by nolddor** [comment]
@WinterFe is just me or i cannot see anything at the link? Expired mby?

**Comment by NlMANT** [comment]
Same problem. The bot works for 2 minutes, then get a timeout. After reconnecting, it works again for 2 minutes. The problem started in October and is still there.

steam-user v4.26.0
