### ISSUE TITLE
requestRichPresence returns nothing

### ISSUE THREAD

**Issue by Satont** [DoctorMcKay/node-steam-user#412]
## Describe the bug
I'm trying to get rich presence of user, but it no more working. Actually it was working ok couple month ago, since that moment im never changed code, but updated lib sometimes. Now `requestRichPresence` returns empty users.

## Versions
`"steam-user": "4.25.0",`

## Screenshots and Error Logs
```ts
export class AppService extends SteamUser {
  constructor() {
    super({
      autoRelogin: true,
    });
    
    this.init()
  }
  
  async init() {
     this.logOn({
      accountName: config.STEAM_USERNAME,
      password: config.STEAM_PASSWORD,
    });

    this.on('disconnected', (e) => {
      console.log(`Disconnected, ${e}`);
    });

    this.on('loggedOn', (e) => {
      this.setPersona(1);
      this.gamesPlayed([570], true);
    });

    this.on('error', (e) => {
      console.log(e);
    });
  }
  
  getPresences(accIds: string[]) {
    this.requestRichPresence(570, accIds, 'english', async (error, data) => {
      if (error) {
        console.log(error);
        return
      }
      console.log(data.users)
  }
}
```

Actually my code is bigger, i just cutted extra noise. https://github.com/Satont/tsuwari/blob/cb22017d0dc1a5cc44d665e305a3d2bd354d6720/apps/dota/src/app.service.ts

`accIds` in `[ '76561199211789795', '76561199062875574' ]` format.

**Comment by Satont** [comment]
Tried that outside of project, might be problem on my side, becuase 
```
import Steam from 'steam-user'

const s = new Steam({
  autoRelogin: true,
})

s.logOn({
  accountName: '',
  password: '',
})

s.on('loggedOn', (e) => {
  s.setPersona(1);
  s.gamesPlayed([570], true);
  s.requestRichPresence(570, ['76561198085222222'], 'english', async (error, data) => {
    if (error) {
      console.log(error);
      return
    }
    console.log(data.users)
  })
});
```
Working.

**Comment by Satont** [comment]
```js
import Steam from 'steam-user';
import SteamID from 'steamid';

const s = new Steam({
    autoRelogin: true,
});

s.logOn({
    accountName: config.STEAM_USERNAME,
    password: config.STEAM_PASSWORD,
});

s.on('loggedOn', (e) => {
    s.setPersona(1);
    s.gamesPlayed([570], true);
});

s.on('appLaunched', () => {
    setInterval(() => {
        const id = SteamID.fromIndividualAccountID(343380297);
        s.requestRichPresence(570, [id], 'english', async (error, data) => {
            console.log(id.getSteamID64(), error, data);
        });
    }, 1000);
});
```

Always logging `76561198303646025 null { users: {} }` even player in match.

**Comment by DoctorMcKay** [comment]
You probably need to wait for a `user` event to emit indicating that the user is online. appLaunched is emitted synchronously when you call games played, so you're requesting RP data synchronously on the same tick as your setPersona call.

**Comment by Satont** [comment]
> You probably need to wait for a `user` event to emit indicating that the user is online. appLaunched is emitted synchronously when you call games played, so you're requesting RP data synchronously on the same tick as your setPersona call.

yes, but i'm doing it in an interval, you think `user` never emitted then?

**Comment by Satont** [comment]
I think i found problem. That happens when users set this privacy setting to not public, so not an issue with library.
![image](https://user-images.githubusercontent.com/42675886/216032793-b7075db6-399b-4d17-a05d-155a3a64293f.png)
