### ISSUE TITLE
socksProxy type is missing

### ISSUE THREAD

**Issue by vladislav-puzyrev** [DoctorMcKay/node-steam-user#414]
## Describe the bug
socksProxy type is missing in @types/steam-user

## Versions
Node.js 16.17.0, "steam-user": "^4.26.0"

## Screenshots and Error Logs
![image](https://user-images.githubusercontent.com/52296792/203135847-ac8c1ad6-425e-4a87-b0c8-2b8210986cf8.png)

**Comment by DoctorMcKay** [comment]
@types/steam-user is not maintained by me.
