### ISSUE TITLE
Checking steamID of refresh token not working

### ISSUE THREAD

**Issue by Tyranozomby** [DoctorMcKay/node-steam-user#415]
Impossible to confirm validity of ``steamID`` refresh token has the wrong field is used (``steamID`` instead of ``_steamid``)

https://github.com/DoctorMcKay/node-steam-user/blob/a3cacf3b1e701c1e560e829cbfab49a4b1640849/components/08-logon.js#L117-L122

**Comment by LelouBil** [comment]
I have the same problem.

**Comment by DoctorMcKay** [comment]
Thanks, this is fixed in [4.26.1](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.26.1).
