### ISSUE TITLE
2Factor Logon Doesn't Accept saved code

### ISSUE THREAD

**Issue by codeMatt** [DoctorMcKay/node-steam-user#42]
I have a bot that had steam guard enabled, and now recently it has the 2factor enabled.

The shared key is being used by the steam-totp library to get the 5 digit code, but that isn't allowing a straight logon, it still asks for a steam guard code. I am just trying to log on yet this steam guard code stops me from doing it automatically.

loginTwoFactorCode = SteamTotp.generateAuthCode('P......................=');

SteamClient.logOn({
	accountName: botCredential.username,
	password: botCredential.password,
	twoFactorCode: loginTwoFactorCode
});

after which I get prompted for a steam guard code.....

How do I make the application log on properly?

**Comment by Aareksio** [comment]
Make sure your code is generated on time, `TwoFactorCodes` works for roughly 30 seconds. You can also supply `timeOffset` as the second argument to `SteamTotp.generateAuthCode` function.

You may check if the last code was correct using [SteamGuard](https://github.com/DoctorMcKay/node-steam-user#steamguard) event.

**Comment by DoctorMcKay** [comment]
Your code is wrong for one reason or another. As @Aareksio mentioned, make sure your clock is correct (or you specified an appropriate `timeOffset`) and that your secret is correct.

Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/4/).
