### ISSUE TITLE
Undefined account_name in sentry files filenames

### ISSUE THREAD

**Issue by NBNGaming** [DoctorMcKay/node-steam-user#422]
## Describe the bug
When using refreshToken for log on sentry files are saved with `sentry.undefined.bin` filename because `accountName` is not passed to `logOn` method.
https://github.com/DoctorMcKay/node-steam-user/blob/be8e05c0eba611e4f31c39677353377d28dd9af0/components/sentry.js#L24
https://github.com/DoctorMcKay/node-steam-user/blob/be8e05c0eba611e4f31c39677353377d28dd9af0/components/08-logon.js#L168
Machine ID suffers too. _getMachineID thinks it is anonymous logon.
https://github.com/DoctorMcKay/node-steam-user/blob/be8e05c0eba611e4f31c39677353377d28dd9af0/components/08-logon.js#L383
## Versions
Node.js v18.13.0
steam-user v4.27.0

**Comment by DoctorMcKay** [comment]
Acknowledged, I'll be able to get to this soon. Unfortunately it looks like logging in with a refresh token will mean that we have to save sentry files and generate machine IDs based on your SteamID rather than your account name, since the account name isn't available prior to logon.

**Comment by DoctorMcKay** [comment]
Fixed in [v4.27.1](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.27.1).
