### ISSUE TITLE
socks5 option has not taken effect

### ISSUE THREAD

**Issue by Javabcd** [DoctorMcKay/node-steam-user#426]
## Describe the bug
when I set options of socksProxy, it not change steam ip ,but It works when I use httpProxy

`let steamClient = new SteamUser({socksProxy:'socks5://127.0.0.1:10808'});`

## Versions
node.js: "v18.15.0"
"steam-user": "v4.28.0"

## Possiable error location
from index.js , the method `_setOption()` no case of 'socksProxy'

**Comment by xxcc520** [comment]
Me too

**Comment by DoctorMcKay** [comment]
Works fine for me.

`socksProxy: 'socks5://127.0.0.1:8088'`

publicIP is my proxy's IP.
