### ISSUE TITLE
Unable to LogOn with latest version

### ISSUE THREAD

**Issue by therepower** [DoctorMcKay/node-steam-user#427]
## Describe the bug
I updated to 4.28 to use it and when I try to log in to steam it tries to read some files that don't exist.

TypeError: Cannot read properties of undefined (reading 'forEach')
  files.forEach((file) => {

At Line 182 on 09-logon.js

I also tried the most basic way to login, and the result is same

`
var client = new steamUser();
client.logOn({
	"accountName": account.id,
	"password": account.pw,
"logonID":4
});
`

## Versions
Node 18.15.0
Version: 4.28.0

## Screenshots and Error Logs
https://prnt.sc/Ty6nZoQmIaJN

**Comment by HerrEurobeat** [comment]
Logging in using username & password is deprecated as Steam recently changed the login flow to use refreshTokens as mentioned in the README [here](https://github.com/DoctorMcKay/node-steam-user#using-refresh-tokens).  
You might want to update your login flow to use the [steam-session](https://github.com/DoctorMcKay/node-steam-session) library, which retrieves a token for you that you can then pass to [logOn()](https://github.com/DoctorMcKay/node-steam-user#logondetails) to login.

**Comment by therepower** [comment]
> Logging in using username & password is deprecated as Steam recently changed the login flow to use refreshTokens as mentioned in the README [here](https://github.com/DoctorMcKay/node-steam-user#using-refresh-tokens). You might want to update your login flow to use the [steam-session](https://github.com/DoctorMcKay/node-steam-session) library, which retrieves a token for you that you can then pass to [logOn()](https://github.com/DoctorMcKay/node-steam-user#logondetails) to login.
thanks for informing. didn't know about the change i just updated my older bot to use

**Comment by DoctorMcKay** [comment]
It works fine for me. Please show your code and the full stack trace. Logging on with an account name and password is deprecated, but should still work.
