### ISSUE TITLE
'Request timed out' - while activating someones auth session ticket

### ISSUE THREAD

**Issue by Sadzurami** [DoctorMcKay/node-steam-user#428]
## Describe the bug
Uncaught exception during auth session ticket activation.

## Versions
steam-user - 4.28.1
node - v18.15.0

## Screenshots and Error Logs
```
C:\project\node_modules\@doctormckay\stdlib\components\promises.js:12
        let err = new Error('Request timed out');
           ^
Error: Request timed out
    at Object.Promises.timeoutPromise (C:\project\node_modules\@doctormckay\stdlib\components\promises.js:12:12)
    at Object.Promises.timeoutCallbackPromise (C:\project\node_modules\@doctormckay\stdlib\components\promises.js:87:25)
    at SteamUser.activateAuthSessionTickets (C:\project\node_modules\steam-user\components\appauth.js:175:26)
    at buildToken (C:\project\node_modules\steam-user\components\appauth.js:122:17)
    at C:\project\node_modules\steam-user\components\appauth.js:128:6
    at Immediate.<anonymous> (C:\project\node_modules\@doctormckay\stdlib\components\promises.js:94:6)
    at processImmediate (node:internal/timers:476:21)
```

## Code
```javascript
try {
   await this.steamClient.activateAuthSessionTickets(this.steamAppId, [ticket])
} catch (error) {
/* Error doesn't come here **/
/* Possible way to catch only - process.on('uncaughtException') **/
}
```

## How to repeat
Try activating someone's authentication session ticket and immediately disconnect the Internet connection. I know this method is a bit synthetic, but since the error does not always occur, but randomly, this method may help to understand that it exists at all. I'm not sure, but perhaps it could also happen with our session tickets (rather than someone else's).

## Where is the possible cause of the problem
https://github.com/DoctorMcKay/node-steam-user/blob/b7e60c71d7f525e925d13e5d11798a3d42b8b2eb/components/appauth.js#L229-L230

**Comment by Sadzurami** [comment]
It seems that the problem was in my environment.
I tested the code on Win11 arm64 with x86 node.
After upgrading to x64 the problem disappeared.
I am now closing the issue, but continue testing.

**Comment by DoctorMcKay** [comment]
It's really strange that an environment setup like that would change how a rejected promise is delivered, but I guess as long as it's working for you now that's good.

**Comment by Sadzurami** [comment]
Something is still going wrong

![image](https://user-images.githubusercontent.com/47674424/234585659-81fbdf95-7b2f-4deb-8ad7-6f4eddb05505.png)

This happens not every time, in most cases the promise works properly and rejects, instead of throw error.

**Comment by Sadzurami** [comment]
Maybe the issue behind timeouts?

Looks like timeout here starts earlier
https://github.com/DoctorMcKay/node-steam-user/blob/b67302eb6eae12e358d444ee6f237ec393ab1833/components/appauth.js#L175

than
https://github.com/DoctorMcKay/node-steam-user/blob/b67302eb6eae12e358d444ee6f237ec393ab1833/components/appauth.js#L336

in small amount of cases, for example when event-loop blocked, maybe first interval ends earlier than interval inside function (promise not awaits anymore and throw error)
