### ISSUE TITLE
Steam user "httpProxy" does not work for most of proxies

### ISSUE THREAD

**Issue by aligatorr89** [DoctorMcKay/node-steam-user#431]
## Describe the bug
- Proxy URLs (`httpProxy` property) with special characters and uppercased letters don't work. It works for simple proxy urls with lowercased letters and numbers. 

## Versions
What version of the module and what version of Node.js are you using?
steam-user: `4.24.3` 
Node: `v16.10.0`

## Screenshots and Error Logs
Login fails without any explanation.

**Comment by DoctorMcKay** [comment]
I can't reproduce this. Can you provide an example of a URL that fails? It doesn't have to be your real proxy URL.

**Comment by aligatorr89** [comment]
@DoctorMcKay thanks for reply! It was an issue with my proxy provider which doesn't allow raw IP as target address. Steam login uses raw IPs for connecting to network
