### ISSUE TITLE
Inaccurate server timestamps for messages

### ISSUE THREAD

**Issue by MachineNeil** [DoctorMcKay/node-steam-user#435]
Node-steam-user v4.28.3

I have been attempting to measure the delay between messages being sent and received via Steam chat using the following code.

```
client.chat.on("friendMessage", (message) => {
  console.log(Date.now() - Date.parse(message.server_timestamp));
```
However, when I use Date.parse(message.server_timestamp), it returns the time rounded up to the nearest second (e.g., 1684597283000 ms). As a result, I am unable to determine the exact number of milliseconds that have passed. Is this behaviour purposeful to prevent users from determining their latency?

**Comment by Gobot1234** [comment]
FWIW there are actual ways to measure your latency using the send_reply parameter of CMsgClientHeartBeat. Steam just doesn't have ms precision for sent messages as they have their "ordinal" system.

**Comment by MachineNeil** [comment]
@Gobot1234 Thank you for replying. I have only managed to find the following in regards to the parameter you are referring to:
```
/**
 * @typedef {object} Proto_CMsgClientHeartBeat
 * @property {boolean} [send_reply]
 */
```
in lines 303 and 304 of [this](https://github.com/DoctorMcKay/node-steam-user/blob/9312326c34fed69a2ea6c4102ed25e3073f0516d/protobufs/generated/_types.js#L9755-L9775) file. However, I must confess that I'm struggling to fully comprehend its functionality. Would you kindly provide me with a brief explanation?

**Comment by Gobot1234** [comment]
I don't think it's something you can implement on your end, it would need implementing in the library but the flow should look like 
```js
sleep(heartbeat_seconds);
let current_timestamp = Date.now();
send_heartbeat();
wait_for(CMsgClientHeartBeat);
let received_timestamp = Date.now();
let latency = received_timestamp - current_timestamp;
```
I did however forget about CMsgClientServerTimestampRequest/Response which might be good enough for one off things

**Comment by MachineNeil** [comment]
@Gobot1234 How do you know about these parameters? Amazing.
```
/**
 * @typedef {object} Proto_CMsgClientServerTimestampRequest
 * @property {string} [client_request_timestamp]
 */

/**
 * @typedef {object} Proto_CMsgClientServerTimestampResponse
 * @property {string} [client_request_timestamp]
 * @property {string} [server_timestamp_ms]
 */
```
I am a newbie in programming and I don't think I can face this challenge alone. If you find some more beginner friendly way to implement Steam chat latency measurement, I would be very grateful. In any case, thank you.

**Comment by DoctorMcKay** [comment]
What exactly are you trying to measure, and why? Are you trying to measure the latency between when a message is sent and when it's delivered to a recipient, or are you trying to measure your latency to the CM?

If you're trying to measure latency between when a message is sent and when it's delivered, then the only way you could accurately measure this is by using two accounts you control. Send `Date.now()` on the first, and calculate the difference between the current time and the received message on the recipient.

If you're trying to measure latency between when a message is sent and when it's acknowledged by the CM, then you could do this:

```js
let sentAtTime = Date.now();
await user.chat.sendFriendMessage(recipientSteamId, 'hello, world');
console.log(`Message sending took ${Date.now() - sentAtTime} ms`);
```

**Comment by MachineNeil** [comment]
Thank you for your help, Alex. You may not realize it, but you're doing a lot of good.
