### ISSUE TITLE
Using socksProxy causes a memory leak

### ISSUE THREAD

**Issue by Sadzurami** [DoctorMcKay/node-steam-user#437]
## Describe the bug
If we use more than one socksProxy (with different SteamUser instances) - proxies stop working (we can't logOn and etc.) and ram usage starts to rise.

The more proxies we use, the faster memory usage increases.
If we use only one proxy, there will be no problem.

The problem only exists with socks proxies.

## Versions
4.28.4
18.16.0
## Screenshots and Error Logs
Steam user does not throws or emits errors.

**Comment by Sadzurami** [comment]
Update, a similar situation occurred when using a WebSockets connection without a proxy.

Maybe a problem with the semaphore here?
https://github.com/DoctorMcKay/node-steam-user/blob/master/components/connection_protocols/websocket.js

**Comment by DoctorMcKay** [comment]
At first glance, this sounds a lot like a bug in an upstream dependency. steam-user just passes your proxy URL as-is to [socks-proxy-agent](https://www.npmjs.com/package/socks-proxy-agent).

**Comment by Sadzurami** [comment]
> At first glance, this sounds a lot like a bug in an upstream dependency. steam-user just passes your proxy URL as-is to [socks-proxy-agent](https://www.npmjs.com/package/socks-proxy-agent).

Yep, maybe.
But we found another problem close to this one.

If we try to use WebSockets as a protocol and use httpProxy with many instances of a Steam user, we get the same behavior.

If we use socksProxy, WebSockets protocol will be used by default. Maybe problem here?

**Comment by DoctorMcKay** [comment]
I cannot reproduce your report using this code:

```js
const SteamUser = require('./index');

const PROXIES = ['socks5://127.0.0.1:8808', 'socks5://127.0.0.1:8809', 'socks5://127.0.0.1:8810'];

PROXIES.forEach((proxy, idx) => {
	let user = new SteamUser({
		socksProxy: proxy
	});

	user.logOn({anonymous: true});

	let currentChangeNumber = 0;

	user.on('loggedOn', () => {
		console.log(`[${idx}] Logged on as ${user.steamID.steam3()} from ${user.publicIP}`);

		setInterval(async () => {
			let result = await user.getProductChanges(currentChangeNumber);
			currentChangeNumber = result.currentChangeNumber;
			console.log(`[${idx}] Got changenumber ${currentChangeNumber}`);
		}, 1000);
	});
});
```

**Comment by Sadzurami** [comment]
Should be fixed in https://github.com/DoctorMcKay/node-steam-user/commit/67800694c1a4e21680d25ed5665907097579dc35
