### ISSUE TITLE
Some variables are stored in global scope

### ISSUE THREAD

**Issue by Sadzurami** [DoctorMcKay/node-steam-user#439]
## Describe the bug
Some variables are accidentally stored in the global scope, which can lead to errors/bugs or unexpected results.

List of variables:
- `string` (contains cookies of LoginSecure)
- `finalstr` (contains cookies of LoginSecure)
- `res` (contains object `{authenticateuser: {token: "76561199443....", tokensecure: "76561199443...."}}`)
- `ptr` (contains number)
- `ci` (constain number)

As shown earlier, some variables contain sensitive information, such as cookies. If we use more than one SteamUser instance in the same thread, we may receive invalid cookies from another instance.

Why is this happening?

The problem is caused by the `vdf` library that was previously used by SteamUser.
This library creates variables in the global scope.
https://github.com/rjackson/node-vdf/blob/eefcd8a8651475981100d99e60da0212ff9d0ca6/index.js#L38
https://github.com/rjackson/node-vdf/blob/eefcd8a8651475981100d99e60da0212ff9d0ca6/index.js#L54
https://github.com/rjackson/node-vdf/blob/eefcd8a8651475981100d99e60da0212ff9d0ca6/index.js#L97
https://github.com/rjackson/node-vdf/blob/eefcd8a8651475981100d99e60da0212ff9d0ca6/index.js#L158
https://github.com/rjackson/node-vdf/blob/eefcd8a8651475981100d99e60da0212ff9d0ca6/index.js#L29

Stop, stop, used earlies?
Yep... Right now SteamUser is using `simple-vdf`, but the old deps haven't changed in this commit.
https://github.com/DoctorMcKay/node-steam-user/commit/a69bc1a50a2a1ba814010684b68b292f6fda2452

But how it works?
SteamSession. This library is used internally by SteamUser and depends on the old vdf library, so SteamUser can use the old vdf library.

## Versions
4.28.4
18.16.0

## Screenshots and Error Logs
![image](https://github.com/DoctorMcKay/node-steam-user/assets/47674424/71d70742-4ef9-4f75-90e4-91c9c6c98151)

**Comment by Sadzurami** [comment]
Well, adding `simple-vdf` solves this problem, but adds other variables globally.

![image](https://github.com/DoctorMcKay/node-steam-user/assets/47674424/3a53617d-44d4-4800-85e8-bbb0c521321a)

Works better, but at all, we need fork of vdf.

**Comment by Sadzurami** [comment]
Moving to @node-steam/vdf solved this problem completely.

**Comment by DoctorMcKay** [comment]
> If we use more than one SteamUser instance in the same thread, we may receive invalid cookies from another instance.

Is this conjecture or have you actually run into a problem in practice from this? The only way I'm aware of that this could happen is if you're using the worker_thread module, which is neither useful nor supported with steam-user. Worker threads are only useful when performing CPU-intensive pure-JS operations, which is not the case anywhere in steam-user. If you want to run multiple isolated steam-user instances in the same app, you should use child processes instead.

> SteamSession. This library is used internally by SteamUser and depends on the old vdf library, so SteamUser can use the old vdf library.

Then this is an issue with steam-session, not with steam-user. That said, global variables in a dependency are not considered a bug here.

**Comment by Sadzurami** [comment]
> Is this conjecture or have you actually run into a problem in practice from this?

This is an assumption. But it is worth considering this, because. if there are no bugs now, there may be in the future.

> Then this is an issue with steam-session, not with steam-user.
By the way, SteamUser tries to load old `vdf` library, that removed from `package.json`

https://github.com/DoctorMcKay/node-steam-user/blob/ba80747af4926eb6d7994e7210323e2a80545960/components/06-webapi.js#L3

https://github.com/DoctorMcKay/node-steam-user/blob/ba80747af4926eb6d7994e7210323e2a80545960/components/apps.js#L4

**Comment by DoctorMcKay** [comment]
> This is an assumption. But it is worth considering this, because if there are no bugs now, there may be in the future.

There is no way for this to introduce a bug without using worker threads, which again are unsupported in steam-user and will cause many more problems than just some bad VDF parsing.
 
> By the way, SteamUser tries to load old `vdf` library, that removed from `package.json`

Thanks, fixed in https://github.com/DoctorMcKay/node-steam-user/commit/812d58d5b1638a1c7435a307a3052cdce3ec1c97
