### ISSUE TITLE
Sentry file

### ISSUE THREAD

**Issue by hrvasiliy** [DoctorMcKay/node-steam-user#44]
I'm trying to save sentry file:
```javascript
client.on('sentry', function(sentryHash) {
  fs.writeFile('sentry',sentryHash,function(err) {
    if(err) {
      console.log(err);
    } else {
      console.log('Saved sentry file hash as "sentryfile"');
    }
  });
});
```
but my case does not work even if I try:
```javascript
client.on('sentry', function(sentryHash) {
  console.log('Hi!');
});
```
also I can't use the ssfn file. 

How to save and login on the ssfn file?

**Comment by Aareksio** [comment]
`sentry` event is only emitted if you use classic `SteamGuard`, `2FA` requires using new code everytime you want to log in.

I belive you should wait for response on [steam group](https://steamcommunity.com/groups/SteamRE/discussions/4/)'s forums.
