### ISSUE TITLE
Most proxies that I use do not work, bad gateway error.

### ISSUE THREAD

**Issue by newTomas** [DoctorMcKay/node-steam-user#443]
## Describe the bug

When I specify a proxy, I get a `bad gateway` error. If in the `components/connection_protocols/tcp.js` file replace `let req = HTTP.request(url);` on
```js
let request = HTTP request({
host: url.host,
hostname: url.hostname,
port: url.port,
headers: url headers,
method: "CONNECT",
path: tcpCm
});
```
then the client successfully logs in to steam, but the web session does not arrive (the `loggedOn` event arrives, but the `webSession` does not).
The same if you remove `delete url.auth;`
Checked on 3 different proxies from different countries from different providers. What could be the problem?

## Versions
node v20.3.1
steam-user v4.28.6

**Comment by newTomas** [comment]
I removed `delete prox.auth;` in `stdlib/components/http/proxyagent.js` and now the web session works too. Is it possible to remove the removal of `auth` from the `URL` everywhere?

**Comment by DoctorMcKay** [comment]
It sounds like your proxies aren't HTTP compliant, and are looking for an Authorization header rather than a Proxy-Authorization header. This is unsafe, as it has the potential for leaking your proxy credentials to whatever server you're connecting to.

I suggest you contact your provider and inquire as to why their proxies aren't compliant.

**Comment by newTomas** [comment]
@DoctorMcKay 
Indeed, if you leave `auth` in the `url`, then in addition to `Proxy-Authorization`, `Authorization` will also be transmitted. Although I do not understand what is insecure about this, because both headers are transmitted in base64 without encryption. But what about the second solution to the problem? If an object is passed instead of a `URL`, then only `Proxy-Authorization` is passed, but instead of `URI /`, `tcpCm` is passed as a `URI`.

tcp.js:
```js
let req = HTTP.request({
  method: "CONNECT",
  path: tcpCm,
  localAddress: user.options.localAddress,
  localPort: user.options.localPort,
  headers: url.headers,
  host: url.host,
  hostname: url.hostname,
  port: url.port,
});
```
![image](https://github.com/DoctorMcKay/node-steam-user/assets/18233174/da54c3a6-f68c-424a-9afc-b0b3a822b581)
![image](https://github.com/DoctorMcKay/node-steam-user/assets/18233174/52db9af9-d518-4b9e-b79c-bb6fd6899ffe)

proxyagent.js:
```js
let req = (prox.protocol == "https:" ? HTTPS : HTTP).request({
  method: "CONNECT",
  path: prox.path,
  localAddress: options.localAddress,
  localPort: options.localPort,
  headers: prox.headers,
  host: url.host,
  hostname: url.hostname,
  port: url.port,
});
```
![image](https://github.com/DoctorMcKay/node-steam-user/assets/18233174/46e6ae87-0274-4b62-947b-f852b4c79018)
![image](https://github.com/DoctorMcKay/node-steam-user/assets/18233174/f57a9fc4-58cf-412d-b66e-442997eb0453)

I assume that when the `URI /` was transmitted, the proxy considered that we were connecting to the proxy as a site and therefore requested `Authorization` in addition to `Proxy-Authorization`.

**Comment by DoctorMcKay** [comment]
> If an object is passed instead of a URL, then only Proxy-Authorization is passed, but instead of URI /, tcpCm is passed as a URI.

I don't understand what you're saying here. Can you elaborate and give an example?

**Comment by newTomas** [comment]
> > If an object is passed instead of a URL, then only Proxy-Authorization is passed, but instead of URI /, tcpCm is passed as a URI.
> 
> I don't understand what you're saying here. Can you elaborate and give an example?

I pass [options](https://nodejs.org/api/http.html#httprequestoptions-callback) instead of `URL`. The whole difference between the original code and what I wrote is that the original sends the request `"CONNECT /"`, and my `"CONNECT " + tcpCm` and `"CONNECT " + (options.host + ':' + options.port)` for `tcp.js` and `proxyagent.js` respectively

**Comment by DoctorMcKay** [comment]
The code is working perfectly fine as-is for me. I still can't follow what you're saying.

![image](https://github.com/DoctorMcKay/node-steam-user/assets/1538723/52e208af-3d14-46aa-a04b-c32ab94fdad7)

**Comment by newTomas** [comment]
It seems I understood. The `url` has a `path` and a `pathname`, you set the `path` manually, but the `pathname` is still the default and is equal to `/` and for some reason in my case the request is `CONNECT /`. I tried to switch to `node v18` and the proxies work correctly there. So apparently this is a `node v20` bug, but you can just change from `path` to `pathname`.
![image](https://github.com/DoctorMcKay/node-steam-user/assets/18233174/74a77126-5923-4c26-a107-eb41363970b3)

**Comment by newTomas** [comment]
It turns out that `pathname` instead of `path` does not work on `node v18`, it is necessary to specify the `path`. Can you find a solution that will work on any node version?

**Comment by DoctorMcKay** [comment]
[4.28.7](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.28.7) should fix things for you.
