### ISSUE TITLE
ClientUpdateMachineAuth not working

### ISSUE THREAD

**Issue by Sdoy** [DoctorMcKay/node-steam-user#447]
## Describe the bug

using email auth account , sentry event not emit

logOnOptions is  {dontRememberMachine: false}

## Versions
4.28.9

**Comment by k0mar12** [comment]
have u fixed it ? I have same problem

**Comment by DoctorMcKay** [comment]
Steam isn't using sentry files anymore. [4.29.0](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.29.0) has a fix for this.

**Comment by k0mar12** [comment]
> Steam isn't using sentry files anymore. [4.29.0](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.29.0) has a fix for this.

thanks :)
