### ISSUE TITLE
Unable to login with v4.29.0 using refreshToken

### ISSUE THREAD

**Issue by nombersDev** [DoctorMcKay/node-steam-user#451]
## Describe the bug
Logging in using refreshtoken causes the following error 

`TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at SteamUser._getMachineAuthFilename (/Users/xxx/Documents/github/steam-engine/node_modules/steam-user/components/08-machineauth.js:19:97)
    at /Users/xxx/Documents/github/steam-engine/node_modules/steam-user/components/09-logon.js:223:50`

It appears to be looking for an account_name variable but it is undefined when logging in with the refreshToken. 

`{ account_name: undefined,
  password: undefined,
  login_key: undefined,
  auth_code: undefined,
  two_factor_code: undefined,
   ... }
`

Reverting to [v4.28.9](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.28.9) fixes the issue.

## Versions
v4.29.0

**Comment by DoctorMcKay** [comment]
Fixed in 4.29.1, thanks for the report.
