### ISSUE TITLE
TypeError: this.debug is not a function

### ISSUE THREAD

**Issue by thouravi** [DoctorMcKay/node-steam-user#457]
I am still getting the same error despite updating the package.

Tried both the latest version and the previous version (4.27.1).

![image](https://github.com/DoctorMcKay/node-steam-user/assets/15676184/fa14b147-4855-440a-be34-c5d58300dd7b)

```
TypeError: this.debug is not a function
at LoginSession. (/home/ubuntu/scripts/appInfo/node_modules/steam-user/components/09-logon.js:366:10)
at LoginSession.emit (node:events:513:28)
at LoginSession._doPoll (/home/ubuntu/scripts/appInfo/node_modules/steam-session/dist/LoginSession.js:483:22)
```

**Comment by Kolosok86** [comment]
<img width="980" alt="CleanShot 2023-09-13 at 09 41 46@2x" src="https://github.com/DoctorMcKay/node-steam-user/assets/48204231/d5ca543e-0774-4afb-9e5d-dc666cf55a6b">

4.29.2

**Comment by AlexKrois** [comment]
really seems like valve changed something, since i also have this problem since the last maintenance.

**Comment by gaelsuv** [comment]
> I am still getting the same error despite updating the package.
> 
> Tried both the latest version and the previous version (4.27.1).
> 
> ![image](https://user-images.githubusercontent.com/15676184/267546694-fa14b147-4855-440a-be34-c5d58300dd7b.png)
> 
> ```
> TypeError: this.debug is not a function
> at LoginSession. (/home/ubuntu/scripts/appInfo/node_modules/steam-user/components/09-logon.js:366:10)
> at LoginSession.emit (node:events:513:28)
> at LoginSession._doPoll (/home/ubuntu/scripts/appInfo/node_modules/steam-session/dist/LoginSession.js:483:22)
> ```

4.29.2 didn't work for me either, but 4.27.1 seems to have fixed it. Make sure to run `npm install` after changing dependencies

**Comment by younesabouali** [comment]
browsed the code a bit, it seems like it's implemented in the base connection class, but no class is extending it ?

**Comment by DoctorMcKay** [comment]
Sounds like you're running into some caching or other environmental problems. 09-logon.js:366 is a comment in the latest version.

**Comment by DoctorMcKay** [comment]
4.29.3 is up to fix this crash for real, but your underlying issue was that you didn't get the latest version of steam-session along with your steam-user update. package.json has also been updated to require the latest version of steam-session.
