### ISSUE TITLE
Error: globaloffensive v2 only supports steam-user v4.2.0 or later. SteamUser v5.0.1 given.

### ISSUE THREAD

**Issue by hrjoyce1990** [DoctorMcKay/node-steam-user#459]
## Describe the bug
Error: globaloffensive v2 only supports steam-user v4.2.0 or later. SteamUser v5.0.1 given.

## Versions
"steam-user": "^5.0.1",
"globaloffensive": "^2.3.0",

## Screenshots and Error Logs

source code:
let parts = steam.packageVersion.split('.');
if (parts[0] < 4 || parts[1] < 2) {
	throw new Error(`globaloffensive v2 only supports steam-user v4.2.0 or later. ${steam.constructor.name} v${steam.packageVersion} given.`);
}

version.5.0.1 will get this error,plase fix this error

**Comment by DoctorMcKay** [comment]
globaloffensive is the offending package with the bug, not steam-user. 2.3.1 fixes this.
