### ISSUE TITLE
How to connect to steam

### ISSUE THREAD

**Issue by WalkingCore** [DoctorMcKay/node-steam-user#46]
I am trying the function community.login but it says it doesnt exist...and after it's done, how do I get the cookies and sesion id?

**Comment by andrewda** [comment]
Did you even read the README? https://github.com/DoctorMcKay/node-steam-user#logondetails

**Comment by DoctorMcKay** [comment]
Read the readme and direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/4/).
