### ISSUE TITLE
httpProxy Proxy connection timed out

### ISSUE THREAD

**Issue by backtd** [DoctorMcKay/node-steam-user#461]
## Issue/Bug
I have used almost every single proxy provider there is from oxylabs, proxyrack, proxy-server, rayobyte, packetstream and the list keeps going and no matter what I can't get it to work with any proxy and always times out the connection it is like not allowing the connection to go through at all although the same proxies are used in all different modules and http requests but won't work on the steam-user module, for example the proxies work with the steamcommunity module or axios or httpProxyAgent but not with the steam-user which uses the native HTTP module from nodejs

## Versions
steam-user v5.0.1
NodeJS v16.12.0

## Screenshots and Error Logs
![Code_KRs4JVwPV9](https://github.com/DoctorMcKay/node-steam-user/assets/105519986/29de419a-80f0-4c05-bfbb-c794e5ce7bda)

**Comment by DoctorMcKay** [comment]
I cannot provide support for third-party proxy providers. Maybe try enabling the `webCompatibilityMode` option.
