### ISSUE TITLE
Cannot find module lzma_worker.js when using with pkg

### ISSUE THREAD

**Issue by krylovaaleksandra** [DoctorMcKay/node-steam-user#467]
## Describe the bug
I am trying to package my application using pkg and I get the error below

```
import SteamUser from "steam-user";

const client = new SteamUser();
console.log("Hello world")
```

package command:
`yarn pkg dist/index.js --target node14-win-x64`

## Versions
latest

## Screenshots and Error Logs
![изображение](https://github.com/DoctorMcKay/node-steam-user/assets/101058726/0884042d-8cd2-4127-afa1-ed5de9375aa5)

**Comment by DoctorMcKay** [comment]
Your issue is caused by a third-party tool (pkg) interacting improperly with a third-party dependency (lzma). I can't really help you here.

**Comment by Sadzurami** [comment]
@krylovaaleksandra 

just add this lines to your package.json file

```json
"pkg": {
    "assets": [
      "node_modules/@doctormckay/steam-crypto",
      "node_modules/lzma"
    ]
  }
```
