### ISSUE TITLE
ETIMEDOUT result in crash

### ISSUE THREAD

**Issue by jollenR** [DoctorMcKay/node-steam-user#47]
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

C:\Users\Joel\Desktop\bot>pause
```

The program stops after this error and it seems to be appearing on logins. Any recomendations on what to do to prevent crash and instead retrying to login?

**Comment by DoctorMcKay** [comment]
http://steamcommunity.com/groups/SteamRE/discussions/4/458605613390323450/
