### ISSUE TITLE
Change the getUserOwnedApps() method description

### ISSUE THREAD

**Issue by rcode-app** [DoctorMcKay/node-steam-user#471]
## Describe the bug
The key names are incorrect. 

**"games_count" => "app_count"
"games" => "apps"**

## Versions
steam-user: ^5.0.8

![2024-02-09 19 56 40](https://github.com/DoctorMcKay/node-steam-user/assets/110404110/027bd356-8667-4fd4-8ccc-fc1e0e9f41a2)
![2024-02-09 19 55 15](https://github.com/DoctorMcKay/node-steam-user/assets/110404110/3e8b00e7-8a61-412e-9599-b3c9adf22f77)

response:
`{
  app_count: 26,
  apps: [
    {
      content_descriptorids: [Array],
      appid: 10,
      name: 'Counter-Strike',
      playtime_2weeks: null,
      playtime_forever: 74464,
      img_icon_url: 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/10/6b0312cda02f5f777efa2f3318c307ff9acafbb5.jpg',
      has_community_visible_stats: null,
      playtime_windows_forever: 0,
      playtime_mac_forever: 0,
      playtime_linux_forever: 0,
      rtime_last_played: 1456867622,
      capsule_filename: null,
      sort_as: null,
      has_workshop: null,
      has_market: null,
      has_dlc: null,
      has_leaderboards: null
    },
    ...
  ]
}`

**Comment by simonkovtyk** [comment]
https://github.com/DoctorMcKay/node-steam-user/pull/484

**Comment by simonkovtyk** [comment]
And also the fix for the definitly types here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70209

**Comment by DoctorMcKay** [comment]
Fixed in [5.1.0](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v5.1.0)
