### ISSUE TITLE
Outdated typescript definitions

### ISSUE THREAD

**Issue by osztenkurden** [DoctorMcKay/node-steam-user#478]
## Describe the bug
@types/steam-user seems to have outdated types. 

## Versions
Node: 20.9.0
Typescript: 5.3.2
steam-user: 5.0.8
@types/steam-user: 4.26.8

## Screenshots and Error Logs
Example is logOn method, when using machineAuthToken:
```javascript
 if (session.steamGuardMachineToken) client.logOn({
        accountName: env.ACCOUNT_NAME,
        password: env.PASSWORD,
        machineAuthToken : session.steamGuardMachineToken
    });
```

![image](https://github.com/DoctorMcKay/node-steam-user/assets/25458209/48250bd8-a33d-4481-8595-6746f0b2974d)

**Comment by DoctorMcKay** [comment]
@types/steam-user is not maintained by me.
