### ISSUE TITLE
Running many bots

### ISSUE THREAD

**Issue by dolanmiu** [DoctorMcKay/node-steam-user#48]
I want to eventually run 100+ bots on my Heroku setup.

Do you recommend running ```node-steam-user``` and ```node-steamcommunity``` on many Heroku apps? I have 24+ bots at the moment on one app, and its already starting to struggle, using more and more RAM.

I was thinking of having the main app call the bot apps through an API, which will reduce load on the main server.

What are you recommendations? How would you do it? I need your expert advice.

Thanks!

**Comment by DoctorMcKay** [comment]
Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/4/).

I wouldn't try to run 100+ bots on a single machine without loads of RAM, CPU, and IP addresses.

I've successfully run 30 bots each on several relatively cheap VPSes, which are controlled by a central webserver.
