### ISSUE TITLE
Implement `SteamNotificationClient` notifications

### ISSUE THREAD

**Issue by xPaw** [DoctorMcKay/node-steam-user#485]
https://github.com/SteamDatabase/Protobufs/blob/master/steam/steammessages_notifications.steamclient.proto

In particular `CSteamNotification_NotificationsReceived_Notification`.

If you search for `notification_type` in Steam client javascripts, you can find test functions that include `body_data` json strings, but for the lib it would be enough to just parse the json.

Example code here: https://github.com/xPaw/Steam-Card-Farmer/blob/115f8ea3201d71321a9fde4b6ef67d33d8eea933/index.mjs#L582

**Comment by DoctorMcKay** [comment]
Landed in [5.2.0](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v5.2.0)
