### ISSUE TITLE
Error: Parse error at line 1: unexpected ''

### ISSUE THREAD

**Issue by ClassAxion** [DoctorMcKay/node-steam-user#50]
Hi.
I install steam-user using "npm install steam-user" and I use basic example but I have an error.
Thanks for help :)

![zrzut ekranu z 2016-01-12 21 18 04](https://cloud.githubusercontent.com/assets/7270946/12275755/1ea22d2c-b972-11e5-901e-97ff1cac33b7.png)

**Comment by andrewda** [comment]
Post your code. I'm guessing the first line is `***` and its supposed to be a comment.

**Comment by DoctorMcKay** [comment]
Looks to me like a protobuf got corrupted. Can you screenshot the contents of `/protobufs` relative to the module root?

**Comment by ClassAxion** [comment]
![zrzut ekranu z 2016-01-12 22 01 48](https://cloud.githubusercontent.com/assets/7270946/12276804/1bed2c70-b978-11e5-9154-1e4c2aa3ff3d.png)

**Comment by DoctorMcKay** [comment]
That's not what I meant. I'm asking for `/usr/home/CTD8/node_modules/steam-user/protobufs`.

**Comment by ClassAxion** [comment]
Ok, sorry.

![2016-01-13_17-36-46](https://cloud.githubusercontent.com/assets/7270946/12300538/400daaea-ba1c-11e5-9ca1-efc0a66729da.png)

**Comment by DoctorMcKay** [comment]
Can you try reinstalling? Something may have gotten corrupted.

**Comment by ClassAxion** [comment]
Yes, but it still doesn't work :/

**Comment by ClassAxion** [comment]
So what can I do?

I uninstall steam-user and protobufjs using
```
npm uninstall steam-user
npm uninstall protobufjs
```

and I installed again
```
npm install steam-user
```

but it still doesn't work.
I use the example code (basicbot.js).
