### ISSUE TITLE
getSteamGuardDetails() gives false info

### ISSUE THREAD

**Issue by Yorkii** [DoctorMcKay/node-steam-user#51]
If there is 2fa enabled on account and you login it having no auth file getSteamGuardDetails() returns canTrade equal to false based on steam guard enabled time on this machine, but if you have mobile auth you can freely trade on new machines having secret keys? So it gives false info, am I right?

**Comment by Ne3tCode** [comment]
I can confirm false-negative result if the Steam Guard was activated before Steam began to remember the date of activation. Example:
`SteamUser.getSteamGuardDetails()` result:
```
enabled: true
enabledTime: 2012-12-21 18:29:57 // can be 'null'
machineTime: null
canTrade: false // WRONG!
```
Raw data:
```
{
  "is_steamguard_enabled": true,
  "timestamp_steamguard_enabled": 1356103797, // can be '0'
  "deprecated_newauthentication": [],
  "deprecated_machine_name_userchosen": "",
  "deprecated_timestamp_machine_steamguard_enabled": 0,
  "deprecated_authentication_exists_from_geoloc_before_mintime": null,
  "deprecated_machine_id": <redacted>,
  "session_data": [
    {
      "machine_id": <redacted>,
      "machine_name_userchosen": "",
      "timestamp_machine_steamguard_enabled": 0,
      "authentication_exists_from_geoloc_before_mintime": null,
      "newauthentication": [],
      "authentication_exists_from_same_ip_before_mintime": null,
      "public_ipv4": <redacted>
    }
  ],
  "is_twofactor_enabled": true,
  "timestamp_twofactor_enabled": 1449281153,
  "is_phone_verified": null
}
```

**Comment by Ne3tCode** [comment]
Not fixed. Incorrect result for:
`timestamp_steamguard_enabled == 0`
**or**
`2FA disabled or less than 7 days` and `timestamp_machine_steamguard_enabled == 0`

**Comment by DoctorMcKay** [comment]
If it's 0, does that **always** mean that it was enabled before they started tracking?

**Comment by Ne3tCode** [comment]
I think so. I dont know what result for disabled SteamGuard.

**Comment by DoctorMcKay** [comment]
I ask (and am hesitant to change it) as I've seen a value of 0 in `timestamp_machine_steamguard_enabled` when the sentry is brand-new.
