### ISSUE TITLE
[Error 503]

### ISSUE THREAD

**Issue by bulgakovk** [DoctorMcKay/node-steam-user#52]
Hi there. I'm always getting [Error 503] after the bot will run for about an hour. [Here are my sources.](https://github.com/bulgakovk/steamBot/blob/master/bot.js)

![default](https://cloud.githubusercontent.com/assets/8983736/12533025/1a903632-c234-11e5-85dd-87c5dc11804e.png)

**Comment by DoctorMcKay** [comment]
You've somehow managed to:

1. Ignore the CONTRIBUTING.md that tells you to post questions in the Steam group
2. Post in the wrong module's issue tracker
3. Post your Steam WebAPI key
