### ISSUE TITLE
gamesPlayed fails to actually load non-steam game?

### ISSUE THREAD

**Issue by charredgrass** [DoctorMcKay/node-steam-user#55]
I simply have `user.gamesPlayed("some string");` (where `user` is a `SteamUser` object) but it doesn't load into game. 

The module does not throw an error either, it just does nothing.

**Comment by DoctorMcKay** [comment]
Works for me.

```js
client.on('loggedOn', function(details) {
	console.log("Logged on, SteamID: " + client.steamID);
	client.setPersona(Steam.EPersonaState.Online); // did you remember this?
	client.gamesPlayed("Half-Life 3");
});
```

![](https://mckay.media/4NP18)

**Comment by andrewda** [comment]
I'm guessing you're calling `gamesPlayed` before logging in, or, as @DoctorMcKay said, before going setting your state to online.

**Comment by charredgrass** [comment]
Left out the `client.setPersona(Steam.EPersonaState.Online);`, sorry. I shouldn't have opened an issue for this, closing it now.

**Comment by Serhatttt** [comment]
Steam is not defined error please help me @DoctorMcKay
