### ISSUE TITLE
Error polling when hanging a notice of the receipt of things

### ISSUE THREAD

**Issue by nikadrenalin** [DoctorMcKay/node-steam-user#56]
when I get things with a partner, I hung a notice of this, as I have not looked it get an error "Error polling for trade offers: Error: HTTP error 403", how to solve it?

**Comment by DoctorMcKay** [comment]
At a certain point I'm going to just stop responding to issues that don't read the guidelines for contributing.

**Comment by nikadrenalin** [comment]
I apologize if my question is stupid, I read the documentation https://github.com/DoctorMcKay/node-steam-user

**Comment by Aareksio** [comment]
https://github.com/DoctorMcKay/node-steam-user/blob/master/CONTRIBUTING.md#issues

**Comment by nikadrenalin** [comment]
well thank you

**Comment by DoctorMcKay** [comment]
Sorry for being snippy. It's just very tiresome to get these emails every day.
