### ISSUE TITLE
My bot can't join to the public chat

### ISSUE THREAD

**Issue by MrKoijk** [DoctorMcKay/node-steam-user#57]
Sorry if I made dumb mistake but your node-steam-user is little bit different than node-steam from seishun (and I am not familiar with it, yet).
It is my code: `var user = new SteamUser(client);`
and
```
user.on('chatInvite', function(inviterID, chatID, chatName) {
  console.log("Got an invite to " + chatName + " from " + inviterID.getSteam3RenderedID());
  user.chatEnter(chatID); // Autojoin on invite
});

client.on('friendOrChatMessage', function(senderID, message, room) {
  // Respond to both chat room and private messages
  console.log("Received message from " + senderID.getSteam3RenderedID() + ": " + message);
  if (message == 'ping') {
    client.chatMessage(senderID, "pong"); // ChatMsg by default
  }
  if (message.indexOf('hello') != -1) {
    client.chatMessage(senderID, "Hi! How are you?"); // ChatMsg by default
  }
  if (message.indexOf('fine') != -1) {
    client.chatMessage(senderID, "That's good to hear"); // ChatMsg by default
  }
});
```
Can you help me? What am I doing wrong?

**Comment by MrKoijk** [comment]
On private chat bot answers easily but when I invite him to conversation he isn't joining :/

**Comment by MrKoijk** [comment]
And is there any way to handle 4 users at once?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/4/).**

You're looking for [`joinChat`](https://github.com/DoctorMcKay/node-steam-user#joinchatsteamid-callback).

You can run multiple Steam bots in one process. Just instantiate multiple SteamUser objects.
