### ISSUE TITLE
Steam Guard App Code: Strange delay

### ISSUE THREAD

**Issue by tbanov** [DoctorMcKay/node-steam-user#59]
From time to time my bot want me to add manually "Steam Guard App Code: " Is this some kind of server delay or what? Yesterday i have no problem with login without entering the twoFactorCode, but today i have to retry login maybe around 5 times (15 sec). How can i handle this.

Example of my code:
```
var client = new SteamUser();
var SteamTotp = require('steam-totp');
client.logOn({
    accountName: config.username,
    password: config.password,
    twoFactorCode: SteamTotp.generateAuthCode(config.secret) // I think that secret is OK because i can login every 7 of 10 times
});
```

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/4/).**

If I had to guess, I'd say that you're trying to login twice within a 30-second block. Codes can't be reused.

**Comment by tbanov** [comment]
Good to know that thanks. I will ask in group if i have additional questions.

**Comment by Kordonme** [comment]
@DoctorMcKay 
We have roughly the same code as @tbanov describes here and have no problem logging in within a few seconds. However, if the login is happening too fast after a disconnect, the app will try and acquire a code from you.
We simply set promptSteamGuardCode to false and listens for the steamGuard event, set a timeout and try again after 3-5 seconds.

**Comment by tbanov** [comment]
@Kordonme can you please paste an example here for those who are trying to avoid thay issue
