### ISSUE TITLE
Automatically notifies us when an application updates

### ISSUE THREAD

**Issue by wq9** [DoctorMcKay/node-steam-user#6]
[SteamDB](https://steamdb.info/faq/#how-are-we-getting-this-information) mentions that Steam's own update system automatically notifies us when an application or package updates.

So, instead of polling with `getProductChanges` method, is there a way to use Steam's own update system to get updates faster?

**Comment by DoctorMcKay** [comment]
That page is misleading. There's no "automatic" update system. They're just polling.

**Comment by wq9** [comment]
Ok so polling is the way to go I guess. What frequency should the polling be done?

**Comment by DoctorMcKay** [comment]
It's up to you. I use 5 seconds in my bots and it works fine.

**Comment by wq9** [comment]
Well, at longer polling interval, it will be faster to just make the bot listen on IRC #steamdb-announce. 

I found that in SteamDB, the changelist timestamps in the database are about 2-4 seconds behind, while the IRC messages come within 2 seconds after I receive a new change number. Then, after several minutes, Steam starts downloading an update.

Anyway, since there is no "automatic" update system, this issue can close. Thanks!

**Comment by DoctorMcKay** [comment]
I'm going to reopen this as I find a built-in polling system with events to be a good potential feature.

**Comment by DoctorMcKay** [comment]
See the new offerings in [v3.3.0](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v3.3.0).
