### ISSUE TITLE
Relogging with a new auth code?

### ISSUE THREAD

**Issue by autaut03** [DoctorMcKay/node-steam-user#60]
When autoRelogin is true, new auth code is not generated each time.. but it has to be regenerated before each login..

**Comment by DoctorMcKay** [comment]
No, it doesn't. This uses the same mechanism the proper Steam client uses to avoid that requirement.

**Comment by autaut03** [comment]
But after some time bot's getting logged out, and when newTrade event is fired I check escrow duration and it gives 503 HTTP error, all the time, until I fully reload the bot. It definitely logs out.

**Comment by DoctorMcKay** [comment]
That's irrelevant to this. You should be using `webLogOn` to refresh your web session as necessary.

**Comment by autaut03** [comment]
What do u mean? Can u please provide some piece of code example?

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-user#weblogon

**Comment by autaut03** [comment]
How do I know that session expired?
