### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by m4rve1337** [DoctorMcKay/node-steam-user#61]
How to identify exactly the message that was sent to the bot?

**Comment by williamokano** [comment]
Did you read the documentation?

https://github.com/DoctorMcKay/node-steam-user#id-events

**Comment by m4rve1337** [comment]
But how to handle message for example: "/me"?

**Comment by williamokano** [comment]
You get only the raw message, if you want to handle commands you should implement that.

For example

```javascript
if (message === '/me') {
    doSomething();
}
```

I don't think that this is the point of this lib. The lib provides the basic, you should implement the rest.

I recomment the reading of this post, it's a little bit outdated but, I believe that this can help you a little

https://firepowered.org/developer/create-a-steam-trade-bot-with-nodejs-iojs-updated-for-node-steam-v1-0/

PS.: sorry about the bad english

**Comment by m4rve1337** [comment]
ty

**Comment by m4rve1337** [comment]
But I saw a bot with if (message.infexOf === ''')

**Comment by williamokano** [comment]
Well, that depends, you can implement that several different ways.

As for me, my preferred way is using regular expressions, like in the tutorial.

But you can do it using indexOf, tokenizing the string and parsing the grammar.

In my opinion, the easiest way to implement that if using regex.

PS.: if you need commands with arguments, indexOf and regex are your best shot.

If simple commands (like just ```/me```, using just comparison works good as well)
