### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by m4rve1337** [DoctorMcKay/node-steam-user#62]
Why It don't working?
steamUser.on('friendMessage', function(message){
	if (message === "/send") {
		console.log("New message");
	}
});

**Comment by williamokano** [comment]
Please don't open new issues for the same question.

When you use === "/send" you have to ensure that the message has no spaces.

Just do a console.log(message) and check if the message you're receiving is exactly "/send", no spaces, no nothing.

**Comment by m4rve1337** [comment]
What?) What I need to do?

**Comment by m4rve1337** [comment]
steamUser.on('friendMessage', function(message){
	console.log(message);
});
I used this now and when my friend writed me on chat, nothing logged in console

**Comment by williamokano** [comment]
First, the callback function should take 2 arguments, SteamID and message.

Check this example:
```javascript
var SteamUser = require('../index.js'); // Replace this with `require('steam-user');` if used outside of the module directory
var client = new SteamUser();

client.logOn({
	"accountName": "username",
	"password": "password"
});

client.on('loggedOn', function(details) {
	console.log("Logged into Steam as " + client.steamID.getSteam3RenderedID());
	client.setPersona(SteamUser.Steam.EPersonaState.Online);
	client.gamesPlayed(440);
});

client.on('friendMessage', function (steamID, message) {
	console.log("Friend message from " + steamID.getSteam3RenderedID() + ": " + message);
});
```

**Comment by m4rve1337** [comment]
Not working...

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**
