### ISSUE TITLE
'tradeResponse' event never emitted

### ISSUE THREAD

**Issue by SenshiSentou** [DoctorMcKay/node-steam-user#65]
I noticed my tradeResponse handler was never called when a trade made by the bot was either accepted or declined. The handler looks like this:

```
client.on('tradeResponse', function(steamID, response, restrictions){
    console.log("Incoming trade response from " + steamID.getSteam3RenderedID());
    //[actual method body]
}
```

To make sure I wasn't doing something wrong on my end I added an extra `console.log()` call on top of the emitting method in `trading.js`:

```
SteamUser.prototype._handlers[Steam.EMsg.EconTrading_InitiateTradeResult] = function(body){
    // Is trade ID meaningful here? (sidenote: yes it is ;))
    console.log("tradeResponse id emit! "+body);
    this._emitIdEvent('tradeResponse', ..., ...);
}
```

Unless I'm messing up big-time, I'd venture to say it's broken. =)

**Comment by DoctorMcKay** [comment]
Are we talking about trade offers here?

**Comment by SenshiSentou** [comment]
The use case here is:

1. Bot sends a trade offer to a user
2. Bot waits for the user to accept or reject, which should trigger this callback.

Unless I'm misunderstanding what this event's supposed to represent?

**Comment by DoctorMcKay** [comment]
Yes, you're misunderstanding it. The event is for responses to trade *requests*, not trade *offers*. These things:

![](https://mckay.media/zJepQ)

You might want to look into [steam-tradeoffer-manager](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager).

**Comment by SenshiSentou** [comment]
Aaah alright, apologies then! I'll check out the other package, thanks!
