### ISSUE TITLE
Node-Steam-User#gamesPlayed() errors Illegal Value (ProtoBuf)

### ISSUE THREAD

**Issue by kondax** [DoctorMcKay/node-steam-user#66]
Upon running `SteamUser.gamesPlayed('test')`, the following error is spewed out:

> ProtoBuf.js:1769
     throw Error("Illegal value for "+this.toString(true)+" of type "+this.type.name+": "+val+" ("+msg+")");

__

> Error: Illegal value for [object Object] of type message: string (object expected)
    at Error (native)
    at .<anonymous> (ProtoBuf.js:1769:23)
    at ProtoBuf.Reflect.ElementPrototype.verifyValue (ProtoBuf.js:1865:25)
    at ProtoBuf.Reflect.FieldPrototype.verifyValue (ProtoBuf.js:3417:43)
    at MessagePrototype.set (ProtoBuf.js:2443:59)
    at Message (ProtoBuf.js:2367:42)
    at SteamUser.gamesPlayed (steam\lib\handlers\user\index.js:50:6)

Not sure why this occurs, any help is appreciated. I've stripped out some of the longer-file names for ease of reading.

**Comment by Aareksio** [comment]
Everything is working perfectly fine here, code sample may help to reproduce the problem.

My test code:
```js
var SteamUser = require('steam-user');
var SteamTotp = require('steam-totp');

var user = new SteamUser();
user.logOn({
	accountName: "xxx",
	password: "xxx",
	twoFactorCode: SteamTotp.getAuthCode("xxx")
});

user.on('webSession', function() {
	console.log('Logged in!');
	user.setPersona(SteamUser.Steam.EPersonaState.Online);
	user.gamesPlayed('Test');
});
```

**Comment by kondax** [comment]
Huh, strange. I set the Persona yet using the same gamesPlayed() function as you causes the ProtoBuf error.

**Comment by DoctorMcKay** [comment]
You're using node-steam, not node-steam-user.

**Comment by kondax** [comment]
Ah, yeah I am.

Issue still applies: https://github.com/DoctorMcKay/node-steam/tree/master/lib/handlers/user#gamesplayedgamesplayed

**Comment by DoctorMcKay** [comment]
My node-steam repo is just a fork from a long time ago. You shouldn't be using it or referencing it.

**Comment by kondax** [comment]
Ahh right. Okay, thanks bud.

**Comment by Aareksio** [comment]
@kondax Read the description of given function - especially this part:

> `gamesPlayed` is a [CMsgClientGamesPlayed](https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/steamclient/steammessages_clientserver.proto) object.

**Comment by kondax** [comment]
Yeah, I saw that. I provided an object with game_id but it said that
game_id wasn't a valid parameter or something along the lines. I'll
probably just leave that out.

**Comment by kondax** [comment]
Got it working by incorporating the object with an array.
