### ISSUE TITLE
live trading

### ISSUE THREAD

**Issue by ErickSkrauch** [DoctorMcKay/node-steam-user#67]
Is it posible to make live trading session, using this repo? I can create trade with [.trade(steamId)](https://github.com/DoctorMcKay/node-steam-user#tradesteamid), but when I accept trade, it's start to load trading modal:

![](http://joxi.ru/8AnXP58hq493zm?d=1)

And after ~10 sec steam drop trade, because loading timeout.
How to "accept" trade?

**Comment by Aareksio** [comment]
[This](https://github.com/DoctorMcKay/node-steam-user#traderesponse), [this](https://github.com/DoctorMcKay/node-steam-user#tradestarted) and probably [this](https://github.com/seishun/node-steam-trade).

**Comment by DoctorMcKay** [comment]
^

**Comment by ErickSkrauch** [comment]
Yeah, this was helpful. Thanks.
