### ISSUE TITLE
Forward logon reason

### ISSUE THREAD

**Issue by deStrO** [DoctorMcKay/node-steam-user#69]
Hello,

It should be nice to forward the logon result somewhere, because when the bot got disconnected, we never know why.

Thanks!

**Comment by DoctorMcKay** [comment]
You mean the [disconnected](https://github.com/DoctorMcKay/node-steam-user#disconnected) event?

**Comment by deStrO** [comment]
The logOn event, to know. we don't know the "status"

**Comment by DoctorMcKay** [comment]
I don't follow. If `loggedOn` is emitted, then it was OK. If there was a temporary failure (like `ServiceUnavailable` or `TryAnotherCM`) then it will keep trying to reconnect until it succeeds, or a permanent failure is encountered (which is emitted in the `error` event).
