### ISSUE TITLE
Cannot find module 'file-storage'

### ISSUE THREAD

**Issue by wq9** [DoctorMcKay/node-steam-user#7]
Using npm version 3.3.4 and nodejs v4.1.1, `file-storage` does not appear in node_modules.

Maybe the package name of `node-file-storage` can be changed from `file-manager` to `file-storage` or change the dependencies from `file-storage` to `file-manager`?

**Comment by DoctorMcKay** [comment]
Are you installing from npm or git?

**Comment by wq9** [comment]
I'm installing with `npm install`

**Comment by DoctorMcKay** [comment]
Like, you have `steam-user` as a dependency in your package.json and you're using `npm install` there?

Or you're doing `npm install steam-user`?

Or you've cloned/downloaded the repository and you used `npm install`?

**Comment by wq9** [comment]
I have `steam-user` as the only dependency in package.json and `npm install` there.

**Comment by DoctorMcKay** [comment]
You're installing it from Git that way, which I don't really support. Please install it from npm instead, like this:

    "steam-user": "^1.9.5"

This will pin it to 1.x.x, which means that you won't automatically get any future breaking changes. If you want to just install the current version every time regardless, you want:

    "steam-user": "*"
