### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Foltos2016** [DoctorMcKay/node-steam-user#72]
Sorry to bother here.

But i use steam.rip api. and lots of time see steam.rip site write STEAM RIP

(but steam not rip) only problem very lot of time get web inventory status (on USA)

You can fix it?

GA, USA
Web Inventories: Too many request

The problem afternoon start.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

**Comment by Foltos2016** [comment]
I write but nothing.

Why not fix it?

**Comment by Lagg** [comment]
How in god's name is @DoctorMcKay supposed to fix Valve's servers throttling you, you goddamned notification clogging fiend

**Comment by DoctorMcKay** [comment]
There is a problem with one of steam.rip's monitoring servers, but I haven't had the time to fix it nor is this the proper place to talk about it.
