### ISSUE TITLE
enableTwoFactor - status Code 84

### ISSUE THREAD

**Issue by rezz3x** [DoctorMcKay/node-steam-user#73]
When i am calling enableTwoFactor i am getting 84 as a status code, what does that mean?

**Comment by shaunidiot** [comment]
[RateLimitExceeded = 84;](https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd#L90)

Your account called some API too many times?

**Comment by rezz3x** [comment]
Oh, thanks that is the Problem.
Searched for a list of error's now i got one, thanks!

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**
