### ISSUE TITLE
[Q] Can I use redeemKey func to redeem Steam Wallet Codes?

### ISSUE THREAD

**Issue by infam0us** [DoctorMcKay/node-steam-user#77]
Is there a way to redeem Steam Wallet Codes? I've looked to the wiki and closed issues, couldn't find it.
https://store.steampowered.com/account/redeemwalletcode

POST Url: https://store.steampowered.com/account/confirmredeemwalletcode/
Parameters(1): 'wallet_code'

**Comment by andrewda** [comment]
Have you tried sending a POST request to that URL? Does it work?

**Comment by infam0us** [comment]
No, because it needs more work. Before you redeem wallet code, you have to create the wallet with your address info IF you don't have wallet yet.

**Comment by DoctorMcKay** [comment]
You cannot. If you want this implemented in something, make an issue in DoctorMcKay/node-steamstore.
