### ISSUE TITLE
webLogOn crash

### ISSUE THREAD

**Issue by Xeluim** [DoctorMcKay/node-steam-user#79]
Hello,

I'm running a webLogOn() function every X mins, and sometimes I get this error causing the bot to exit:

Error: Cannot log onto steamcommunity.com without first being connected to Steam network

Is there any safe guard to use prior calling it or any work around on your end?

Thanks.

**Comment by DoctorMcKay** [comment]
Before calling it, check that you're connected to Steam.

**Comment by Xeluim** [comment]
I already called logOn and the 'websession' event is emitted. How can I check if I'm connected to steam? 

I'm already logged In, Is there anyway to check If I'm connected to Steam servers ?

This thing happens every while, the bot meant to refresh the session every X mins. How can I know if I lost my connection to steam meanwhile?

Thanks.

**Comment by DoctorMcKay** [comment]
Being connected is the same thing as being logged on (not the same as being logged onto the web, but if your client session drops then so does your web session). If you're not connected, the `steamID` property will be `null`.
