### ISSUE TITLE
Friend request

### ISSUE THREAD

**Issue by Infrox** [DoctorMcKay/node-steam-user#82]
Hey, is it possible to detect friend requests? I don't see any event doing that.

**Comment by Aareksio** [comment]
https://github.com/DoctorMcKay/node-steam-user#friendrelationship

**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/). Such issues may be ignored!**

**Comment by Infrox** [comment]
I see now, thanks a lot!
