### ISSUE TITLE
Much time ask for Steam Guard App Code

### ISSUE THREAD

**Issue by Marow** [DoctorMcKay/node-steam-user#83]
Much times, when he crashed and restarted, or when i will start the bot, it says

`Steam Guard App Code:`

What is this? Why he ask this? Much times it works with login.... but what is this?

**Comment by DoctorMcKay** [comment]
>**Have a question about the module or coding in general? *Do not create a GitHub issue.* GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/). Such issues may be ignored!**
