### ISSUE TITLE
File-Manager error

### ISSUE THREAD

**Issue by Savikas** [DoctorMcKay/node-steam-user#85]
Hello,

```
/var/node/bots/node_modules/steam-user/node_modules/file-manager/index.js:138
                        fs.mkdirSync(path, 0o750);
                                           ^
SyntaxError: Unexpected token ILLEGAL
```

What could be the reason?
`

**Comment by DoctorMcKay** [comment]
What version of node.js are you using?

**Comment by decryptable** [comment]
I'm getting this error from using v0.12 on Ubuntu 14.04.05

**Comment by andrewda** [comment]
@decryptable Upgrade to *at least* v4.0.0. There's absolutely no reason to still be using v0.12.

**Comment by DoctorMcKay** [comment]
Ancient, unsupported versions of node are not supported.
