### ISSUE TITLE
`friendMessageEcho` doesnt seem to fire

### ISSUE THREAD

**Issue by yonilerner** [DoctorMcKay/node-steam-user#86]
My code:
```js
client.on('friendMessageEcho', (recipId, message) => {
    console.log(`We messaged ${recipId} with: ${message}`)
})
```
The callback is never called.

`chat.js:295` (`SteamUser.prototype._handlers[SteamUser.EMsg.ClientFriendMsgEchoToSender]`) is also not being called, which explains why the event is never emitted. I tried debugging this myself, but I quickly got in over my head.

UPDATE:
`messages.js:158` (`SteamUser.prototype._handleMessage`) never gets called with a message of `5578`.

**Comment by DoctorMcKay** [comment]
Why do you expect it to fire?

**Comment by yonilerner** [comment]
Hmm very good question, should have said that from the start.

This is what the comment says on that handler:

```js
/**
	 * Emitted when we receive a message sent by us on another logon.
	 * You can also listen for friendMessageEcho#steamid64 to only get messages sent to a specific user.
	 *
	 * @event SteamUser#friendMessageEcho
	 * @param {SteamID} recipientID - The SteamID of the message recipient
	 * @param {string} message - The message text
	 */
```

I understood that to mean that if I send a chat message to someone from, lets say, my desktop Steam login, then that handler would be called on my node server.

**Comment by DoctorMcKay** [comment]
Seems to work for me:

![](https://mckay.media/XVIM7)

**Comment by yonilerner** [comment]
How do you get it to show all of that debug information?

And here is a very minimal repository that demonstrates the bug: https://github.com/yonilerner/steam-user-test

Here is the output from node:

https://puu.sh/swJi9/1ce9534859.png

And while its running, Im sending this to one of my Steam friends from my desktop: 
https://puu.sh/swJjq/4127052c5b.png

**Comment by DoctorMcKay** [comment]
You can get debug output with `client.on('debug', console.log);`

If you aren't getting the event, then I really don't know what to tell you. Maybe Steam is in a bad mood.

**Comment by yonilerner** [comment]
Thanks for that. And yea, Im just not getting the event it seems. I guess I can try it on a different platform. Ill let you know if that makes a difference.

**Comment by Aareksio** [comment]
Works perfectly fine here. Tested on node v6.9.1 on WIndows 8.1 and Debian 8

![9eef9y](https://cloud.githubusercontent.com/assets/11166786/20689317/205fdd1c-b5c5-11e6-8064-1bbac0b4d88e.gif)

I think your account is not setting the presence to `Online` for some reason (just had the problm while creating test script, used `username` instead of `accountName` parameter in `logOn`). Make sure the account goes online before sending the messages.

My test code:
```JS
const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');

const secret = require('./secret');

let user = new SteamUser();
user.logOn({
    accountName: secret.username,
    password: secret.password,
    twoFactorCode: SteamTotp.getAuthCode(secret.sharedSecret)
});

user.on('debug', console.log);

user.on('loggedOn', () => {
    console.log('Logged in.');
    user.setPersona(SteamUser.Steam.EPersonaState.Online, 'Inu');
});

user.on('friendMessage', (steamId, message) => { console.log(`Message from: ${steamId} was: ${message}`); });
user.on('friendMessageEcho', (recipId, message) => { console.log(`We messaged ${recipId} with: ${message}`); });
```

**Comment by yonilerner** [comment]
If that were the case, then wouldnt I be unable to receive `friendMessage`s also? The `friendMessage`s are coming in just fine, but not `friendMessageEcho`.

Ill test again just to be sure.

**Comment by yonilerner** [comment]
This is most strange. Its clearly logging on, as you can see my nickname is being changed to Yoni1: 
![image](https://cloud.githubusercontent.com/assets/278810/20693016/6e036866-b590-11e6-8d06-e5d7276f5b0c.png)

And you can see here that messages sent to me are being received just fine: 
![image](https://cloud.githubusercontent.com/assets/278810/20693023/7f1c435c-b590-11e6-80e1-f3c11572028f.png)

But I clearly am not getting messages I send myself.

**Comment by yonilerner** [comment]
Just another data point to add to this strange situation: It turns out that if Two Factor Auth is disabled, this bug does not occur.
