### ISSUE TITLE
Improvement of gamesPlayed method

### ISSUE THREAD

**Issue by shqke** [DoctorMcKay/node-steam-user#87]
I think that method gamesPlayed can be improved by specifying appid when using type of shortcut (or at least using a fixed value).
Say we want to see a custom message at the chat area (for status message, debug purposes, etc.) which will be the same for desktop client chat window and friends list, mobile client friends list and https://steamcommunity.com/chat):
```javascript
const Long = require('bytebuffer').Long;

client.gamesPlayed([{
    game_id: new Long((2 << 24) | 250820, 0x80000000, true), // or just "-9223372036820970556"
    game_extra_info: 'Custom text'
}, 550]);
// 250820 - appid of SteamVR (always available and wont spoil profile play feed)
// and 550 of L4D2 for example while using list of games
```

Also it looks like that Steam need that high bit to display properly:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/steam/steamclientpublic.h#L1062

**Comment by DoctorMcKay** [comment]
>To play a single non-Steam game by name, use a single string (e.g. "Minecraft")

What's wrong with this?

**Comment by shqke** [comment]
`client.gamesPlayed("Team Fortress 3");` :
mobile client friends list:
![screenshot_2016-12-28-04-57-04](https://cloud.githubusercontent.com/assets/2848519/21512274/2fab5144-ccbc-11e6-9c9e-2dcd7b051668.png)

`client.gamesPlayed([ "Team Fortress 3", 440 ]);` :
mobile client friends list:
![screenshot_2016-12-28-04-58-20](https://cloud.githubusercontent.com/assets/2848519/21512276/50387806-ccbc-11e6-8ce7-a8d0818a2092.png)

`client.gamesPlayed({ game_id: 440, game_extra_info: "Team Fortress 3" });` :
webchat:
![__1](https://cloud.githubusercontent.com/assets/2848519/21512215/77a3e7be-ccbb-11e6-8359-8e07d710cd74.png)
steam client:
![__2](https://cloud.githubusercontent.com/assets/2848519/21512216/77a466d0-ccbb-11e6-98c0-e7f9c4eda9ec.png)

The only thing that shows "Team Fortress 3" correctly everywhere:
```
client.gamesPlayed([{
	game_id: new Long((2 << 24) | 440, 0x80000000, true),
	game_extra_info: 'Team Fortress 3'
}, 492240]);
```

**Comment by DoctorMcKay** [comment]
I cannot reproduce this.

![](https://mckay.media/VX60o)

**Comment by shqke** [comment]
Yes, I've attached a screen shot that shows result of this line and it has been made on Android 5.0.2 (official mobile Steam client). As you could see the message simply doesn't show up. As for other clients this code works just fine.

**Comment by DoctorMcKay** [comment]
The mobile app doesn't show non-Steam shortcut names even if launched through the official client.

**Comment by shqke** [comment]
Like I said in the beginning my whole point of using shortcut names was to provide 'status text' feature. Thus I think it wouldn't be too bad to have gamesPlayed slightly changed or overloaded to support a feature on mobile app. Maybe a fixed appid can be used (like SteamVR tool which wont spoil playfeed)? I doubt it will change anytime soon.

**Comment by DoctorMcKay** [comment]
Do arbitrary SteamVR messages show up on the mobile client?

**Comment by DoctorMcKay** [comment]
What does the desktop client show in the friends list? TF3 or SteamVR?

**Comment by shqke** [comment]
Everywhere is TF3.

**Comment by DoctorMcKay** [comment]
Okay, confirmed that does work on mobile and desktop, but I'm not sure I want to add something that amounts to a glitch to the module, as it's liable to break at any point in the future. Shortcut names are officially supported but using this thing is a glitch.
