### ISSUE TITLE
callback for 2 steam login sessions?

### ISSUE THREAD

**Issue by sp0ok3r** [DoctorMcKay/node-steam-user#89]
Is any way to detect when i enter in bot account, and start a game, and the bot closes all games idling?
![git](https://cloud.githubusercontent.com/assets/7952298/22174900/bfef9c3c-dfe1-11e6-9b27-fee81c593252.jpg)

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

You will get an `error` event, most likely with the EResult `LoggedInElsewhere`.
