### ISSUE TITLE
Incompatible result codes of event chatCreated and related callback

### ISSUE THREAD

**Issue by shqke** [DoctorMcKay/node-steam-user#91]
I've been looking over implementation of chat creation and found incompatible result types passing around:
```js
if(eresult != SteamUser.EResult.OK) {
	this._emitIdEvent('chatCreated', friendID, eresult);
} else {
	var self = this;
	this.joinChat(chatID, function(result) {
		self._emitIdEvent('chatCreated', friendID, result, chatID);
	});
}
```
As you can see we're passing EResult code on creation error and code of EChatRoomEnterResponse on false, since joinChat returns exactly EChatRoomEnterResponse. It leads to unknown error in case of any.

I'd suggest to remove autojoin.

**Comment by DoctorMcKay** [comment]
I never dealt with this because it was going to be a breaking change, which I avoid in non-major releases. I'm going to go ahead and close it now because chat rooms are pretty much moot with new Steam chat.
