### ISSUE TITLE
gamesPlayed doesn't have a force option

### ISSUE THREAD

**Issue by Vankxr** [DoctorMcKay/node-steam-user#94]
If you are playing a game on a certain machine, then you log on another machine and try to open the same game, steam prompts you to decide if you want to force the app to open, thus invalidating the other machine`s session, or if you want to cancel.

By default, steam-user does not have this feature, causing an EResult 6 when trying to notify steam you`re playing a game you were already playing in another machine.

**Comment by DoctorMcKay** [comment]
Do you get the 6 on the bot where you're trying to launch the game, or on the session where you're currently using it?

**Comment by Vankxr** [comment]
If I launch a game that was already launched in another machine, I immediatly get the 6

**Comment by sp0ok3r** [comment]
same here, it goes to the default error,

// It goes to the first -> *
client.on("error", function (e) {
            client.chatMessage(AdminID, "blablabla");
            console.error(Red + "Error: " + Yellow + "Logon failed, Invalid Password or playing in the account.");
* 
            if (e.result == Steam.EResult.InvalidPassword) {
                console.error(Red + "Error: " + Yellow + "Invalid Password, check config file.");

            } else if (e.result == Steam.EResult.LoggedInElsewhere) {
                client.gamesPlayed([0]);
                console.error(Red + "Error: " + Yellow + "Already logged in somewhere else.");

**Comment by Vankxr** [comment]
Got back to this after some time. Maybe setting something different to `launch_option_type`?

`message CMsgClientGamesPlayed {
	message GamePlayed {
		optional uint64 steam_id_gs = 1;
		optional fixed64 game_id = 2;
		optional uint32 game_ip_address = 3;
		optional uint32 game_port = 4;
		optional bool is_secure = 5;
		optional bytes token = 6;
		optional string game_extra_info = 7;
		optional bytes game_data_blob = 8;
		optional uint32 process_id = 9;
		optional uint32 streaming_provider_id = 10;
		optional uint32 game_flags = 11;
		optional uint32 owner_id = 12;
		optional string vr_hmd_vendor = 13;
		optional string vr_hmd_model = 14;
		optional uint32 launch_option_type = 15 [default = 0];
		optional int32 primary_controller_type = 16 [default = -1];
		optional string primary_steam_controller_serial = 17;
		optional uint32 total_steam_controller_count = 18 [default = 0];
		optional uint32 total_non_steam_controller_count = 19 [default = 0];
		optional uint64 controller_workshop_file_id = 20 [default = 0];
	}

	repeated .CMsgClientGamesPlayed.GamePlayed games_played = 1;
	optional uint32 client_os_type = 2;
}`

**Comment by sapphyrus** [comment]
I'm also searching for a fix

**Comment by DoctorMcKay** [comment]
Added in [3.21.0](https://github.com/DoctorMcKay/node-steam-user/releases/tag/v3.21.0).
