### ISSUE TITLE
Check if user is online before sending message

### ISSUE THREAD

**Issue by Eanna5** [DoctorMcKay/node-steam-user#95]
I need to make sure the recipient is online before I message him. I have loooked for this and this is what I found:

```
            client.getPersonas([SteamID], function (persona) {
            PersonaState = persona[SteamID].persona_state;
            console.log(PersonaState);
```

This returns null no matter what state I set for myself.
I am very new to node. Not sure where to look, there are no errors in the code.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/7-node-steam-user/).**

You can't get a user's persona_state through Steam if you aren't friends, I believe. You could check the WebAPI but that wouldn't work if their profile is private.
