### ISSUE TITLE
.logOn() is not calling event "webSession"

### ISSUE THREAD

**Issue by tambu22** [DoctorMcKay/node-steam-user#96]
that its when i do a .logOn() i get only the event "loggedOn" but not the "webSession". so i cant do anything that require API KEY

(my code works for like 3 months and now it stop working)
i got this error:

 
`at SteamTradeOffers.doAPICall (/myDir/node_modules/steam-tradeoffers/index.js:483:19)`
    `   at SteamTradeOffers.getOffer (/myDir/node_modules/steam-tradeoffers/index.js:170:23)`

i tryed adding ` steamUser.webLogOn();`  after a loggedOn status = Steam.EResult.OK, but it still dont do the webSession event

**Comment by DoctorMcKay** [comment]
Valve broke things; [see here](https://dev.doctormckay.com/topic/830-websession-not-fire-when-i-call-weblogon/).

**Comment by tambu22** [comment]
but thewn how can i setup the offers with oyut the COOKIES and session?

**Comment by tambu22** [comment]
looks like i found a solution:

`
var steamUser = new SteamU(steamClient);
var steamClient = new SteamC.CMClient();
var SteamWebLogOn    = require('steam-weblogon');
var steamWebLogOn = new SteamWebLogOn(steamClient, steamUser);         
steamWebLogOn.webLogOn(function(sessionID, newCookie){
              getSteamAPIKey({
                sessionID: sessionID,
                webCookie: newCookie
            }, function(err, APIKey) {
                offers.setup({
                    sessionID: sessionID,
                    webCookie: newCookie,
                    APIKey: APIKey
                });
                   steamuserinfo.setup(APIKey);

            });
        });`

**Comment by Cohedrin** [comment]
@tambu22 this is fixed as of around 40 minutes ago https://dev.doctormckay.com/topic/830-websession-not-fire-when-i-call-weblogon/#entry2773
