### ISSUE TITLE
doctormckay/steam-crypto is not in the npm registry.

### ISSUE THREAD

**Issue by T1MOXA** [DoctorMcKay/node-steam-user#99]
```
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'doctormckay/steam-crypto' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'steam-user'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/bot/idle
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bot/idle/npm-debug.log
npm ERR! not ok code 0
```

How to fix that ?

**Comment by DoctorMcKay** [comment]
```npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21```

update.

**Comment by DoctorMcKay** [comment]
The latest version of Node.js is 7.7.1. The latest version of npm is 4.3.0. You kind of don't.

Ubuntu's default repos don't have the latest versions of lots of software, Node.js and npm included.

**Comment by T1MOXA** [comment]
Hmm, OK, I'll look, thanks.

**Comment by DoctorMcKay** [comment]
You can install the latest versions of both on Ubuntu by running this as root:

```
wget https://www.doctormckay.com/installnode.sh
chmod +x installnode.sh
./installnode.sh 7
```

**Comment by T1MOXA** [comment]
Did not help...
"It worked"
...
node-v v0.10.25
npm ERR! npm -v 1.4.21

**Comment by DoctorMcKay** [comment]
You need to use `node` instead of `nodejs`. Also, you may need to delete your old npm installation. Find where it is with `which npm`.

**Comment by T1MOXA** [comment]
`# apt-get remove nodejs npm node
Package 'node' is not installed, so not removed
Package 'nodejs' is not installed, so not removed
Package 'npm' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  ax25-node gyp libax25 libc-ares-dev libc-ares2 libfile-copy-recursive-perl
  libjs-node-uuid libv8-3.14-dev libv8-3.14.5 openbsd-inetd update-inetd
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
# apt-get autoremove
Reading package lists... Done`

`Installing node.js version 7.7.1 64-bit for Linux...
--2017-03-02 19:30:24--  https://nodejs.org/dist/v7.7.1/node-v7.7.1-linux-x64.tar.gz
Saving to: ‘node-v7.7.1-linux-x64.tar.gz’
node-v7.7.1-linux-x 100%[=====================>]  14.82M  7.89MB/s   in 1.9s

2017-03-02 19:30:26 (7.89 MB/s) - ‘node-v7.7.1-linux-x64.tar.gz’ saved [15539454/15539454]

Installing npm...

Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-4.3.0.tgz
It worked`

But...
```
# npm -v
-bash: /usr/bin/npm: No such file or directory
# node -v
-bash: /usr/sbin/node: No such file or directory
# npm i @doctormckay/steam-crypto
-bash: /usr/bin/npm: No such file or directory
```

**Comment by DoctorMcKay** [comment]
You ran the installer as root?

**Comment by T1MOXA** [comment]
ls /usr/local/bin
easy_install      forever  node  pip   pip3.5  youtube-dl
easy_install-3.5  n        npm   pip3  wheel

**Comment by DoctorMcKay** [comment]
Is /usr/local/bin in your $PATH? What if you do `/usr/local/bin/node -v`?

**Comment by T1MOXA** [comment]
/usr/local/bin/node -v
v7.7.1

**Comment by DoctorMcKay** [comment]
Is /usr/local/bin in your $PATH?

**Comment by T1MOXA** [comment]
yes
